apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurantos-config
data:
  EUREKA_URL: "http://eureka-server:8761/eureka/"
  EUREKA_URI: "http://eureka-server:8761/eureka"
  CONFIG_URI: "http://config-server:8888"
  JWKS_URI: "http://auth-service:8081/.well-known/jwks.json"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "/"
  OPA_URL: "http://opa:8181"
  MINIO_ENDPOINT: "http://minio:9000"
  MINIO_BUCKET: "restaurantos-files"
  CLICKHOUSE_URL: "http://clickhouse:8123"
  CLICKHOUSE_DB: "clickhouse_analytics"
  AUTH_SERVICE_URI: "http://auth-service:8081"
  USER_SERVICE_URI: "http://user-service:8082"
  POS_SERVICE_URI: "http://pos-service:8084"
  FINANCE_SERVICE_URI: "http://finance-service:8086"
  PLATFORM_ADMIN_URI: "http://platform-admin-service:8096"
  PLATFORM_ADMIN_SERVICE_URI: "http://platform-admin-service:8096"
  SPRING_PROFILES_ACTIVE: "native"
  AUTH_COOKIE_SECURE: "true"
