import { chromium } from "@playwright/test";
import { login, openAndCheck, shot } from "./lib-login.mjs";
const b = await chromium.launch({ headless: true });
const ctx = await b.newContext({ viewport: { width: 1500, height: 950 } });
const pos = await ctx.newPage();
await login(pos, { email: "manager@terrace.local", password: "Terrace#Manager1" });
await openAndCheck(pos, "/app/pos", { settle: 5000 });
await pos.getByTestId("menu-grid").getByRole("button").filter({ hasText: /Seekh Kebab/i }).first().click();
await pos.waitForTimeout(700);
await pos.getByRole("button", { name: /send to kitchen/i }).first().click();
await pos.waitForTimeout(4000);
console.log("order fired");

const board = await ctx.newPage();
const r = await openAndCheck(board, "/app/kitchen/DEFAULT", { settle: 6000 });
const n0 = await board.getByTestId("kds-ticket-card").count();
console.log("cards:", n0, "| body:", r.body.replace(/\n+/g," | ").slice(0,220));
if (n0 === 0) { console.log("STILL EMPTY — cannot drive bump"); await b.close(); process.exit(0); }
console.log("first card:", (await board.getByTestId("kds-ticket-card").first().innerText()).replace(/\n+/g," | ").slice(0,140));
await board.getByTestId("kds-ticket-card").first().click();
await board.waitForTimeout(1200);
await shot(board, "j0-selected");
await board.keyboard.press("f");
await board.waitForTimeout(3500);
const n1 = await board.getByTestId("kds-ticket-card").count();
console.log("cards after F (bump):", n1);
await shot(board, "j1-after-bump");
await board.keyboard.press("r");
await board.waitForTimeout(3500);
const n2 = await board.getByTestId("kds-ticket-card").count();
console.log("cards after R (recall):", n2);
console.log("BUMP worked:", n1 < n0, "| RECALL worked:", n2 > n1);
await shot(board, "j2-after-recall");
await b.close();
