import { chromium } from "@playwright/test";
const OUT="/Users/muhammadumer/Documents/Projects/ResturantOS/.planning/audits/diagnosis/nlq-analytics-recheck";
const b=await chromium.launch(); const p=await (await b.newContext({viewport:{width:1440,height:1000}})).newPage();
p.on("response",r=>{if(/\/api\//.test(r.url())&&r.status()>=400)console.log("NET",r.status(),r.request().method(),r.url());});
await p.goto("http://localhost:3000/login",{waitUntil:"domcontentloaded"});
await p.waitForTimeout(2000);
console.log("INPUTS:", JSON.stringify(await p.evaluate(()=>Array.from(document.querySelectorAll("input,select,button")).map(e=>`${e.tagName}#${e.id}[name=${e.name||''}][type=${e.type||''}] "${(e.innerText||e.placeholder||'').trim()}"`))));
await p.locator('input[name="email"], input#email').first().fill("owner@terrace.local");
await p.locator('input[name="password"], input#password').first().fill("Terrace#Owner1");
await p.locator('button[type="submit"]').first().click();
await p.waitForTimeout(4000);
console.log("URL after pw:", p.url());
console.log("TEXT:", (await p.evaluate(()=>document.body.innerText)).slice(0,900));
console.log("INPUTS2:", JSON.stringify(await p.evaluate(()=>Array.from(document.querySelectorAll("input")).map(e=>`${e.id}[name=${e.name}][type=${e.type}] ph=${e.placeholder}`))));
await p.screenshot({path:`${OUT}/dbg-owner-login.png`,fullPage:true});
await b.close();
