#!/usr/bin/env bash
# Phase 13-13 — ROADMAP SC4, proved live: an administrator resets another user's password.
#
# SC4 asks for admin-initiated reset at BOTH tiers, for the reset to clear the login lockout, and
# for must_change_password to govern the next login. This script proves all three over real HTTP
# through the real gateway, which is the only kind of proof this phase accepts (D-30) — the audit
# found Phase 3 scored 24/24 by grepping source while its controller did not exist.
#
# WHY THIS SCRIPT IS THE EVIDENCE FOR Docs/known-gaps/notification-delivery.md
#
# 13-09 (D-31) resolved that self-service forgot-password ships DISABLED, because
# services/notification-service is an active Maven module with zero source files and nothing
# consumes PASSWORD_RESET_REQUESTED. That gap document names the admin reset as the recovery path
# that replaces it. Section 6 below asserts BOTH halves in the same run — the self-service endpoint
# answering RESET_DELIVERY_DISABLED, and the admin path that has just recovered a real user — so
# the document is backed by a measurement rather than by a promise.
#
# THE ASSERTION THAT IS THE WHOLE OF D-18
#
# A locked-out user is reset, and their NEXT login is the forced-change refusal (403) rather than
# the lockout (423). That single assertion is the difference between a reset that works and one
# that leaves the user staring at a lockout with no explanation, having already done the only thing
# the error told them to do. It is made from a GENUINELY locked account — five real wrong passwords
# through the gateway, with a control proving the correct password was refused 423 first.
#
# WHY TWO TENANTS ARE PROVISIONED RATHER THAN ONE FABRICATED
#
# A cross-tenant assertion against a made-up UUID proves only that a random id is not found, which
# is true of a completely broken API. Both tenants here are provisioned through the real platform
# API and both have a real admin who has really logged in. This matters more than usual: users is
# FORCE ROW LEVEL SECURITY and auth_user is NOSUPERUSER NOBYPASSRLS, but Testcontainers' Postgres
# user is a SUPERUSER, so the policy is INERT in every integration test in this repository. This
# script runs against the enforcing database and is the only place it is actually exercised.
#
# Prerequisites: the full dev stack, with gateway, auth-service, user-service and
# platform-admin-service running jars built at or after 13-13.
#
# Usage: bash scripts/e2e/phase13-admin-reset-e2e.sh

set -uo pipefail

. scripts/e2e/_phase13-lib.sh

# TOTP secrets, one file per address.
#
# enrol_and_login is always called as "$( … )", which is a SUBSHELL — a variable it assigns cannot
# reach this shell, so the obvious `LAST_TOTP_SECRET=$secret` silently produced an empty string and
# every later step-up login answered 401 TOTP_REQUIRED. That reads exactly like "the password is
# wrong", which is what three assertions in this script reported before the cause was found.
TOTP_DIR="$(mktemp -d)"
SUPERADMIN_EMAIL="${SUPERADMIN_EMAIL:-superadmin@softxlogic.com}"
SUPERADMIN_PASSWORD="${SUPERADMIN_PASSWORD:-Test@123!}"

# ── Throwaway identities ────────────────────────────────────────────────────────────────────
#
# Tenant ids are generated by platform_db and cannot be pinned. The BRANDS are pinned instead, and
# ProvisioningService.slugify is deterministic on them, so a re-run addresses the same rows rather
# than littering the database with a tenant per run. Cleanup resolves ids from the slugs.

BRAND_A="Phase13 AdminReset A"
SLUG_A="phase13-adminreset-a"
OWNER_A_EMAIL="owner@${SLUG_A}.local"

BRAND_B="Phase13 AdminReset B"
SLUG_B="phase13-adminreset-b"
OWNER_B_EMAIL="owner@${SLUG_B}.local"

VICTIM_EMAIL="victim@${SLUG_A}.local"
CASHIER_EMAIL="cashier@${SLUG_A}.local"
TADMIN_EMAIL="tadmin@${SLUG_A}.local"

OWNER_NEW_PASSWORD='AdmRst#Owner1x'
VICTIM_FIRST_PASSWORD='AdmRst#Victim1x'
VICTIM_FINAL_PASSWORD='AdmRst#Victim2y'
CASHIER_NEW_PASSWORD='AdmRst#Cash1x'
TADMIN_NEW_PASSWORD='AdmRst#Admin1x'
OWNER_B_FINAL_PASSWORD='AdmRst#OwnerB2y'

# ── Database access ─────────────────────────────────────────────────────────────────────────
#
# Two uses only: cleanup, and reading the audit row + the lockout columns back out of the enforcing
# database. Every role here is NOSUPERUSER NOBYPASSRLS and the tables are FORCE RLS, so the GUC
# lines are not ceremony — without them these statements report success while touching nothing.

auth_sql()     { docker exec -i restaurantos-postgres psql -U auth_user      -d auth_db     -v ON_ERROR_STOP=1 -qtA; }
user_sql()     { docker exec -i restaurantos-postgres psql -U user_service   -d user_db     -v ON_ERROR_STOP=1 -qtA; }
platform_sql() { docker exec -i restaurantos-postgres psql -U platform_admin -d platform_db -v ON_ERROR_STOP=1 -qtA; }
finance_sql()  { docker exec -i restaurantos-postgres psql -U finance_user   -d finance_db  -v ON_ERROR_STOP=1 -qtA; }

purge_everything() {
  local tenant_ids tid
  tenant_ids="$(printf '%s\n' \
    "SELECT id FROM tenants WHERE slug IN ('${SLUG_A}','${SLUG_B}')
       OR brand_name IN ('${BRAND_A}','${BRAND_B}');" | platform_sql 2>/dev/null || true)"

  for tid in $tenant_ids; do
    printf '%s\n' "
      SELECT set_config('app.current_tenant_id', '${tid}', false);
      DELETE FROM refresh_sessions WHERE tenant_id = '${tid}';
      DELETE FROM user_branch_roles WHERE tenant_id = '${tid}';
      DELETE FROM password_reset_tokens WHERE tenant_id = '${tid}';
      DELETE FROM password_history WHERE user_id IN (SELECT id FROM users WHERE tenant_id = '${tid}');
      DELETE FROM users WHERE tenant_id = '${tid}';
      DELETE FROM event_outbox WHERE tenant_id = '${tid}';
      DELETE FROM auth_tenants WHERE id = '${tid}';
    " | auth_sql > /dev/null 2>&1 || true
    printf '%s\n' "
      SELECT set_config('app.current_tenant_id', '${tid}', false);
      DELETE FROM branches WHERE tenant_id = '${tid}';
    " | user_sql > /dev/null 2>&1 || true
    printf '%s\n' "
      SELECT set_config('app.current_tenant_id', '${tid}', false);
      DELETE FROM accounting_periods WHERE tenant_id = '${tid}';
      DELETE FROM chart_of_accounts WHERE tenant_id = '${tid}';
    " | finance_sql > /dev/null 2>&1 || true
    printf '%s\n' "
      DELETE FROM event_outbox WHERE tenant_id = '${tid}';
      DELETE FROM tenant_features WHERE tenant_id = '${tid}';
      DELETE FROM usage_records WHERE tenant_id = '${tid}';
      DELETE FROM tenants WHERE id = '${tid}';
    " | platform_sql > /dev/null 2>&1 || true
  done

  printf '%s\n' "DELETE FROM auth_tenants WHERE slug IN ('${SLUG_A}','${SLUG_B}');" \
    | auth_sql > /dev/null 2>&1 || true
}

cleanup() {
  local code=$?
  set +e
  purge_everything
  rm -rf "${TOTP_DIR:-}" 2>/dev/null
  local tenants_left users_left
  tenants_left="$(printf '%s\n' \
    "SELECT count(*) FROM tenants WHERE slug IN ('${SLUG_A}','${SLUG_B}');" \
    | platform_sql 2>/dev/null | tail -1 || echo '?')"
  users_left="$(printf '%s\n' \
    "SELECT count(*) FROM users WHERE email LIKE '%@${SLUG_A}.local' OR email LIKE '%@${SLUG_B}.local';" \
    | auth_sql 2>/dev/null | tail -1 || echo '?')"
  echo "Cleaned up: tenants left = ${tenants_left}, disposable users left = ${users_left}"
  exit $code
}
trap cleanup EXIT

# A previous run killed between steps would otherwise leave rows that turn "slug already exists"
# into what looks like a defect in the code under test.
purge_everything

# ── Helpers ─────────────────────────────────────────────────────────────────────────────────

# Bodies are ALWAYS built from python argv, never as an inline literal: bash brace-expands
# -d "{\"a\":1,\"b\":2}" into two malformed fragments and runs curl twice (13-02), and re-parses
# escaped quotes away inside "$( … )" (13-07).
jbody() {
  python3 -c "
import json, sys
a = sys.argv[1:]
d = {}
for i in range(0, len(a), 2):
    k, v = a[i], a[i + 1]
    if v == '__null__':
        d[k] = None
    elif v in ('true', 'false'):
        d[k] = (v == 'true')
    else:
        d[k] = v
print(json.dumps(d))
" "$@"
}

# One request; status on the FIRST line, body on the rest.
#
# DELIBERATELY NOT RETRIED on the gateway's SERVICE_UNAVAILABLE fallback. A blind retry is right
# for a GET and wrong for a POST — and catastrophically wrong for THIS post, which mints a new
# credential and audits a row each time. Routes are warmed before the assertion phase instead.
req() {
  local method="$1" url="$2" token="${3:-}" body="${4:-}"
  local args=(-s -w '\n%{http_code}' -X "$method" "$url")
  [[ -n "$token" ]] && args+=(-H "Authorization: Bearer ${token}")
  [[ -n "$body"  ]] && args+=(-H "Content-Type: application/json" -d "$body")
  local response
  response="$(curl "${args[@]}")"
  printf '%s\n%s' "$(printf '%s' "$response" | tail -1)" "$(printf '%s' "$response" | sed '$d')"
}
status_of() { printf '%s' "$1" | head -1; }
body_of()   { printf '%s' "$1" | tail -n +2; }

pass() { echo "PASS: $1"; PHASE13_PASS=$((PHASE13_PASS + 1)); }
fail() { echo "FAIL: $1"; PHASE13_FAIL=$((PHASE13_FAIL + 1)); }

# TOTP in pure stdlib. pyotp is not installed on this machine's python3 and the phase threat
# register forbids installing a package to make a verification script run.
totp_now() {
  python3 -c "
import base64, hmac, hashlib, struct, sys, time
secret = sys.argv[1]
key = base64.b32decode(secret + '=' * (-len(secret) % 8), casefold=True)
mac = hmac.new(key, struct.pack('>Q', int(time.time()) // 30), hashlib.sha1).digest()
off = mac[-1] & 0x0F
print(str((struct.unpack('>I', mac[off:off+4])[0] & 0x7FFFFFFF) % 10**6).zfill(6))
" "$1"
}

provision_tenant() {
  local brand="$1" admin_email="$2" body result status response
  body="$(jbody brandName "$brand" adminEmail "$admin_email" tier GROWTH)"
  result="$(req POST "${GATEWAY}/api/v1/platform/tenants" "$SUPER_TOKEN" "$body")"
  status="$(status_of "$result")"
  response="$(body_of "$result")"
  if [[ "$status" != "201" ]]; then
    echo "SETUP FAILED: provisioning '${brand}' returned ${status}: ${response}" >&2
    return 1
  fi
  PROV_TENANT_ID="$(printf '%s' "$response" | json_get "['data']['tenantId']")"
  PROV_SLUG="$(printf '%s' "$response"      | json_get "['data']['slug']")"
  PROV_TEMP="$(printf '%s' "$response"      | json_get "['data']['tempPassword']")"
  [[ -n "$PROV_TENANT_ID" && "$PROV_TENANT_ID" != "None" ]]
}

clear_forced_change() {
  local email="$1" temp="$2" slug="$3" new_password="$4" login_body refusal change_token result
  login_body="$(jbody email "$email" password "$temp" tenantSlug "$slug")"
  refusal="$(curl_retry -X POST "${GATEWAY}/api/v1/auth/login" \
    -H "Content-Type: application/json" -d "$login_body")"
  change_token="$(change_token_from "$refusal" || true)"
  if [[ -z "$change_token" ]]; then
    echo "clear_forced_change: no change token for ${email}: ${refusal}" >&2
    return 1
  fi
  result="$(forced_change "$change_token" "$temp" "$new_password")"
  [[ "$(status_of "$result")" == "200" ]]
}

# Enrol a second factor and return a stepped-up access token. Required for any role holding
# finance.period.close or hr.payroll.approve — which OWNER and TENANT_ADMIN both do (D-29a).
# ORDER MATTERS: forced change FIRST, enrolment second, so the factor is not bound under a
# credential whoever provisioned the account still knows.
enrol_and_login() {
  local email="$1" password="$2" slug="$3" bootstrap uri secret verify_body login_body response
  bootstrap="$(jbody email "$email" password "$password" tenantSlug "$slug")"
  response="$(curl_retry -X POST "${GATEWAY}/api/v1/auth/2fa/bootstrap" \
    -H "Content-Type: application/json" -d "$bootstrap")"
  uri="$(printf '%s' "$response" | json_get "['data']['otpauthUri']" 2>/dev/null || true)"
  if [[ -z "$uri" || "$uri" == "None" ]]; then
    echo "enrol_and_login: no otpauth uri for ${email}: ${response}" >&2
    return 1
  fi
  secret="$(printf '%s' "$uri" | python3 -c "
import sys, urllib.parse as u
print(u.parse_qs(u.urlparse(sys.stdin.read().strip()).query)['secret'][0])
")"
  # Written to a file, not to a variable: see TOTP_DIR. Remembered because a LATER login for this
  # same account — after a platform reset, say — must step up again. TOTP enrolment survives a
  # password reset, and must: a reset replaces one factor, not both.
  printf '%s' "$secret" > "${TOTP_DIR}/${email}"
  verify_body="$(jbody email "$email" password "$password" tenantSlug "$slug" code "$(totp_now "$secret")")"
  curl_status -X POST "${GATEWAY}/api/v1/auth/2fa/bootstrap/verify" \
    -H "Content-Type: application/json" -d "$verify_body" > /dev/null
  login_body="$(jbody email "$email" password "$password" tenantSlug "$slug" totpCode "$(totp_now "$secret")")"
  response="$(curl_retry -X POST "${GATEWAY}/api/v1/auth/login" \
    -H "Content-Type: application/json" -d "$login_body")"
  printf '%s' "$response" | json_get "['data']['accessToken']"
}

# A current TOTP code for an address this run enrolled. Every OWNER and TENANT_ADMIN needs one:
# they hold finance.period.close and hr.payroll.approve, which trip mandatory step-up (D-29a).
totp_for() {
  local secret_file="${TOTP_DIR}/$1"
  [[ -f "$secret_file" ]] && totp_now "$(cat "$secret_file")" || printf ''
}

# Log in, printing status on the first line and the body on the rest, so the CALLER decides what a
# refusal means. tenant_login() swallows that distinction, and 423-vs-403 is the whole of D-18.
login_result() {
  local email="$1" password="$2" slug="$3" totp="${4:-}" body
  body="$(python3 -c "
import json, sys
b = {'email': sys.argv[1], 'password': sys.argv[2], 'tenantSlug': sys.argv[3]}
if sys.argv[4]:
    b['totpCode'] = sys.argv[4]
print(json.dumps(b))
" "$email" "$password" "$slug" "$totp")"
  req POST "${GATEWAY}/api/v1/auth/login" "" "$body"
}

echo "=== Phase 13-13: administrator-initiated password reset, over live HTTP (ROADMAP SC4) ==="
echo "gateway=${GATEWAY}"
echo "tenant A='${BRAND_A}'   tenant B='${BRAND_B}'"
echo

# ── 0. Setup: two real tenants, two real owners, one disposable victim ──────────────────────

SUPER_TOKEN="$(platform_login "$SUPERADMIN_EMAIL" "$SUPERADMIN_PASSWORD")"
if [[ -z "$SUPER_TOKEN" ]]; then
  echo "SETUP FAILED: the SuperAdmin could not log in — that is blocker B1, not SC4." >&2
  exit 1
fi
echo "SuperAdmin authenticated."

# Warm each route's load-balancer pool with a cheap GET, so no assertion below is the first request
# through it. See req() for why this replaces a blind 503 retry rather than supplementing one.
curl_status "${GATEWAY}/api/v1/platform/tenants?size=1" -H "Authorization: Bearer ${SUPER_TOKEN}" > /dev/null

provision_tenant "$BRAND_A" "$OWNER_A_EMAIL" || exit 1
TENANT_A_ID="$PROV_TENANT_ID"; SLUG_A_REAL="$PROV_SLUG"; OWNER_A_TEMP="$PROV_TEMP"
provision_tenant "$BRAND_B" "$OWNER_B_EMAIL" || exit 1
TENANT_B_ID="$PROV_TENANT_ID"; SLUG_B_REAL="$PROV_SLUG"; OWNER_B_TEMP="$PROV_TEMP"
echo "Provisioned tenant A=${TENANT_A_ID} (${SLUG_A_REAL}) and tenant B=${TENANT_B_ID} (${SLUG_B_REAL})"

clear_forced_change "$OWNER_A_EMAIL" "$OWNER_A_TEMP" "$SLUG_A_REAL" "$OWNER_NEW_PASSWORD" \
  || { echo "SETUP FAILED: tenant A's owner could not replace its temporary password" >&2; exit 1; }
clear_forced_change "$OWNER_B_EMAIL" "$OWNER_B_TEMP" "$SLUG_B_REAL" "$OWNER_NEW_PASSWORD" \
  || { echo "SETUP FAILED: tenant B's owner could not replace its temporary password" >&2; exit 1; }

OWNER_A_TOKEN="$(enrol_and_login "$OWNER_A_EMAIL" "$OWNER_NEW_PASSWORD" "$SLUG_A_REAL")" || true
OWNER_B_TOKEN="$(enrol_and_login "$OWNER_B_EMAIL" "$OWNER_NEW_PASSWORD" "$SLUG_B_REAL")" || true
if [[ -z "${OWNER_A_TOKEN:-}" || -z "${OWNER_B_TOKEN:-}" || "$OWNER_A_TOKEN" == "None" ]]; then
  echo "SETUP FAILED: an owner never obtained an access token" >&2
  exit 1
fi
echo "Both owners are online and hold real access tokens."

BRANCHES_A="$(curl_retry "${GATEWAY}/api/v1/branches" -H "Authorization: Bearer ${OWNER_A_TOKEN}")"
BRANCH_A_ID="$(printf '%s' "$BRANCHES_A" | python3 -c "
import sys, json
d = json.load(sys.stdin)['data']
rows = d if isinstance(d, list) else d.get('content', [])
print(next((r['id'] for r in rows if r.get('isHq') or r.get('hq')), rows[0]['id'] if rows else ''))
" 2>/dev/null || true)"
if [[ -z "$BRANCH_A_ID" ]]; then
  echo "SETUP FAILED: tenant A has no branch to assign roles at: ${BRANCHES_A}" >&2
  exit 1
fi

# The victim: a real staff account with a password it chose itself, so the lockout below is a real
# lockout of a real working credential rather than of a temporary one.
VICTIM_CREATE="$(req POST "${GATEWAY}/api/v1/users" "$OWNER_A_TOKEN" \
  "$(jbody email "$VICTIM_EMAIL" fullName "E2E Victim" branchId "$BRANCH_A_ID" roleCode CASHIER)")"
if [[ "$(status_of "$VICTIM_CREATE")" != "201" ]]; then
  echo "SETUP FAILED: could not create the disposable victim: $(body_of "$VICTIM_CREATE")" >&2
  exit 1
fi
VICTIM_ID="$(body_of "$VICTIM_CREATE"   | json_get "['data']['id']")"
VICTIM_TEMP="$(body_of "$VICTIM_CREATE" | json_get "['data']['tempPassword']")"
clear_forced_change "$VICTIM_EMAIL" "$VICTIM_TEMP" "$SLUG_A_REAL" "$VICTIM_FIRST_PASSWORD" \
  || { echo "SETUP FAILED: the victim could not replace its temporary password" >&2; exit 1; }
echo "Disposable victim ${VICTIM_ID} is online with a password of its own choosing."
echo

set +e   # errexit off for the assertion phase: assert_* return 1, and under -e the first failure
         # would silently skip every assertion after it. The exit code comes from phase13_summary.

# ── 1. Lock the victim out for real, then recover it — the whole of D-18 ────────────────────

echo "--- a genuinely locked account, recovered by an admin reset ---"

# The control first. Without it, "the login is refused" below is satisfied by a password this
# script got wrong, and every assertion after it would pass for the wrong reason.
PRE="$(login_result "$VICTIM_EMAIL" "$VICTIM_FIRST_PASSWORD" "$SLUG_A_REAL")"
assert_status 200 "$(status_of "$PRE")" "[control] the victim can log in immediately before the lockout"

# 13-09's lesson: five wrong-password requests are NOT five recorded failures — the gateway's own
# SERVICE_UNAVAILABLE fallback on a cold lb:// pool answered four of them in that run and the
# account never locked. So submit until the threshold trips and PRINT the statuses, so a failure
# here is diagnosable from the output alone.
LOCK_STATUSES=""
for _ in 1 2 3 4 5 6 7 8; do
  WRONG="$(login_result "$VICTIM_EMAIL" "DefinitelyWrong#9z" "$SLUG_A_REAL")"
  LOCK_STATUSES="${LOCK_STATUSES} $(status_of "$WRONG")"
  [[ "$(status_of "$WRONG")" == "423" ]] && break
done
echo "wrong-password attempt statuses:${LOCK_STATUSES}"

LOCKED="$(login_result "$VICTIM_EMAIL" "$VICTIM_FIRST_PASSWORD" "$SLUG_A_REAL")"
assert_status 423 "$(status_of "$LOCKED")" \
  "the CORRECT password is now refused 423 — the account is genuinely locked, not merely wrong"

# Plant a non-zero counter before the reset. handleFailedPassword ZEROES failed_login_count at the
# moment it trips the lock, so a genuinely locked account already reads 0 there and "0 afterwards"
# would pass against a reset that did nothing at all. 13-09 found exactly this and the same
# stagecraft is required here. locked_until needs no help — the real lockout path set it.
printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${TENANT_A_ID}', false);
  UPDATE users SET failed_login_count = 3 WHERE id = '${VICTIM_ID}';
" | auth_sql > /dev/null 2>&1

PRE_STATE="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${TENANT_A_ID}', false);
  SELECT failed_login_count || '|' || (locked_until IS NOT NULL) FROM users WHERE id = '${VICTIM_ID}';
" | auth_sql 2>/dev/null | tail -1)"
assert_status '3|true' "$PRE_STATE" \
  "[control] the database really shows a planted counter and a live lockout before the reset"

RESET="$(req POST "${GATEWAY}/api/v1/users/${VICTIM_ID}/reset-password" "$OWNER_A_TOKEN" \
  "$(jbody reason "locked out at the till")")"
assert_status 200 "$(status_of "$RESET")" "[SC4] the tenant admin resets the locked user's password"
RESET_BODY="$(body_of "$RESET")"
VICTIM_RESET_TEMP="$(printf '%s' "$RESET_BODY" | json_get "['data']['tempPassword']" 2>/dev/null || true)"
if [[ -n "$VICTIM_RESET_TEMP" && "$VICTIM_RESET_TEMP" != "None" ]]; then
  pass "the reset returns a temporary password to hand over out of band (the ONLY delivery channel)"
else
  fail "no temporary password in the reset response: ${RESET_BODY}"
fi
assert_contains "$RESET_BODY" '"mustChangePassword":true' \
  "the response says the forced-change flag was set, so the temp credential cannot become permanent"

POST_STATE="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${TENANT_A_ID}', false);
  SELECT failed_login_count || '|' || (locked_until IS NULL) || '|' || must_change_password
    FROM users WHERE id = '${VICTIM_ID}';
" | auth_sql 2>/dev/null | tail -1)"
assert_status '0|true|true' "$POST_STATE" \
  "read back from the ENFORCING database: counter cleared, lockout cleared, forced-change set (D-18)"

# THE assertion. 423 here would mean the reset "worked" and left the user exactly where they were.
RECOVERED="$(login_result "$VICTIM_EMAIL" "$VICTIM_RESET_TEMP" "$SLUG_A_REAL")"
assert_status 403 "$(status_of "$RECOVERED")" \
  "[D-18] the next login is the FORCED-CHANGE refusal, NOT the lockout — the reset actually unlocked"
assert_contains "$(body_of "$RECOVERED")" 'PASSWORD_CHANGE_REQUIRED' \
  "and the refusal says which gate it is, so a client knows what to render"

if clear_forced_change "$VICTIM_EMAIL" "$VICTIM_RESET_TEMP" "$SLUG_A_REAL" "$VICTIM_FINAL_PASSWORD"; then
  pass "the temporary password redeems the forced change"
else
  fail "the temporary password could not redeem the forced change"
fi

BACK="$(login_result "$VICTIM_EMAIL" "$VICTIM_FINAL_PASSWORD" "$SLUG_A_REAL")"
assert_status 200 "$(status_of "$BACK")" \
  "[SC4] and the user is back in the product with a password only they know"
SPENT="$(login_result "$VICTIM_EMAIL" "$VICTIM_RESET_TEMP" "$SLUG_A_REAL")"
assert_status 401 "$(status_of "$SPENT")" \
  "the temporary password is spent — it did not survive as a second credential"
echo

# ── 2. The tenant-tier refusals ─────────────────────────────────────────────────────────────

echo "--- the tenant-tier refusals, each with a control ---"

# (a) an ordinary staff account
STAFF_TOKEN="$(tenant_login "$VICTIM_EMAIL" "$VICTIM_FINAL_PASSWORD" "$SLUG_A_REAL" 2>/dev/null || true)"
if [[ -n "$STAFF_TOKEN" && "$STAFF_TOKEN" != "None" ]]; then
  assert_status 403 "$(status_of "$(req POST "${GATEWAY}/api/v1/users/${VICTIM_ID}/reset-password" \
    "$STAFF_TOKEN" "$(jbody reason "self service by the back door")")")" \
    "a cashier cannot reset anybody's password, including their own account's"
else
  fail "no staff token available for the authorization floor"
fi

# (b) anonymous
assert_status 401 "$(status_of "$(req POST "${GATEWAY}/api/v1/users/${VICTIM_ID}/reset-password" "" \
  "$(jbody reason "anonymous")")")" \
  "an anonymous caller cannot reset a password"

# (c) another tenant's user — against a SECOND genuinely provisioned tenant, with a control
LIST_B="$(req GET "${GATEWAY}/api/v1/users?size=50" "$OWNER_B_TOKEN")"
OWNER_B_ID="$(body_of "$LIST_B" | python3 -c "
import sys, json
print(next((u['id'] for u in json.load(sys.stdin)['data'] if u['email'] == '${OWNER_B_EMAIL}'), ''))
" 2>/dev/null || true)"
if [[ -n "$OWNER_B_ID" ]]; then
  pass "[control] tenant B's admin row exists and is visible to tenant B (${OWNER_B_ID})"

  X_RESET="$(req POST "${GATEWAY}/api/v1/users/${OWNER_B_ID}/reset-password" "$OWNER_A_TOKEN" \
    "$(jbody reason "cross tenant")")"
  assert_status 404 "$(status_of "$X_RESET")" \
    "tenant A cannot reset tenant B's admin (404, never 403 — a 403 confirms the id is real somewhere)"
  if printf '%s' "$(body_of "$X_RESET")" | grep -qE "${OWNER_B_EMAIL}|${TENANT_B_ID}"; then
    fail "the not-found body leaked the other tenant's address or id"
  else
    pass "the not-found body names neither the other tenant's address nor its id"
  fi
  # An id that exists NOWHERE must answer identically, or the pair is an enumeration oracle.
  assert_status 404 "$(status_of "$(req POST "${GATEWAY}/api/v1/users/$(uuidgen)/reset-password" \
    "$OWNER_A_TOKEN" "$(jbody reason "nobody at all")")")" \
    "and an id that exists nowhere answers identically, so the pair is not an oracle"

  # The control that tenant B's admin is untouched: it can still log in with the password it had.
  B_STILL="$(login_result "$OWNER_B_EMAIL" "$OWNER_NEW_PASSWORD" "$SLUG_B_REAL" "$(totp_for "$OWNER_B_EMAIL")")"
  assert_status 200 "$(status_of "$B_STILL")" \
    "[control] tenant B's admin still logs in with its OWN password — the refused reset changed nothing"
else
  fail "[control] could not find tenant B's admin in tenant B's own list: $(body_of "$LIST_B")"
fi

# (d) the privilege inversion: a TENANT_ADMIN resetting the tenant's OWNER
TA_CREATE="$(req POST "${GATEWAY}/api/v1/users" "$OWNER_A_TOKEN" \
  "$(jbody email "$TADMIN_EMAIL" fullName "E2E Tenant Admin" branchId "$BRANCH_A_ID" roleCode TENANT_ADMIN)")"
assert_status 201 "$(status_of "$TA_CREATE")" "the OWNER may create a TENANT_ADMIN (its own ceiling permits it)"
TADMIN_TEMP="$(body_of "$TA_CREATE" | json_get "['data']['tempPassword']" 2>/dev/null || true)"

TADMIN_TOKEN=""
if [[ -n "$TADMIN_TEMP" && "$TADMIN_TEMP" != "None" ]] \
   && clear_forced_change "$TADMIN_EMAIL" "$TADMIN_TEMP" "$SLUG_A_REAL" "$TADMIN_NEW_PASSWORD"; then
  TADMIN_TOKEN="$(enrol_and_login "$TADMIN_EMAIL" "$TADMIN_NEW_PASSWORD" "$SLUG_A_REAL" 2>/dev/null || true)"
fi

OWNER_A_ID="$(req GET "${GATEWAY}/api/v1/users?size=100" "$OWNER_A_TOKEN" | tail -n +2 | python3 -c "
import sys, json
print(next((u['id'] for u in json.load(sys.stdin)['data'] if u['email'] == '${OWNER_A_EMAIL}'), ''))
" 2>/dev/null || true)"

if [[ -z "$TADMIN_TOKEN" || "$TADMIN_TOKEN" == "None" || -z "$OWNER_A_ID" ]]; then
  fail "the created TENANT_ADMIN never came online, so the privilege inversion could not be exercised"
else
  pass "the created TENANT_ADMIN is fully online (created → forced change → enrolled → token)"

  # The control: this caller really can administer users. Without it the 403 below is satisfied by
  # a caller who simply lacks the authority, which proves nothing about the ceiling.
  CEIL_CONTROL="$(req POST "${GATEWAY}/api/v1/users/${VICTIM_ID}/reset-password" "$TADMIN_TOKEN" \
    "$(jbody reason "a legitimate reset by the tenant admin")")"
  assert_status 200 "$(status_of "$CEIL_CONTROL")" \
    "[control] the TENANT_ADMIN CAN reset an ordinary staff account — so the refusal below is the ceiling"

  CEIL="$(req POST "${GATEWAY}/api/v1/users/${OWNER_A_ID}/reset-password" "$TADMIN_TOKEN" \
    "$(jbody reason "privilege inversion attempt")")"
  assert_status 403 "$(status_of "$CEIL")" \
    "a TENANT_ADMIN is REFUSED resetting the tenant's OWNER — a privilege inversion, not a convenience"
  assert_contains "$(body_of "$CEIL")" 'ROLE_CEILING_EXCEEDED' \
    "the refusal says it is a ceiling refusal, not an opaque 500"
  if printf '%s' "$(body_of "$CEIL")" | grep -q 'rbac.manage'; then
    fail "the refusal named the permission codes it is withholding"
  else
    pass "the refusal names the role and a count, never the permission codes it withholds"
  fi

  # And nothing happened: the OWNER's own password still works. A refusal that already changed the
  # credential is not a refusal.
  OWNER_STILL="$(login_result "$OWNER_A_EMAIL" "$OWNER_NEW_PASSWORD" "$SLUG_A_REAL" "$(totp_for "$OWNER_A_EMAIL")")"
  assert_status 200 "$(status_of "$OWNER_STILL")" \
    "the refused reset left the OWNER's password untouched — it still logs in"
fi
echo

# ── 3. The platform tier ────────────────────────────────────────────────────────────────────

echo "--- the platform tier: a SuperAdmin rescues a tenant admin ---"

PLATFORM_RESET="$(req POST \
  "${GATEWAY}/api/v1/platform/tenants/${TENANT_B_ID}/users/${OWNER_B_ID}/reset-password" \
  "$SUPER_TOKEN" "$(jbody reason "tenant B lost its owner password — support ticket 4711")")"
assert_status 200 "$(status_of "$PLATFORM_RESET")" \
  "[SC4] the SuperAdmin resets a tenant admin through the platform API"
OWNER_B_RESET_TEMP="$(body_of "$PLATFORM_RESET" | json_get "['data']['tempPassword']" 2>/dev/null || true)"
if [[ -n "$OWNER_B_RESET_TEMP" && "$OWNER_B_RESET_TEMP" != "None" ]]; then
  pass "the platform reset returns a temporary password (there is no email path — D-31)"
else
  fail "no temporary password in the platform reset response: $(body_of "$PLATFORM_RESET")"
fi

# The rescue completes: forced change, then a real login. Without this the platform reset is a 200
# that proves nothing about whether the tenant got its account back.
if clear_forced_change "$OWNER_B_EMAIL" "$OWNER_B_RESET_TEMP" "$SLUG_B_REAL" "$OWNER_B_FINAL_PASSWORD"; then
  pass "tenant B's admin completes the forced change with the SuperAdmin's temporary password"
else
  fail "tenant B's admin could not complete the forced change"
fi
B_BACK="$(login_result "$OWNER_B_EMAIL" "$OWNER_B_FINAL_PASSWORD" "$SLUG_B_REAL" "$(totp_for "$OWNER_B_EMAIL")")"
assert_status 200 "$(status_of "$B_BACK")" \
  "[SC4] and tenant B's admin is back in, so the rescue is complete rather than merely accepted"

# A tenant token on the platform endpoint. It is a real, valid, fully privileged tenant credential.
assert_status 403 "$(status_of "$(req POST \
  "${GATEWAY}/api/v1/platform/tenants/${TENANT_A_ID}/users/${VICTIM_ID}/reset-password" \
  "$OWNER_A_TOKEN" "$(jbody reason "tenant token on the platform door")")")" \
  "a real tenant OWNER token is REFUSED at the platform reset endpoint"
assert_status 401 "$(status_of "$(req POST \
  "${GATEWAY}/api/v1/platform/tenants/${TENANT_A_ID}/users/${VICTIM_ID}/reset-password" \
  "" "$(jbody reason "anonymous on the platform door")")")" \
  "and an anonymous caller is refused there too"

# A reset with no reason is refused at both tiers: every reset is audited and a row that cannot say
# why is one somebody has to interpret rather than read (T-13-13-E).
assert_status 400 "$(status_of "$(req POST \
  "${GATEWAY}/api/v1/platform/tenants/${TENANT_B_ID}/users/${OWNER_B_ID}/reset-password" \
  "$SUPER_TOKEN" '{}')")" \
  "a platform reset with NO REASON is refused (T-13-13-E)"
assert_status 400 "$(status_of "$(req POST "${GATEWAY}/api/v1/users/${VICTIM_ID}/reset-password" \
  "$OWNER_A_TOKEN" '{}')")" \
  "and so is a tenant reset with no reason"
echo

# ── 4. The audit trail — read out of the outbox, not out of a response ──────────────────────

echo "--- the audit event, read from event_outbox on the enforcing database ---"

# Read the envelope of the most recent admin reset for tenant B — the PLATFORM one, where the actor
# and the target are unambiguously different PEOPLE in different id spaces.
AUDIT_B="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${TENANT_B_ID}', false);
  SELECT envelope_json FROM event_outbox
   WHERE event_type = 'ADMIN_PASSWORD_RESET' AND tenant_id = '${TENANT_B_ID}'
   ORDER BY created_at DESC LIMIT 1;
" | auth_sql 2>/dev/null | tail -1)"

if [[ -z "$AUDIT_B" ]]; then
  fail "no ADMIN_PASSWORD_RESET row in event_outbox — the audit write did not commit. 13-14 found an"
  echo "      impersonation audit that could never commit at all while the method reported success."
else
  pass "the reset wrote a PERSISTED audit row (not merely called a publisher)"
  AUDIT_FIELDS="$(printf '%s' "$AUDIT_B" | python3 -c "
import sys, json
p = json.load(sys.stdin)['payload']
print(p.get('actingAdministratorId',''))
print(p.get('targetUserId',''))
print(p.get('actorTier',''))
print(p.get('reason',''))
print(json.dumps(p))
")"
  AUDIT_ACTOR="$(printf  '%s' "$AUDIT_FIELDS" | sed -n 1p)"
  AUDIT_TARGET="$(printf '%s' "$AUDIT_FIELDS" | sed -n 2p)"
  AUDIT_TIER="$(printf   '%s' "$AUDIT_FIELDS" | sed -n 3p)"
  AUDIT_REASON="$(printf '%s' "$AUDIT_FIELDS" | sed -n 4p)"
  AUDIT_PAYLOAD="$(printf '%s' "$AUDIT_FIELDS" | sed -n 5p)"

  assert_status "$OWNER_B_ID" "$AUDIT_TARGET" "the audit row names the TARGET whose password changed"
  if [[ -n "$AUDIT_ACTOR" && "$AUDIT_ACTOR" != "$AUDIT_TARGET" ]]; then
    pass "the acting administrator and the target are DIFFERENT values (${AUDIT_ACTOR} vs ${AUDIT_TARGET})"
  else
    fail "the audit row names the target as its own actor — the impersonation defect, repeated"
  fi
  assert_status 'PLATFORM' "$AUDIT_TIER" "the row says which tier acted, so the two id spaces are separable"
  assert_contains "$AUDIT_REASON" 'support ticket 4711' "the reason the operator gave is recorded verbatim"

  # No credential material anywhere in the payload, checked by VALUE. A key-set check passes against
  # a payload that republishes the password under a harmless name — 13-09 falsified exactly that.
  if printf '%s' "$AUDIT_PAYLOAD" | grep -qF -- "$OWNER_B_RESET_TEMP"; then
    fail "the audit payload contains the temporary password — event_outbox is durable and replicated"
  else
    pass "the audit payload contains no password material at all"
  fi
  if printf '%s' "$AUDIT_PAYLOAD" | grep -qF -- "$OWNER_B_FINAL_PASSWORD"; then
    fail "the audit payload contains the user's chosen password"
  else
    pass "nor the password the user subsequently chose"
  fi
fi

# The tenant tier writes its own row, in its own tenant, naming its own actor.
AUDIT_A_ACTOR="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${TENANT_A_ID}', false);
  SELECT envelope_json FROM event_outbox
   WHERE event_type = 'ADMIN_PASSWORD_RESET' AND tenant_id = '${TENANT_A_ID}'
   ORDER BY created_at ASC LIMIT 1;
" | auth_sql 2>/dev/null | tail -1 | python3 -c "
import sys, json
try:
    p = json.load(sys.stdin)['payload']
    print(p.get('actingAdministratorId','') + '|' + p.get('actorTier',''))
except Exception:
    print('')
" 2>/dev/null || true)"
assert_status "${OWNER_A_ID}|TENANT" "$AUDIT_A_ACTOR" \
  "the tenant tier's first row names the OWNER who actually made the call, and its own tier"

# And no credential reached the auth-service log either.
if grep -qF -- "$OWNER_B_RESET_TEMP" "${PHASE13_REPO_ROOT}/logs/auth-service.log" 2>/dev/null; then
  fail "the temporary password appears in auth-service's log file"
else
  pass "the temporary password does not appear in any auth-service log this run wrote"
fi
echo

# ── 5. Nothing was persisted in an idempotency record ───────────────────────────────────────

echo "--- the temporary password is not durable anywhere it should not be ---"

IDEMPOTENT_LEAK="$(printf '%s\n' "
  SELECT count(*) FROM idempotency_keys
   WHERE response_json LIKE '%${OWNER_B_RESET_TEMP}%';
" | platform_sql 2>/dev/null | tail -1 || echo '?')"
assert_status 0 "$IDEMPOTENT_LEAK" \
  "no idempotency record captured the temp password — response_json is plain text and is never purged (13-10)"

HASHED="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${TENANT_B_ID}', false);
  SELECT (password_hash <> '${OWNER_B_RESET_TEMP}') AND (password_hash LIKE '\$2%')
    FROM users WHERE id = '${OWNER_B_ID}';
" | auth_sql 2>/dev/null | tail -1)"
assert_status 't' "$HASHED" "the stored value is a bcrypt hash and is not the password itself"
echo

# ── 6. The recovery story: the disabled self-service path and its documented alternative ────

echo "--- the recovery story D-31 promised, both halves in one run ---"

SELF_SERVICE="$(req POST "${GATEWAY}/api/v1/auth/reset-password/request" "" \
  "$(jbody email "$VICTIM_EMAIL" tenantSlug "$SLUG_A_REAL")")"
assert_status 200 "$(status_of "$SELF_SERVICE")" \
  "the self-service reset request is accepted (it must never be an account-existence oracle)"
assert_contains "$(body_of "$SELF_SERVICE")" 'RESET_DELIVERY_DISABLED' \
  "…and says it cannot deliver, rather than silently doing nothing (13-09, D-31)"

# The proof that the alternative the gap document names actually exists: no token row was minted by
# the disabled request, and yet the user above was genuinely recovered by the admin path.
TOKENS_MINTED="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${TENANT_A_ID}', false);
  SELECT count(*) FROM password_reset_tokens
   WHERE user_id = '${VICTIM_ID}' AND purpose = 'RESET' AND used_at IS NULL;
" | auth_sql 2>/dev/null | tail -1)"
assert_status 0 "$TOKENS_MINTED" \
  "the disabled request minted NO live reset token, so nothing is waiting for a message that will not come"
echo

phase13_summary
