#!/usr/bin/env bash
# Phase 13-10 — ROADMAP SC2, proved live: a tenant provisioned through the real API logs in.
#
# WHY THIS EXISTS (D-30). The audit found .planning/phases/03-*/03-VERIFICATION.md scoring Phase 3
# "24/24 passed" while citing a controller that does not exist, because that verification grepped
# source. Blocker B2 — "a tenant created via POST /api/v1/platform/tenants cannot log in" — survived
# inside a phase marked complete for exactly that reason. This script refutes B2 the only way it can
# be refuted: by creating a tenant over HTTP through the gateway and then logging into it.
#
# It also does what no integration test in platform-admin-service can. Its ITs stub auth-service,
# user-service and finance-service with WireMock, so a saga that talks to all three correctly and a
# saga whose stubs merely agree with its bugs are indistinguishable there — which is precisely how
# extractBranchId stayed green for months while parsing a response shape user-service has never
# produced. And Testcontainers' Postgres user is a SUPERUSER, so no RLS defect on any of these write
# paths is visible to any suite. Every role this script reads with — auth_user, user_service,
# platform_admin, finance_user — is NOSUPERUSER NOBYPASSRLS on the live dev databases, so every row
# it asserts on was written under a policy that is really enforced.
#
# WHAT IT PROVES, one PASS line per point of blocker B2
#   1. The provisioning response carries the temporary password (it carried a login url in its place).
#   2. The platform tenant is ACTIVE.
#   3. An auth_tenants row exists for the slug, ACTIVE — nothing in application code wrote one before.
#   4. Exactly one branch exists for the tenant, flagged headquarters (isHq was never sent).
#   5. The provisioning event's aggregate id IS the real branch row (it was a random UUID).
#   6. One active OWNER branch-role row exists for the admin at that branch (it never existed).
#   7. The chart of accounts was seeded.
#   8. THE CRITERION: that admin authenticates through the gateway and reaches a tenant-scoped
#      endpoint.
#   9. A failed provision leaves no orphaned active branch and no orphaned admin — compensation is
#      forced, not asserted about.
#
# ON THE LOGIN NOT BEING A STRAIGHT 200
# A freshly provisioned OWNER meets two gates before it holds a token, in this order:
#   1. 403 PASSWORD_CHANGE_REQUIRED — the account carries must_change_password (13-06 writes it,
#      13-08 made login read it). The refusal hands back a single-use change token.
#   2. 401 TOTP_ENROLLMENT_REQUIRED — OWNER holds rbac.manage, requiresTotpStepUp fires on it, and a
#      new account has no enrolled factor. That is decision D-29a working as decided.
# Neither is a provisioning failure, and both are structurally GOOD NEWS for B2: enforceTotpStepUp
# runs AFTER permissionResolver.resolveDefault, so being asked to enrol is itself proof that the
# branch assignment resolved. The B2 assertion below therefore tests that distinction — the response
# must not say "no active branch assignments" and must not be a credential rejection — rather than
# testing a status code. Both gates are then cleared over the real public endpoints, so the token
# claims are asserted against a token that was actually issued.
#
# PRECONDITIONS
#   - Docker infra up; gateway, auth-service, user-service, finance-service and
#     platform-admin-service running and Eureka-registered.
#   - platform-admin-service and user-service MUST be running jars built AFTER plan 13-10, and
#     auth-service a jar built after 13-06. Against a stale platform-admin jar the provisioning call
#     500s at step 5 (provision-admin now requires branchId and roleCode) and this script fails
#     early rather than reporting a confident, meaningless pass.
#   - Nothing here restarts anything.
#
# Usage: bash scripts/e2e/phase13-provisioning-e2e.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/../.." && pwd)"
cd "$REPO_ROOT"
# shellcheck disable=SC1091
. scripts/e2e/_phase13-lib.sh

SUPERADMIN_EMAIL="${SUPERADMIN_EMAIL:-superadmin@softxlogic.com}"
SUPERADMIN_PASSWORD="${SUPERADMIN_PASSWORD:-Test@123!}"

# ── Throwaway identities ────────────────────────────────────────────────────────────────────
#
# The tenant id is generated by platform_db, so it cannot be pinned the way the 13-06 seam script
# pins its uuid5. The BRAND is pinned instead, and ProvisioningService.slugify is deterministic on
# it, so a re-run addresses the same rows rather than littering the database with a tenant per run.
# Cleanup resolves ids from the slug.
BRAND="Phase13 Provisioning E2E"
SLUG="phase13-provisioning-e2e"
ADMIN_EMAIL="owner@${SLUG}.local"

# The negative case. Its slug is pre-claimed in auth_db by a tenant that does not exist anywhere
# else, so registerTenant answers 409 STATE_INVALID — a mid-saga failure AFTER the branch was
# created, which is what makes branch compensation observable.
COLLIDE_BRAND="Phase13 Provisioning Collide"
COLLIDE_SLUG="phase13-provisioning-collide"
COLLIDE_EMAIL="owner@${COLLIDE_SLUG}.local"
COLLIDE_HOLDER_ID="$(python3 -c "
import uuid
print(uuid.uuid5(uuid.UUID('6ba7b810-9dad-11d1-80b4-00c04fd430c8'),
                 'restaurantos/e2e/phase13-provisioning/slug-holder'))
")"

FORCED_NEW_PASSWORD='Prov#Owner1x'

# ── Database access ─────────────────────────────────────────────────────────────────────────
#
# Every role below is NOSUPERUSER NOBYPASSRLS on these databases, so the GUC lines are not
# ceremony: branches, chart_of_accounts, accounting_periods, users and user_branch_roles are all
# FORCE ROW LEVEL SECURITY on app.current_tenant_id. Without the GUC these SELECTs return zero rows
# and these DELETEs report success while deleting nothing. auth_tenants is deliberately NOT scoped
# (it is the pre-tenant-context lookup login performs) so it needs none.

auth_sql()     { docker exec -i restaurantos-postgres psql -U auth_user      -d auth_db     -v ON_ERROR_STOP=1 -qtA; }
user_sql()     { docker exec -i restaurantos-postgres psql -U user_service   -d user_db     -v ON_ERROR_STOP=1 -qtA; }
platform_sql() { docker exec -i restaurantos-postgres psql -U platform_admin -d platform_db -v ON_ERROR_STOP=1 -qtA; }
finance_sql()  { docker exec -i restaurantos-postgres psql -U finance_user   -d finance_db  -v ON_ERROR_STOP=1 -qtA; }

# ── Cleanup ─────────────────────────────────────────────────────────────────────────────────

purge_everything() {
  local tenant_ids
  tenant_ids="$(printf '%s\n' \
    "SELECT id FROM tenants WHERE slug IN ('${SLUG}','${COLLIDE_SLUG}')
       OR brand_name IN ('${BRAND}','${COLLIDE_BRAND}');" | platform_sql 2>/dev/null || true)"

  local tid
  for tid in $tenant_ids; do
    printf '%s\n' "
      SELECT set_config('app.current_tenant_id', '${tid}', false);
      DELETE FROM refresh_sessions WHERE tenant_id = '${tid}';
      DELETE FROM user_branch_roles WHERE tenant_id = '${tid}';
      DELETE FROM password_reset_tokens WHERE tenant_id = '${tid}';
      DELETE FROM password_history WHERE user_id IN (SELECT id FROM users WHERE tenant_id = '${tid}');
      DELETE FROM users WHERE tenant_id = '${tid}';
      DELETE FROM auth_tenants WHERE id = '${tid}';
    " | auth_sql > /dev/null 2>&1 || true
    printf '%s\n' "
      SELECT set_config('app.current_tenant_id', '${tid}', false);
      DELETE FROM branches WHERE tenant_id = '${tid}';
    " | user_sql > /dev/null 2>&1 || true
    printf '%s\n' "
      SELECT set_config('app.current_tenant_id', '${tid}', false);
      DELETE FROM accounting_periods WHERE tenant_id = '${tid}';
      DELETE FROM chart_of_accounts WHERE tenant_id = '${tid}';
    " | finance_sql > /dev/null 2>&1 || true
    printf '%s\n' "
      DELETE FROM event_outbox WHERE tenant_id = '${tid}';
      DELETE FROM tenant_features WHERE tenant_id = '${tid}';
      DELETE FROM usage_records WHERE tenant_id = '${tid}';
      DELETE FROM tenants WHERE id = '${tid}';
    " | platform_sql > /dev/null 2>&1 || true
  done

  # The pre-claimed slug and any auth_tenants row left by a run killed mid-flight.
  printf '%s\n' "
    DELETE FROM auth_tenants WHERE id = '${COLLIDE_HOLDER_ID}'
       OR slug IN ('${SLUG}','${COLLIDE_SLUG}');
  " | auth_sql > /dev/null 2>&1 || true
}

cleanup() {
  local code=$?
  set +e
  purge_everything
  echo "Cleaned up throwaway tenants '${SLUG}' and '${COLLIDE_SLUG}'"
  exit $code
}
trap cleanup EXIT

# Also purge BEFORE starting: a previous run killed between steps would otherwise leave rows that
# turn "slug already exists" into what looks like a defect in the code under test.
purge_everything

# ── Helpers ─────────────────────────────────────────────────────────────────────────────────

# Bodies are ALWAYS built in a variable, never inline inside "$( … )". An inline
# -d "{\"a\":1,\"b\":2}" is BRACE-EXPANDED by bash into two malformed fragments and curl runs twice
# — which in 13-02 produced a confident FAIL for a request that, sent correctly, succeeds.
json() { python3 -c "
import json, sys
print(json.dumps(json.loads(sys.argv[1])))
" "$1"; }

# "The request reached the service and was answered on its merits" — borrowed from 13-02, where
# assert_not_status alone once passed on a gateway 503, reporting an authorization success for a
# request that never arrived.
assert_authorized() {
  local status="${1:-}" description="${2:-}"
  case "$status" in
    401|403|404|5??|000)
      echo "FAIL: ${description} — got ${status}, which is not the service answering on the merits"
      PHASE13_FAIL=$((PHASE13_FAIL + 1))
      ;;
    *)
      echo "PASS: ${description} (${status})"
      PHASE13_PASS=$((PHASE13_PASS + 1))
      ;;
  esac
}

# TOTP in pure stdlib. pyotp is not installed on this machine's python3, and the phase threat
# register forbids installing a package to make a verification script run — a verification script
# that cannot run on the machine that needs it is not a verification script. Parameters match
# dev.samstevens.totp's defaults, which is what auth-service verifies against: SHA1, 6 digits, 30s.
totp_now() {
  python3 -c "
import base64, hmac, hashlib, struct, sys, time
secret = sys.argv[1]
key = base64.b32decode(secret + '=' * (-len(secret) % 8), casefold=True)
mac = hmac.new(key, struct.pack('>Q', int(time.time()) // 30), hashlib.sha1).digest()
off = mac[-1] & 0x0F
print(str((struct.unpack('>I', mac[off:off+4])[0] & 0x7FFFFFFF) % 10**6).zfill(6))
" "$1"
}

# One request, status on the first line and body on the rest.
#
# WHY ONE REQUEST RATHER THAN TWO. 13-05 had to fix a harness that fetched the status and the body
# with separate curls; against an endpoint that creates something, those are not the same
# experiment, because the second call provisions a second tenant. Every assertion pair here concerns
# one response.
#
# DELIBERATELY NOT RETRIED on the gateway's SERVICE_UNAVAILABLE fallback, unlike curl_retry.
#
# curl_retry's blind retry is right for a GET and WRONG here, and this script found out the hard
# way. The gateway answers 503 both when a request never reached the backend (cold `lb://` pool)
# AND when the backend is simply taking longer than the route's time limiter — and provisioning is
# a six-step saga across four services, so the second case is real. On the first run of this script
# the 503 was a timeout: the saga was already in flight, it went on to register the auth tenant, and
# the "retry" then provisioned a SECOND tenant that collided with the first one's slug. That is a
# harness manufacturing the very failure it is meant to detect.
#
# So a 503 is reported as the failure it is. The cold-pool case is handled by warming the route
# before the assertion phase instead, which is the honest fix: it removes the ambiguity rather than
# papering over it.
post_json() {
  local url="$1" token="$2" body="$3" idem="${4:-}"
  local args=(-s -w '\n%{http_code}' -X POST "$url" -H "Content-Type: application/json")
  [[ -n "$token" ]] && args+=(-H "Authorization: Bearer ${token}")
  [[ -n "$idem"  ]] && args+=(-H "Idempotency-Key: ${idem}")
  args+=(-d "$body")
  local response
  response="$(curl "${args[@]}")"
  printf '%s\n%s' "$(printf '%s' "$response" | tail -1)" "$(printf '%s' "$response" | sed '$d')"
}

echo "=== Phase 13-10: provisioning through the real API, then logging in (ROADMAP SC2) ==="
echo "gateway=${GATEWAY}"
echo "brand='${BRAND}'  slug=${SLUG}  admin=${ADMIN_EMAIL}"
echo

# ── 0. The SuperAdmin authenticates (13-05's real credential path) ───────────────────────────

SUPER_TOKEN="$(platform_login "$SUPERADMIN_EMAIL" "$SUPERADMIN_PASSWORD")"
if [[ -z "$SUPER_TOKEN" ]]; then
  echo "SETUP FAILED: the SuperAdmin could not log in — this is blocker B1, not B2." >&2
  exit 1
fi
echo "SuperAdmin authenticated."

# Warm the platform route's load-balancer pool with a cheap GET, so the provisioning POST below is
# not the first request through it. See post_json for why this replaces a blind 503 retry rather
# than supplementing one.
curl_status "${GATEWAY}/api/v1/platform/tenants?size=1" -H "Authorization: Bearer ${SUPER_TOKEN}" > /dev/null

set +e   # errexit off for the assertion phase: assert_* return 1, and under -e the first failure
         # would silently skip every assertion after it. The exit code comes from phase13_summary.

# ── 1. Provision ────────────────────────────────────────────────────────────────────────────

PROVISION_BODY="$(json "{\"brandName\":\"${BRAND}\",\"adminEmail\":\"${ADMIN_EMAIL}\",\"tier\":\"GROWTH\"}")"
PROVISION_RESULT="$(post_json "${GATEWAY}/api/v1/platform/tenants" "$SUPER_TOKEN" "$PROVISION_BODY" \
  "e2e-1310-$(date +%s)")"
PROVISION_STATUS="$(printf '%s' "$PROVISION_RESULT" | head -1)"
PROVISION_RESPONSE="$(printf '%s' "$PROVISION_RESULT" | tail -n +2)"

assert_status 201 "$PROVISION_STATUS" "POST /api/v1/platform/tenants provisions a tenant"

TENANT_ID="$(printf '%s' "$PROVISION_RESPONSE"    | json_get "['data']['tenantId']"     2>/dev/null || true)"
TENANT_SLUG="$(printf '%s' "$PROVISION_RESPONSE"  | json_get "['data']['slug']"         2>/dev/null || true)"
RESP_EMAIL="$(printf '%s' "$PROVISION_RESPONSE"   | json_get "['data']['adminEmail']"   2>/dev/null || true)"
TEMP_PASSWORD="$(printf '%s' "$PROVISION_RESPONSE"| json_get "['data']['tempPassword']" 2>/dev/null || true)"

if [[ -z "$TENANT_ID" || "$TENANT_ID" == "None" ]]; then
  echo "FATAL: no tenant id in the provisioning response: ${PROVISION_RESPONSE}" >&2
  phase13_summary
  exit 1
fi
echo "Provisioned tenant ${TENANT_ID} (slug ${TENANT_SLUG})"

# B2 point 1. The presence of a non-empty temporary password IS the assertion: the controller
# previously returned a hardcoded login url in its place and discarded the credential entirely, so
# nobody could ever log in as a provisioned admin.
if [[ -n "$TEMP_PASSWORD" && "$TEMP_PASSWORD" != "None" ]]; then
  echo "PASS: [B2.1] the provisioning response carries a temporary password"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: [B2.1] no temporary password in the provisioning response: ${PROVISION_RESPONSE}"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi
assert_status "$ADMIN_EMAIL" "$RESP_EMAIL" "[B2.1] the response names the admin the credential belongs to"

# ── 2. Refute blocker B2, point by point, against databases that enforce RLS ─────────────────

# B2 point 2 — the platform's own view.
TENANT_VIEW="$(curl_retry "${GATEWAY}/api/v1/platform/tenants/${TENANT_ID}" \
  -H "Authorization: Bearer ${SUPER_TOKEN}")"
assert_contains "$TENANT_VIEW" '"status":"ACTIVE"' "[B2.2] the platform reports the new tenant ACTIVE"

# B2 point 3 — the auth-side tenant row login resolves by slug. Nothing in application code wrote
# one before 13-06; without it the admin has no tenant to log into.
AUTH_TENANT="$(printf '%s\n' \
  "SELECT slug || ':' || status FROM auth_tenants WHERE id = '${TENANT_ID}';" | auth_sql | tail -1)"
assert_status "${TENANT_SLUG}:ACTIVE" "$AUTH_TENANT" "[B2.3] an ACTIVE auth_tenants row exists for the slug"

# B2 point 4 — exactly one branch, flagged headquarters. isHq was never sent, so the "HQ" branch was
# persisted is_hq=false.
BRANCH_ROW="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${TENANT_ID}', false);
  SELECT count(*) || ':' || coalesce(bool_and(is_hq)::text,'none') || ':' || coalesce(bool_and(is_active)::text,'none')
    FROM branches WHERE tenant_id = '${TENANT_ID}' AND deleted_at IS NULL;
" | user_sql | tail -1)"
assert_status "1:true:true" "$BRANCH_ROW" "[B2.4] exactly one live branch, flagged headquarters (RLS-enforcing db)"

BRANCH_ID="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${TENANT_ID}', false);
  SELECT id FROM branches WHERE tenant_id = '${TENANT_ID}' AND deleted_at IS NULL;
" | user_sql | tail -1)"

# B2 point 5 — the event's aggregate id. extractBranchId parsed a shape user-service has never
# produced, so it ALWAYS fell through to UUID.randomUUID(), and that fabricated id became
# event_outbox.branch_id: every consumer downstream correlated against a branch that does not exist.
EVENT_BRANCH="$(printf '%s\n' "
  SELECT branch_id FROM event_outbox
   WHERE tenant_id = '${TENANT_ID}' AND event_type = 'TENANT_PROVISIONED';
" | platform_sql | tail -1)"
assert_status "$BRANCH_ID" "$EVENT_BRANCH" "[B2.5] the provisioning event's aggregate id IS the real branch row"

# B2 point 6 — the assignment without which PermissionResolver refuses the login outright. This is
# the write a superuser-backed test cannot vouch for.
# psql renders a boolean as 't'/'f' in table output but as 'true'/'false' when concatenated with ||,
# which is what happens here.
ASSIGNMENT="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${TENANT_ID}', false);
  SELECT ubr.role_code || ':' || ubr.is_active || ':' || (ubr.branch_id = '${BRANCH_ID}')
    FROM user_branch_roles ubr
    JOIN users u ON u.id = ubr.user_id
   WHERE ubr.tenant_id = '${TENANT_ID}' AND u.email = '${ADMIN_EMAIL}' AND ubr.is_active;
" | auth_sql | tail -1)"
assert_status "OWNER:true:true" "$ASSIGNMENT" "[B2.6] one active OWNER assignment for the admin at that branch"

# B2 point 7 — the chart of accounts.
COA_COUNT="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${TENANT_ID}', false);
  SELECT count(*) FROM chart_of_accounts WHERE tenant_id = '${TENANT_ID}';
" | finance_sql | tail -1)"
if [[ "${COA_COUNT:-0}" -gt 0 ]]; then
  echo "PASS: [B2.7] the chart of accounts was seeded (${COA_COUNT} accounts)"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: [B2.7] no chart of accounts for the new tenant"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi

# T-13-10-A/C: the credential exists in the response and nowhere else. 13-06 left this grep owing.
OUTBOX_PAYLOAD="$(printf '%s\n' "
  SELECT envelope_json FROM event_outbox WHERE tenant_id = '${TENANT_ID}';
" | platform_sql)"
if printf '%s' "$OUTBOX_PAYLOAD" | grep -qF -- "$TEMP_PASSWORD"; then
  echo "FAIL: the temporary password appears in an event payload"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
else
  echo "PASS: the temporary password does not appear in any event payload"
  PHASE13_PASS=$((PHASE13_PASS + 1))
fi
IDEM_ROWS="$(printf '%s\n' "
  SELECT coalesce(string_agg(response_json, ' '), '') FROM idempotency_keys WHERE status = 'COMPLETED';
" | platform_sql)"
if printf '%s' "$IDEM_ROWS" | grep -qF -- "$TEMP_PASSWORD"; then
  echo "FAIL: the temporary password is persisted in platform_db.idempotency_keys"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
else
  echo "PASS: the temporary password is not persisted in platform_db.idempotency_keys"
  PHASE13_PASS=$((PHASE13_PASS + 1))
fi

# ── 3. THE CRITERION: the provisioned admin logs in ─────────────────────────────────────────

# Built straight from python, NOT wrapped in json() — nesting a "$( … )" containing a python dict
# literal inside another "$( … )" lets bash brace-expand the dict before python ever sees it, which
# is how the first run of this script sent a malformed body and reported a confident authentication
# failure for a request that was never valid. Every body below is built the same way, once.
LOGIN_BODY="$(python3 -c "
import json, sys
print(json.dumps({'email': sys.argv[1], 'password': sys.argv[2], 'tenantSlug': sys.argv[3]}))
" "$ADMIN_EMAIL" "$TEMP_PASSWORD" "$TENANT_SLUG")"
LOGIN_RESPONSE="$(curl_retry -X POST "${GATEWAY}/api/v1/auth/login" \
  -H "Content-Type: application/json" -d "$LOGIN_BODY")"

# THE blocker-B2 assertion. Asserted on the distinction, not on a status code: a 401 demanding TOTP
# enrolment and a 403 demanding a password change both mean the branch assignment RESOLVED, because
# both gates run after permissionResolver.resolveDefault.
if printf '%s' "$LOGIN_RESPONSE" | grep -q "no active branch assignments"; then
  echo "FAIL: [B2.8] the provisioned admin has no branch assignment — B2 is NOT closed: ${LOGIN_RESPONSE}"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
else
  echo "PASS: [B2.8] the provisioned admin is NOT refused for want of a branch assignment"
  PHASE13_PASS=$((PHASE13_PASS + 1))
fi
if printf '%s' "$LOGIN_RESPONSE" | grep -qE '"accessToken"|TOTP_ENROLLMENT_REQUIRED|TOTP_REQUIRED|PASSWORD_CHANGE_REQUIRED|MUST_CHANGE_PASSWORD'; then
  echo "PASS: [B2.8] the temporary password from the API response is accepted at the edge"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: [B2.8] generic authentication failure for the provisioned admin: ${LOGIN_RESPONSE}"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi

# 3b. Clear the 13-08 forced-change gate. ORDER MATTERS and 13-15 should copy it: forced change
# first, enrolment second. Enrolling a second factor while the credential is still a temporary
# password known to whoever provisioned the account would bind the factor under a credential the
# admin does not exclusively control.
ADMIN_PASSWORD="$TEMP_PASSWORD"
CHANGE_TOKEN="$(change_token_from "$LOGIN_RESPONSE" || true)"
if [[ -z "$CHANGE_TOKEN" ]]; then
  echo "FAIL: the refused first login carried no change token: ${LOGIN_RESPONSE}"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
else
  FORCED_RESULT="$(forced_change "$CHANGE_TOKEN" "$TEMP_PASSWORD" "$FORCED_NEW_PASSWORD")"
  FORCED_STATUS="$(printf '%s' "$FORCED_RESULT" | head -1)"
  assert_status 200 "$FORCED_STATUS" "the provisioned admin can replace its temporary credential (13-08)"
  [[ "$FORCED_STATUS" == "200" ]] && ADMIN_PASSWORD="$FORCED_NEW_PASSWORD"
fi

# 3c. Complete the D-29a enrolment and obtain a real token.
BOOTSTRAP_BODY="$(python3 -c "
import json, sys
print(json.dumps({'email': sys.argv[1], 'password': sys.argv[2], 'tenantSlug': sys.argv[3]}))
" "$ADMIN_EMAIL" "$ADMIN_PASSWORD" "$TENANT_SLUG")"
BOOTSTRAP_RESPONSE="$(curl_retry -X POST "${GATEWAY}/api/v1/auth/2fa/bootstrap" \
  -H "Content-Type: application/json" -d "$BOOTSTRAP_BODY")"
OTPAUTH_URI="$(printf '%s' "$BOOTSTRAP_RESPONSE" | json_get "['data']['otpauthUri']" 2>/dev/null || true)"

ADMIN_TOKEN=""
if [[ -z "$OTPAUTH_URI" || "$OTPAUTH_URI" == "None" ]]; then
  echo "FAIL: TOTP bootstrap returned no otpauth uri: ${BOOTSTRAP_RESPONSE}"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
else
  TOTP_SECRET="$(printf '%s' "$OTPAUTH_URI" | python3 -c "
import sys, urllib.parse as u
print(u.parse_qs(u.urlparse(sys.stdin.read().strip()).query)['secret'][0])
")"
  VERIFY_BODY="$(python3 -c "
import json, sys
print(json.dumps({'email': sys.argv[1], 'password': sys.argv[2],
                  'tenantSlug': sys.argv[3], 'code': sys.argv[4]}))
" "$ADMIN_EMAIL" "$ADMIN_PASSWORD" "$TENANT_SLUG" "$(totp_now "$TOTP_SECRET")")"
  VERIFY_STATUS="$(curl_status -X POST "${GATEWAY}/api/v1/auth/2fa/bootstrap/verify" \
    -H "Content-Type: application/json" -d "$VERIFY_BODY")"
  assert_status 200 "$VERIFY_STATUS" "the admin can enrol a second factor (D-29a first-login flow)"

  STEPUP_BODY="$(python3 -c "
import json, sys
print(json.dumps({'email': sys.argv[1], 'password': sys.argv[2],
                  'tenantSlug': sys.argv[3], 'totpCode': sys.argv[4]}))
" "$ADMIN_EMAIL" "$ADMIN_PASSWORD" "$TENANT_SLUG" "$(totp_now "$TOTP_SECRET")")"
  STEPUP_RESPONSE="$(curl_retry -X POST "${GATEWAY}/api/v1/auth/login" \
    -H "Content-Type: application/json" -d "$STEPUP_BODY")"
  ADMIN_TOKEN="$(printf '%s' "$STEPUP_RESPONSE" | json_get "['data']['accessToken']" 2>/dev/null || true)"
fi

if [[ -z "$ADMIN_TOKEN" || "$ADMIN_TOKEN" == "None" ]]; then
  echo "FAIL: [SC2] the provisioned admin never obtained an access token"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
else
  echo "PASS: [SC2] the provisioned admin holds a real access token"
  PHASE13_PASS=$((PHASE13_PASS + 1))

  CLAIM_ROLES="$(jwt_claims "$ADMIN_TOKEN" | python3 -c "
import sys, json; print(json.dumps(json.load(sys.stdin).get('roles', [])))
")"
  CLAIM_PERMS="$(jwt_claims "$ADMIN_TOKEN" | python3 -c "
import sys, json; print(len(json.load(sys.stdin).get('permissions', [])))
")"
  CLAIM_TENANT="$(jwt_claims "$ADMIN_TOKEN" | python3 -c "
import sys, json; print(json.load(sys.stdin).get('tenant_id', ''))
")"

  assert_contains "$CLAIM_ROLES" 'OWNER' "the issued token's roles claim names OWNER"
  if [[ "$CLAIM_PERMS" -gt 0 ]]; then
    echo "PASS: the issued token carries a non-empty permissions claim (${CLAIM_PERMS} codes)"
    PHASE13_PASS=$((PHASE13_PASS + 1))
  else
    echo "FAIL: the issued token's permissions claim is EMPTY"
    PHASE13_FAIL=$((PHASE13_FAIL + 1))
  fi
  assert_status "$TENANT_ID" "$CLAIM_TENANT" "the token carries the new tenant's id"

  # An ordinary tenant-scoped endpoint. Deliberately NOT /api/v1/users/me: that is not a route, it
  # matches /api/v1/users/{userId} and 400s parsing "me" as a UUID — a 400 satisfies "not 403" while
  # proving nothing about authorization, which is the shape of assertion this phase exists to stop
  # trusting.
  BRANCHES_STATUS="$(curl_status "${GATEWAY}/api/v1/branches" -H "Authorization: Bearer ${ADMIN_TOKEN}")"
  assert_authorized "$BRANCHES_STATUS" "[SC2] the admin's token reaches a tenant-scoped endpoint"
  assert_status 200 "$BRANCHES_STATUS" "[SC2] ...and that endpoint answers 200"
fi

# ── 4. The negative: a mid-saga failure leaves nothing orphaned ──────────────────────────────

# Pre-claim the slug in auth_db under a tenant that exists nowhere else, so registerTenant answers
# 409 STATE_INVALID. The failure lands AFTER the branch was created and BEFORE any user exists,
# which is exactly the ordering the saga was built for.
printf '%s\n' "
  INSERT INTO auth_tenants (id, slug, name, status, created_at, updated_at)
  VALUES ('${COLLIDE_HOLDER_ID}', '${COLLIDE_SLUG}', 'Slug Holder', 'ACTIVE', now(), now())
  ON CONFLICT (id) DO NOTHING;
" | auth_sql > /dev/null

COLLIDE_BODY="$(json "{\"brandName\":\"${COLLIDE_BRAND}\",\"adminEmail\":\"${COLLIDE_EMAIL}\",\"tier\":\"STARTER\"}")"
COLLIDE_RESULT="$(post_json "${GATEWAY}/api/v1/platform/tenants" "$SUPER_TOKEN" "$COLLIDE_BODY" \
  "e2e-1310-collide-$(date +%s)")"
COLLIDE_STATUS="$(printf '%s' "$COLLIDE_RESULT" | head -1)"

case "$COLLIDE_STATUS" in
  2??) echo "FAIL: [B2.9] a slug-colliding provision reported SUCCESS (${COLLIDE_STATUS})"
       PHASE13_FAIL=$((PHASE13_FAIL + 1)) ;;
  *)   echo "PASS: [B2.9] a slug-colliding provision fails (${COLLIDE_STATUS})"
       PHASE13_PASS=$((PHASE13_PASS + 1)) ;;
esac

COLLIDE_TENANT_ID="$(printf '%s\n' \
  "SELECT id FROM tenants WHERE brand_name = '${COLLIDE_BRAND}';" | platform_sql | tail -1)"
COLLIDE_TENANT_STATUS="$(printf '%s\n' \
  "SELECT status FROM tenants WHERE brand_name = '${COLLIDE_BRAND}';" | platform_sql | tail -1)"
assert_status "PROVISIONING_FAILED" "$COLLIDE_TENANT_STATUS" \
  "[B2.9] the failed tenant is marked PROVISIONING_FAILED"

# Compensation, observed rather than reasoned about: the branch the saga created before it failed
# must be gone. Before this plan this was a log.warn saying manual cleanup was needed.
ORPHAN_BRANCHES="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${COLLIDE_TENANT_ID}', false);
  SELECT count(*) FROM branches
   WHERE tenant_id = '${COLLIDE_TENANT_ID}' AND deleted_at IS NULL AND is_active;
" | user_sql | tail -1)"
assert_status 0 "$ORPHAN_BRANCHES" "[B2.9] the failed provision left no orphaned active branch"

# The branch row IS still there, soft-deleted — compensation is a deactivation, not a hard delete,
# because a branch may already have referents. Asserting this stops a future hard delete slipping in.
DEAD_BRANCHES="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${COLLIDE_TENANT_ID}', false);
  SELECT count(*) FROM branches WHERE tenant_id = '${COLLIDE_TENANT_ID}' AND deleted_at IS NOT NULL;
" | user_sql | tail -1)"
assert_status 1 "$DEAD_BRANCHES" "[B2.9] ...it was soft-deactivated, not hard-deleted"

ORPHAN_USERS="$(printf '%s\n' "
  SELECT set_config('app.current_tenant_id', '${COLLIDE_TENANT_ID}', false);
  SELECT count(*) FROM users WHERE email = '${COLLIDE_EMAIL}';
" | auth_sql | tail -1)"
if [[ "${ORPHAN_USERS:-0}" == "0" ]]; then
  echo "PASS: [B2.9] the failed provision left no orphaned admin user"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: [B2.9] the failed provision left ${ORPHAN_USERS} orphaned admin user(s)"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi

# And the same conclusion the way a user reaches it.
COLLIDE_LOGIN_BODY="$(json "{\"email\":\"${COLLIDE_EMAIL}\",\"password\":\"whatever\",\"tenantSlug\":\"${COLLIDE_SLUG}\"}")"
COLLIDE_LOGIN_STATUS="$(curl_status -X POST "${GATEWAY}/api/v1/auth/login" \
  -H "Content-Type: application/json" -d "$COLLIDE_LOGIN_BODY")"
assert_status 401 "$COLLIDE_LOGIN_STATUS" "[B2.9] no login exists for the failed tenant's admin"

echo
phase13_summary
