#!/usr/bin/env bash
# Phase 13-12 — ROADMAP SC3, proved live: a tenant administers its own staff through a public API.
#
# SC3: "a tenant admin can create, list, edit and deactivate users through a public API, and assign
# per-branch roles from a catalog, with an unknown code rejected with 400." Blocker B3 said none of
# that existed. 13-11 built the internal half; this script proves the public half over real HTTP
# through the real gateway, which is the only kind of proof this phase accepts (D-30) — the audit
# found Phase 3 scored 24/24 by grepping source while its controller did not exist.
#
# WHY TWO TENANTS ARE PROVISIONED RATHER THAN ONE FABRICATED
#
# A cross-tenant assertion against a made-up UUID proves only that a random id is not found, which
# is true of any API and of a completely broken one. Both tenants here are provisioned through the
# real platform API, both have a real admin who has really logged in, and every isolation assertion
# is paired with a CONTROL showing the same request succeeds for the tenant that owns the row. That
# matters more than usual here: users is FORCE ROW LEVEL SECURITY and auth_user is NOSUPERUSER
# NOBYPASSRLS, but Testcontainers' Postgres user is a SUPERUSER, so the policy is INERT in every
# integration test in this repository. This script runs against the enforcing database, and it is
# the only place the policy is actually exercised.
#
# THE CEILING IS TESTED BY A TENANT_ADMIN, NOT BY THE PROVISIONED OWNER
#
# provisionAdmin makes an OWNER, and OWNER holds rbac.manage, so OWNER granting OWNER is legitimate
# and refusing it would be the bug. The escalation 13-02's authority split exists to prevent is a
# TENANT_ADMIN minting an OWNER, so this script creates a real TENANT_ADMIN — through the API under
# test — brings it fully online, and has IT attempt the escalation.
#
# Prerequisites: the full dev stack, with gateway, auth-service, user-service and
# platform-admin-service all running jars built at or after 13-12.
#
# Usage: bash scripts/e2e/phase13-tenant-admin-users-e2e.sh

set -uo pipefail

. scripts/e2e/_phase13-lib.sh

SUPERADMIN_EMAIL="${SUPERADMIN_EMAIL:-superadmin@softxlogic.com}"
SUPERADMIN_PASSWORD="${SUPERADMIN_PASSWORD:-Test@123!}"

# ── Throwaway identities ────────────────────────────────────────────────────────────────────
#
# The tenant ids are generated by platform_db and cannot be pinned. The BRANDS are pinned instead,
# and ProvisioningService.slugify is deterministic on them, so a re-run addresses the same rows
# rather than littering the database with a tenant per run. Cleanup resolves ids from the slugs.

BRAND_A="Phase13 TenantAdmin Users A"
SLUG_A="phase13-tenantadmin-users-a"
OWNER_A_EMAIL="owner@${SLUG_A}.local"

BRAND_B="Phase13 TenantAdmin Users B"
SLUG_B="phase13-tenantadmin-users-b"
OWNER_B_EMAIL="owner@${SLUG_B}.local"

CASHIER_EMAIL="cashier@${SLUG_A}.local"
TADMIN_EMAIL="tadmin@${SLUG_A}.local"

OWNER_NEW_PASSWORD='TAdmU#Owner1x'
CASHIER_NEW_PASSWORD='TAdmU#Cash1x'
TADMIN_NEW_PASSWORD='TAdmU#Admin1x'

# ── Database access (cleanup only — no assertion reads a table) ─────────────────────────────
#
# Every role here is NOSUPERUSER NOBYPASSRLS and the tables are FORCE RLS, so the GUC lines are not
# ceremony: without them these DELETEs report success while deleting nothing.

auth_sql()     { docker exec -i restaurantos-postgres psql -U auth_user      -d auth_db     -v ON_ERROR_STOP=1 -qtA; }
user_sql()     { docker exec -i restaurantos-postgres psql -U user_service   -d user_db     -v ON_ERROR_STOP=1 -qtA; }
platform_sql() { docker exec -i restaurantos-postgres psql -U platform_admin -d platform_db -v ON_ERROR_STOP=1 -qtA; }
finance_sql()  { docker exec -i restaurantos-postgres psql -U finance_user   -d finance_db  -v ON_ERROR_STOP=1 -qtA; }

purge_everything() {
  local tenant_ids tid
  tenant_ids="$(printf '%s\n' \
    "SELECT id FROM tenants WHERE slug IN ('${SLUG_A}','${SLUG_B}')
       OR brand_name IN ('${BRAND_A}','${BRAND_B}');" | platform_sql 2>/dev/null || true)"

  for tid in $tenant_ids; do
    printf '%s\n' "
      SELECT set_config('app.current_tenant_id', '${tid}', false);
      DELETE FROM refresh_sessions WHERE tenant_id = '${tid}';
      DELETE FROM user_branch_roles WHERE tenant_id = '${tid}';
      DELETE FROM password_reset_tokens WHERE tenant_id = '${tid}';
      DELETE FROM password_history WHERE user_id IN (SELECT id FROM users WHERE tenant_id = '${tid}');
      DELETE FROM users WHERE tenant_id = '${tid}';
      DELETE FROM auth_tenants WHERE id = '${tid}';
    " | auth_sql > /dev/null 2>&1 || true
    printf '%s\n' "
      SELECT set_config('app.current_tenant_id', '${tid}', false);
      DELETE FROM branches WHERE tenant_id = '${tid}';
    " | user_sql > /dev/null 2>&1 || true
    printf '%s\n' "
      SELECT set_config('app.current_tenant_id', '${tid}', false);
      DELETE FROM accounting_periods WHERE tenant_id = '${tid}';
      DELETE FROM chart_of_accounts WHERE tenant_id = '${tid}';
    " | finance_sql > /dev/null 2>&1 || true
    printf '%s\n' "
      DELETE FROM event_outbox WHERE tenant_id = '${tid}';
      DELETE FROM tenant_features WHERE tenant_id = '${tid}';
      DELETE FROM usage_records WHERE tenant_id = '${tid}';
      DELETE FROM tenants WHERE id = '${tid}';
    " | platform_sql > /dev/null 2>&1 || true
  done

  printf '%s\n' "DELETE FROM auth_tenants WHERE slug IN ('${SLUG_A}','${SLUG_B}');" \
    | auth_sql > /dev/null 2>&1 || true
}

cleanup() {
  local code=$?
  set +e
  purge_everything
  local left
  left="$(printf '%s\n' \
    "SELECT count(*) FROM tenants WHERE slug IN ('${SLUG_A}','${SLUG_B}');" \
    | platform_sql 2>/dev/null | tail -1 || echo '?')"
  echo "Cleaned up both provisioned tenants ('${SLUG_A}', '${SLUG_B}'); rows left: ${left}"
  exit $code
}
trap cleanup EXIT

# A previous run killed between steps would otherwise leave rows that turn "slug already exists"
# into what looks like a defect in the code under test.
purge_everything

# ── Helpers ─────────────────────────────────────────────────────────────────────────────────

# Bodies are ALWAYS built from python argv, never as an inline literal: bash brace-expands
# -d "{\"a\":1,\"b\":2}" into two malformed fragments and runs curl twice (13-02), and re-parses
# escaped quotes away inside "$( … )" (13-07). Both produced confident failures for requests that
# were never valid.
#   jbody email x@y.local roleCode CASHIER
# The literal __null__ emits a JSON null; __raw__ prefixes are emitted unquoted (for booleans).
jbody() {
  python3 -c "
import json, sys
a = sys.argv[1:]
d = {}
for i in range(0, len(a), 2):
    k, v = a[i], a[i + 1]
    if v == '__null__':
        d[k] = None
    elif v in ('true', 'false'):
        d[k] = (v == 'true')
    else:
        d[k] = v
print(json.dumps(d))
" "$@"
}

# One request; status on the FIRST line, body on the rest.
#
# WHY ONE REQUEST RATHER THAN TWO. 13-05 had to fix a harness that fetched the status and the body
# with separate curls. Against anything that creates, deactivates or redeems, those are not the
# same experiment — the second call acts on the state the first one produced. Every assertion pair
# here concerns one response.
#
# DELIBERATELY NOT RETRIED on the gateway's SERVICE_UNAVAILABLE fallback. A blind retry is right for
# a GET and wrong for a POST: 13-10 found its retry had provisioned a second tenant that then
# collided with the first. The cold-pool case is handled by warming each route before the assertion
# phase instead, which removes the ambiguity rather than papering over it.
req() {
  local method="$1" url="$2" token="${3:-}" body="${4:-}"
  local args=(-s -w '\n%{http_code}' -X "$method" "$url")
  [[ -n "$token" ]] && args+=(-H "Authorization: Bearer ${token}")
  [[ -n "$body"  ]] && args+=(-H "Content-Type: application/json" -d "$body")
  local response
  response="$(curl "${args[@]}")"
  printf '%s\n%s' "$(printf '%s' "$response" | tail -1)" "$(printf '%s' "$response" | sed '$d')"
}
status_of() { printf '%s' "$1" | head -1; }
body_of()   { printf '%s' "$1" | tail -n +2; }

# TOTP in pure stdlib. pyotp is not installed on this machine's python3 and the phase threat
# register forbids installing a package to make a verification script run. Parameters match
# dev.samstevens.totp's defaults, which is what auth-service verifies against: SHA1, 6 digits, 30s.
totp_now() {
  python3 -c "
import base64, hmac, hashlib, struct, sys, time
secret = sys.argv[1]
key = base64.b32decode(secret + '=' * (-len(secret) % 8), casefold=True)
mac = hmac.new(key, struct.pack('>Q', int(time.time()) // 30), hashlib.sha1).digest()
off = mac[-1] & 0x0F
print(str((struct.unpack('>I', mac[off:off+4])[0] & 0x7FFFFFFF) % 10**6).zfill(6))
" "$1"
}

# Provision a tenant through the real platform API. Sets PROV_TENANT_ID / PROV_SLUG / PROV_TEMP.
provision_tenant() {
  local brand="$1" admin_email="$2" body result status response
  body="$(jbody brandName "$brand" adminEmail "$admin_email" tier GROWTH)"
  result="$(req POST "${GATEWAY}/api/v1/platform/tenants" "$SUPER_TOKEN" "$body")"
  status="$(status_of "$result")"
  response="$(body_of "$result")"
  if [[ "$status" != "201" ]]; then
    echo "SETUP FAILED: provisioning '${brand}' returned ${status}: ${response}" >&2
    return 1
  fi
  PROV_TENANT_ID="$(printf '%s' "$response" | json_get "['data']['tenantId']")"
  PROV_SLUG="$(printf '%s' "$response"      | json_get "['data']['slug']")"
  PROV_TEMP="$(printf '%s' "$response"      | json_get "['data']['tempPassword']")"
  [[ -n "$PROV_TENANT_ID" && "$PROV_TENANT_ID" != "None" ]]
}

# Clear the forced-change gate (13-08) for a user whose current credential is a temporary password.
# Prints nothing; returns non-zero if the change did not take.
clear_forced_change() {
  local email="$1" temp="$2" slug="$3" new_password="$4" login_body refusal change_token result
  login_body="$(jbody email "$email" password "$temp" tenantSlug "$slug")"
  refusal="$(curl_retry -X POST "${GATEWAY}/api/v1/auth/login" \
    -H "Content-Type: application/json" -d "$login_body")"
  change_token="$(change_token_from "$refusal" || true)"
  if [[ -z "$change_token" ]]; then
    echo "clear_forced_change: no change token for ${email}: ${refusal}" >&2
    return 1
  fi
  result="$(forced_change "$change_token" "$temp" "$new_password")"
  [[ "$(status_of "$result")" == "200" ]]
}

# Enrol a second factor and return a stepped-up access token. Required for any role holding
# finance.period.close or hr.payroll.approve — which TENANT_ADMIN and OWNER both do (D-29a).
#
# ORDER MATTERS and it is the order 13-10 established: forced change FIRST, enrolment second.
# Binding a factor while the credential is still a temporary password known to whoever provisioned
# the account would bind it under a credential the human does not exclusively control.
enrol_and_login() {
  local email="$1" password="$2" slug="$3" bootstrap uri secret verify_body login_body response
  bootstrap="$(jbody email "$email" password "$password" tenantSlug "$slug")"
  response="$(curl_retry -X POST "${GATEWAY}/api/v1/auth/2fa/bootstrap" \
    -H "Content-Type: application/json" -d "$bootstrap")"
  uri="$(printf '%s' "$response" | json_get "['data']['otpauthUri']" 2>/dev/null || true)"
  if [[ -z "$uri" || "$uri" == "None" ]]; then
    echo "enrol_and_login: no otpauth uri for ${email}: ${response}" >&2
    return 1
  fi
  secret="$(printf '%s' "$uri" | python3 -c "
import sys, urllib.parse as u
print(u.parse_qs(u.urlparse(sys.stdin.read().strip()).query)['secret'][0])
")"
  verify_body="$(jbody email "$email" password "$password" tenantSlug "$slug" code "$(totp_now "$secret")")"
  curl_status -X POST "${GATEWAY}/api/v1/auth/2fa/bootstrap/verify" \
    -H "Content-Type: application/json" -d "$verify_body" > /dev/null
  login_body="$(jbody email "$email" password "$password" tenantSlug "$slug" totpCode "$(totp_now "$secret")")"
  response="$(curl_retry -X POST "${GATEWAY}/api/v1/auth/login" \
    -H "Content-Type: application/json" -d "$login_body")"
  printf '%s' "$response" | json_get "['data']['accessToken']"
}

# The roles claim of a token, as a sorted JSON array.
roles_claim() {
  jwt_claims "$1" | python3 -c "
import sys, json; print(json.dumps(sorted(json.load(sys.stdin).get('roles', []))))
"
}

echo "=== Phase 13-12: the public tenant-admin user API, over live HTTP (ROADMAP SC3) ==="
echo "gateway=${GATEWAY}"
echo "tenant A='${BRAND_A}'   tenant B='${BRAND_B}'"
echo

# ── 0. Setup: two real tenants, two real owners ─────────────────────────────────────────────

SUPER_TOKEN="$(platform_login "$SUPERADMIN_EMAIL" "$SUPERADMIN_PASSWORD")"
if [[ -z "$SUPER_TOKEN" ]]; then
  echo "SETUP FAILED: the SuperAdmin could not log in — that is blocker B1, not B3." >&2
  exit 1
fi
echo "SuperAdmin authenticated."

# Warm each route's load-balancer pool with a cheap GET, so no assertion below is the first request
# through it. See req() for why this replaces a blind 503 retry rather than supplementing one.
curl_status "${GATEWAY}/api/v1/platform/tenants?size=1" -H "Authorization: Bearer ${SUPER_TOKEN}" > /dev/null

provision_tenant "$BRAND_A" "$OWNER_A_EMAIL" || exit 1
TENANT_A_ID="$PROV_TENANT_ID"; SLUG_A_REAL="$PROV_SLUG"; OWNER_A_TEMP="$PROV_TEMP"
provision_tenant "$BRAND_B" "$OWNER_B_EMAIL" || exit 1
TENANT_B_ID="$PROV_TENANT_ID"; SLUG_B_REAL="$PROV_SLUG"; OWNER_B_TEMP="$PROV_TEMP"
echo "Provisioned tenant A=${TENANT_A_ID} (${SLUG_A_REAL}) and tenant B=${TENANT_B_ID} (${SLUG_B_REAL})"

clear_forced_change "$OWNER_A_EMAIL" "$OWNER_A_TEMP" "$SLUG_A_REAL" "$OWNER_NEW_PASSWORD" \
  || { echo "SETUP FAILED: tenant A's owner could not replace its temporary password" >&2; exit 1; }
clear_forced_change "$OWNER_B_EMAIL" "$OWNER_B_TEMP" "$SLUG_B_REAL" "$OWNER_NEW_PASSWORD" \
  || { echo "SETUP FAILED: tenant B's owner could not replace its temporary password" >&2; exit 1; }

OWNER_A_TOKEN="$(enrol_and_login "$OWNER_A_EMAIL" "$OWNER_NEW_PASSWORD" "$SLUG_A_REAL")" || true
OWNER_B_TOKEN="$(enrol_and_login "$OWNER_B_EMAIL" "$OWNER_NEW_PASSWORD" "$SLUG_B_REAL")" || true
if [[ -z "${OWNER_A_TOKEN:-}" || -z "${OWNER_B_TOKEN:-}" || "$OWNER_A_TOKEN" == "None" ]]; then
  echo "SETUP FAILED: an owner never obtained an access token" >&2
  exit 1
fi
echo "Both owners are online and hold real access tokens."

# The HQ branch, read through the public API rather than out of the database — a branch id this
# script invented would not be one the tenant actually has.
BRANCHES_A="$(curl_retry "${GATEWAY}/api/v1/branches" -H "Authorization: Bearer ${OWNER_A_TOKEN}")"
BRANCH_A_ID="$(printf '%s' "$BRANCHES_A" | python3 -c "
import sys, json
d = json.load(sys.stdin)['data']
rows = d if isinstance(d, list) else d.get('content', [])
print(next((r['id'] for r in rows if r.get('isHq') or r.get('hq')), rows[0]['id'] if rows else ''))
" 2>/dev/null || true)"
if [[ -z "$BRANCH_A_ID" ]]; then
  echo "SETUP FAILED: tenant A has no branch to assign roles at: ${BRANCHES_A}" >&2
  exit 1
fi
echo "Tenant A headquarters branch = ${BRANCH_A_ID}"
echo

set +e   # errexit off for the assertion phase: assert_* return 1, and under -e the first failure
         # would silently skip every assertion after it. The exit code comes from phase13_summary.

# ── 1. The SC3 chain: catalog → create → forced change → login ──────────────────────────────

echo "--- the flow a real administrator walks ---"

ROLES_RESULT="$(req GET "${GATEWAY}/api/v1/roles" "$OWNER_A_TOKEN")"
assert_status 200 "$(status_of "$ROLES_RESULT")" "the tenant admin can read the role catalog (13-07)"
ROLE_CODES="$(body_of "$ROLES_RESULT" | python3 -c "
import sys, json
print('\n'.join(sorted(r['code'] for r in json.load(sys.stdin)['data'])))
" 2>/dev/null || true)"
assert_contains "$ROLE_CODES" 'CASHIER' "the catalog offers the cashier role the flow below picks"

# The create body deliberately carries a tenantId, a userId and a branchId belonging to TENANT B.
# None of them may have any effect: the tenant comes from the verified JWT and nowhere else.
CREATE_BODY="$(jbody email "$CASHIER_EMAIL" fullName "E2E Cashier" locale en \
                     branchId "$BRANCH_A_ID" roleCode CASHIER tenantId "$TENANT_B_ID")"
CREATE_RESULT="$(req POST "${GATEWAY}/api/v1/users" "$OWNER_A_TOKEN" "$CREATE_BODY")"
assert_status 201 "$(status_of "$CREATE_RESULT")" "POST /api/v1/users creates a user"
CREATE_BODY_OUT="$(body_of "$CREATE_RESULT")"
CASHIER_ID="$(printf '%s' "$CREATE_BODY_OUT"   | json_get "['data']['id']" 2>/dev/null || true)"
CASHIER_TEMP="$(printf '%s' "$CREATE_BODY_OUT" | json_get "['data']['tempPassword']" 2>/dev/null || true)"

if [[ -n "$CASHIER_TEMP" && "$CASHIER_TEMP" != "None" ]]; then
  echo "PASS: the create response carries the one-time temporary password"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: no temporary password in the create response: ${CREATE_BODY_OUT}"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi
assert_contains "$CREATE_BODY_OUT" '"loginable":true' \
  "the response says the new account can actually be used (an unassigned account cannot)"

if [[ -z "$CASHIER_ID" || "$CASHIER_ID" == "None" ]]; then
  echo "FATAL: no user id in the create response; the rest of the flow cannot run." >&2
  phase13_summary
  exit 1
fi

# The forced-change gate, then a real login. THIS is SC3's criterion: a user a tenant created
# through the public API can log in and use the product.
if clear_forced_change "$CASHIER_EMAIL" "$CASHIER_TEMP" "$SLUG_A_REAL" "$CASHIER_NEW_PASSWORD"; then
  echo "PASS: the created user can replace its temporary credential (13-08)"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: the created user could not clear the forced-change gate"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi

CASHIER_TOKEN="$(tenant_login "$CASHIER_EMAIL" "$CASHIER_NEW_PASSWORD" "$SLUG_A_REAL" 2>/dev/null || true)"
if [[ -n "$CASHIER_TOKEN" && "$CASHIER_TOKEN" != "None" ]]; then
  echo "PASS: [SC3] the created user logs in and holds a real access token"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: [SC3] the created user could not log in"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi

if [[ -n "$CASHIER_TOKEN" ]]; then
  assert_status '["CASHIER"]' "$(roles_claim "$CASHIER_TOKEN")" \
    "the token carries exactly the role that was assigned at creation"
  CASHIER_PERM_COUNT="$(jwt_claims "$CASHIER_TOKEN" | python3 -c "
import sys, json; print(len(json.load(sys.stdin).get('permissions', [])))
")"
  if [[ "${CASHIER_PERM_COUNT:-0}" -gt 0 ]]; then
    echo "PASS: the token carries a non-empty permission set (${CASHIER_PERM_COUNT} codes)"
    PHASE13_PASS=$((PHASE13_PASS + 1))
  else
    echo "FAIL: the created user's token carries NO permissions — a permissionless login is what"
    echo "      an unvalidated role code used to produce (B3, D-13)"
    PHASE13_FAIL=$((PHASE13_FAIL + 1))
  fi
  CLAIM_TENANT="$(jwt_claims "$CASHIER_TOKEN" | python3 -c "
import sys, json; print(json.load(sys.stdin).get('tenant_id', ''))
")"
  assert_status "$TENANT_A_ID" "$CLAIM_TENANT" \
    "the user landed in the CALLER's tenant, not the one named in the request body"
fi
echo

# ── 2. List, update, re-read ────────────────────────────────────────────────────────────────

echo "--- list, update, re-read ---"

LIST_RESULT="$(req GET "${GATEWAY}/api/v1/users?page=0&size=50" "$OWNER_A_TOKEN")"
assert_status 200 "$(status_of "$LIST_RESULT")" "GET /api/v1/users lists this tenant's users"
LIST_BODY="$(body_of "$LIST_RESULT")"
assert_contains "$LIST_BODY" "$CASHIER_EMAIL" "the newly created user appears in the list"
assert_contains "$LIST_BODY" "$OWNER_A_EMAIL" "the tenant's own admin appears in the list"
assert_contains "$LIST_BODY" '"totalCount"' "the list carries page metadata"

UPDATE_RESULT="$(req PATCH "${GATEWAY}/api/v1/users/${CASHIER_ID}" "$OWNER_A_TOKEN" \
  "$(jbody fullName "Renamed Cashier")")"
assert_status 200 "$(status_of "$UPDATE_RESULT")" "PATCH /api/v1/users/{id} updates a profile"

GET_RESULT="$(req GET "${GATEWAY}/api/v1/users/${CASHIER_ID}" "$OWNER_A_TOKEN")"
assert_status 200 "$(status_of "$GET_RESULT")" "GET /api/v1/users/{id} fetches one user"
assert_contains "$(body_of "$GET_RESULT")" 'Renamed Cashier' \
  "the change is reflected on a SUBSEQUENT fetch, not merely echoed by the write"
assert_contains "$(body_of "$GET_RESULT")" '"assignments"' \
  "the fetch reports the assignments that decide what the account can do"

# A password field is refused, not dropped: an administrator must never come away believing they
# set a password the platform has never heard of.
PWD_RESULT="$(req PATCH "${GATEWAY}/api/v1/users/${CASHIER_ID}" "$OWNER_A_TOKEN" \
  "$(jbody fullName "Renamed Cashier" password "SneakySet#1")")"
assert_status 400 "$(status_of "$PWD_RESULT")" "a profile patch carrying a password is REFUSED, not ignored"
if printf '%s' "$(body_of "$PWD_RESULT")" | grep -q 'SneakySet#1'; then
  echo "FAIL: the refusal echoed the submitted password back to the caller"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
else
  echo "PASS: the refusal names the field and never echoes the credential"
  PHASE13_PASS=$((PHASE13_PASS + 1))
fi
echo

# ── 3. Role replacement and the unknown code ────────────────────────────────────────────────

echo "--- per-branch role assignment ---"

ASSIGN_RESULT="$(req POST "${GATEWAY}/api/v1/users/${CASHIER_ID}/branch-roles" "$OWNER_A_TOKEN" \
  "$(jbody branchId "$BRANCH_A_ID" roleCode WAITER)")"
assert_status 200 "$(status_of "$ASSIGN_RESULT")" "a different role can be assigned at the same branch"
assert_contains "$(body_of "$ASSIGN_RESULT")" '"displacedRoleCode":"CASHIER"' \
  "the response reports the role it displaced (13-02's one-active-role-per-branch)"

REPLACED_TOKEN="$(tenant_login "$CASHIER_EMAIL" "$CASHIER_NEW_PASSWORD" "$SLUG_A_REAL" 2>/dev/null || true)"
if [[ -n "$REPLACED_TOKEN" && "$REPLACED_TOKEN" != "None" ]]; then
  assert_status '["WAITER"]' "$(roles_claim "$REPLACED_TOKEN")" \
    "a FRESH login shows exactly one role — the replacement, not both"
else
  echo "FAIL: the user could not log in after the role replacement"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi

UNKNOWN_RESULT="$(req POST "${GATEWAY}/api/v1/users/${CASHIER_ID}/branch-roles" "$OWNER_A_TOKEN" \
  "$(jbody branchId "$BRANCH_A_ID" roleCode NOT_A_REAL_ROLE)")"
assert_status 400 "$(status_of "$UNKNOWN_RESULT")" \
  "a role code absent from the catalog is 400 at the PUBLIC door (13-07 finding #2)"
assert_contains "$(body_of "$UNKNOWN_RESULT")" 'UNKNOWN_ROLE_CODE' \
  "the refusal names why, rather than arriving as an opaque server error"

UNKNOWN_CREATE="$(req POST "${GATEWAY}/api/v1/users" "$OWNER_A_TOKEN" \
  "$(jbody email "unknownrole@${SLUG_A}.local" branchId "$BRANCH_A_ID" roleCode NOT_A_REAL_ROLE)")"
assert_status 400 "$(status_of "$UNKNOWN_CREATE")" "an unknown role code on CREATE is 400 too"
echo

# ── 4. Deactivation actually takes effect ───────────────────────────────────────────────────

echo "--- deactivate / reactivate ---"

# The control first: the account works right now. Without it, "the login is refused" is satisfied by
# a password this script got wrong.
PRE_TOKEN="$(tenant_login "$CASHIER_EMAIL" "$CASHIER_NEW_PASSWORD" "$SLUG_A_REAL" 2>/dev/null || true)"
if [[ -n "$PRE_TOKEN" && "$PRE_TOKEN" != "None" ]]; then
  echo "PASS: [control] the account can log in immediately before deactivation"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: [control] the account could not log in before deactivation — the assertion below"
  echo "      would then pass for the wrong reason"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi

DEACT_RESULT="$(req POST "${GATEWAY}/api/v1/users/${CASHIER_ID}/deactivate" "$OWNER_A_TOKEN")"
assert_status 200 "$(status_of "$DEACT_RESULT")" "POST /api/v1/users/{id}/deactivate succeeds"
assert_contains "$(body_of "$DEACT_RESULT")" '"active":false' \
  "the response returns the updated resource with the flag off"

DEAD_LOGIN="$(tenant_login "$CASHIER_EMAIL" "$CASHIER_NEW_PASSWORD" "$SLUG_A_REAL" 2>/dev/null || true)"
if [[ -z "$DEAD_LOGIN" || "$DEAD_LOGIN" == "None" ]]; then
  echo "PASS: a deactivated user is REFUSED at login (13-11 found login had never read is_active)"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: a deactivated user still logged in — deactivation does not take effect"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi

REACT_RESULT="$(req POST "${GATEWAY}/api/v1/users/${CASHIER_ID}/reactivate" "$OWNER_A_TOKEN")"
assert_status 200 "$(status_of "$REACT_RESULT")" "POST /api/v1/users/{id}/reactivate succeeds"
BACK_TOKEN="$(tenant_login "$CASHIER_EMAIL" "$CASHIER_NEW_PASSWORD" "$SLUG_A_REAL" 2>/dev/null || true)"
if [[ -n "$BACK_TOKEN" && "$BACK_TOKEN" != "None" ]]; then
  echo "PASS: reactivation restores access, with the role the account already held"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: a reactivated user still cannot log in"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi
echo

# ── 5. The tenant boundary, against two genuinely provisioned tenants ───────────────────────

echo "--- tenant isolation (two real tenants, every assertion with a control) ---"

# Tenant B's admin id, read through tenant B's OWN token. This is the control that makes every
# assertion below meaningful: the row exists, and it is returned to the tenant that owns it.
LIST_B="$(req GET "${GATEWAY}/api/v1/users?size=50" "$OWNER_B_TOKEN")"
assert_status 200 "$(status_of "$LIST_B")" "[control] tenant B's admin can list tenant B's users"
OWNER_B_ID="$(body_of "$LIST_B" | python3 -c "
import sys, json
print(next((u['id'] for u in json.load(sys.stdin)['data'] if u['email'] == '${OWNER_B_EMAIL}'), ''))
" 2>/dev/null || true)"
if [[ -n "$OWNER_B_ID" ]]; then
  echo "PASS: [control] tenant B's admin row exists and is visible to tenant B (${OWNER_B_ID})"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: [control] could not find tenant B's admin in tenant B's own list: $(body_of "$LIST_B")"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi

if [[ -n "$OWNER_B_ID" ]]; then
  # Every verb, not just list. A boundary asserted on one verb is a boundary asserted on one verb.
  X_GET="$(req GET "${GATEWAY}/api/v1/users/${OWNER_B_ID}" "$OWNER_A_TOKEN")"
  assert_status 404 "$(status_of "$X_GET")" "tenant A cannot FETCH tenant B's admin (404, not 403)"
  if printf '%s' "$(body_of "$X_GET")" | grep -qE "${OWNER_B_EMAIL}|${TENANT_B_ID}"; then
    echo "FAIL: the not-found body leaked the other tenant's address or id"
    PHASE13_FAIL=$((PHASE13_FAIL + 1))
  else
    echo "PASS: the not-found body names neither the other tenant's address nor its id"
    PHASE13_PASS=$((PHASE13_PASS + 1))
  fi

  assert_status 404 "$(status_of "$(req POST "${GATEWAY}/api/v1/users/${OWNER_B_ID}/deactivate" "$OWNER_A_TOKEN")")" \
    "tenant A cannot DEACTIVATE tenant B's admin"
  assert_status 404 "$(status_of "$(req POST "${GATEWAY}/api/v1/users/${OWNER_B_ID}/reactivate" "$OWNER_A_TOKEN")")" \
    "tenant A cannot REACTIVATE tenant B's admin"
  assert_status 404 "$(status_of "$(req PATCH "${GATEWAY}/api/v1/users/${OWNER_B_ID}" "$OWNER_A_TOKEN" \
    "$(jbody fullName "Hijacked")")")" \
    "tenant A cannot UPDATE tenant B's admin"
  assert_status 404 "$(status_of "$(req POST "${GATEWAY}/api/v1/users/${OWNER_B_ID}/branch-roles" "$OWNER_A_TOKEN" \
    "$(jbody branchId "$BRANCH_A_ID" roleCode CASHIER)")")" \
    "tenant A cannot ASSIGN A ROLE to tenant B's admin"

  # The control that tenant B's admin is still there and untouched by the five attempts above.
  assert_status 200 "$(status_of "$(req GET "${GATEWAY}/api/v1/users/${OWNER_B_ID}" "$OWNER_B_TOKEN")")" \
    "[control] tenant B's admin is still fetchable by tenant B afterwards"
fi

# And the other direction: LIST must not leak either.
LIST_B2="$(req GET "${GATEWAY}/api/v1/users?size=200" "$OWNER_B_TOKEN")"
if printf '%s' "$(body_of "$LIST_B2")" | grep -q "$CASHIER_EMAIL"; then
  echo "FAIL: tenant B's user list contains tenant A's user"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
else
  echo "PASS: tenant B's user list does not contain tenant A's user"
  PHASE13_PASS=$((PHASE13_PASS + 1))
fi
if printf '%s' "$(body_of "$LIST_B2")" | grep -q "$OWNER_B_EMAIL"; then
  echo "PASS: [control] and it DOES contain tenant B's own user, so the list is not simply empty"
  PHASE13_PASS=$((PHASE13_PASS + 1))
else
  echo "FAIL: [control] tenant B's list is empty — the assertion above proved nothing"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi
echo

# ── 6. The privilege ceiling, exercised by a real TENANT_ADMIN ──────────────────────────────

echo "--- the role ceiling (a TENANT_ADMIN, not the OWNER) ---"

# OWNER holds rbac.manage, so OWNER granting OWNER is legitimate. The escalation 13-02's authority
# split exists to prevent is a TENANT_ADMIN minting an OWNER, so make a real one, through the very
# API under test, and let it try.
TA_CREATE="$(req POST "${GATEWAY}/api/v1/users" "$OWNER_A_TOKEN" \
  "$(jbody email "$TADMIN_EMAIL" fullName "E2E Tenant Admin" branchId "$BRANCH_A_ID" roleCode TENANT_ADMIN)")"
assert_status 201 "$(status_of "$TA_CREATE")" "the OWNER may create a TENANT_ADMIN (its own ceiling permits it)"
TADMIN_TEMP="$(body_of "$TA_CREATE" | json_get "['data']['tempPassword']" 2>/dev/null || true)"

TADMIN_TOKEN=""
if [[ -n "$TADMIN_TEMP" && "$TADMIN_TEMP" != "None" ]] \
   && clear_forced_change "$TADMIN_EMAIL" "$TADMIN_TEMP" "$SLUG_A_REAL" "$TADMIN_NEW_PASSWORD"; then
  TADMIN_TOKEN="$(enrol_and_login "$TADMIN_EMAIL" "$TADMIN_NEW_PASSWORD" "$SLUG_A_REAL" 2>/dev/null || true)"
fi

if [[ -z "$TADMIN_TOKEN" || "$TADMIN_TOKEN" == "None" ]]; then
  echo "FAIL: the created TENANT_ADMIN never came online, so the ceiling could not be exercised"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
else
  echo "PASS: the created TENANT_ADMIN is fully online (created → forced change → enrolled → token)"
  PHASE13_PASS=$((PHASE13_PASS + 1))

  # The control: this caller really can administer users. Without it, the 403 below is satisfied by
  # a caller who simply lacks the authority — which proves nothing about the ceiling.
  assert_status 200 "$(status_of "$(req GET "${GATEWAY}/api/v1/users?size=5" "$TADMIN_TOKEN")")" \
    "[control] the TENANT_ADMIN holds the user-administration authority"

  CEIL_CREATE="$(req POST "${GATEWAY}/api/v1/users" "$TADMIN_TOKEN" \
    "$(jbody email "escalate@${SLUG_A}.local" branchId "$BRANCH_A_ID" roleCode OWNER)")"
  assert_status 403 "$(status_of "$CEIL_CREATE")" \
    "a TENANT_ADMIN is REFUSED creating a user in the highest tenant role"
  assert_contains "$(body_of "$CEIL_CREATE")" 'ROLE_CEILING_EXCEEDED' \
    "the refusal says it is a ceiling refusal, not an opaque 500 (13-07 finding, 13-11 fix)"
  if printf '%s' "$(body_of "$CEIL_CREATE")" | grep -q 'rbac.manage'; then
    echo "FAIL: the refusal named the permission codes it is withholding"
    PHASE13_FAIL=$((PHASE13_FAIL + 1))
  else
    echo "PASS: the refusal names the role and a count, never the permission codes it withholds"
    PHASE13_PASS=$((PHASE13_PASS + 1))
  fi

  # Nothing was written. A refusal that has already created the account is not a refusal.
  ESCALATED="$(req GET "${GATEWAY}/api/v1/users?size=200&search=escalate" "$OWNER_A_TOKEN")"
  if printf '%s' "$(body_of "$ESCALATED")" | grep -q "escalate@${SLUG_A}.local"; then
    echo "FAIL: the refused create left a user row behind"
    PHASE13_FAIL=$((PHASE13_FAIL + 1))
  else
    echo "PASS: the refused create wrote nothing at all"
    PHASE13_PASS=$((PHASE13_PASS + 1))
  fi

  CEIL_ASSIGN="$(req POST "${GATEWAY}/api/v1/users/${CASHIER_ID}/branch-roles" "$TADMIN_TOKEN" \
    "$(jbody branchId "$BRANCH_A_ID" roleCode OWNER)")"
  assert_status 403 "$(status_of "$CEIL_ASSIGN")" \
    "a TENANT_ADMIN is REFUSED assigning the highest tenant role to an existing user"
fi
echo

# ── 7. The authorization floor ──────────────────────────────────────────────────────────────

echo "--- the authorization floor ---"

FLOOR_TOKEN="${BACK_TOKEN:-$CASHIER_TOKEN}"
if [[ -n "$FLOOR_TOKEN" && "$FLOOR_TOKEN" != "None" ]]; then
  assert_status 403 "$(status_of "$(req GET "${GATEWAY}/api/v1/users" "$FLOOR_TOKEN")")" \
    "an ordinary staff account cannot LIST users"
  assert_status 403 "$(status_of "$(req POST "${GATEWAY}/api/v1/users" "$FLOOR_TOKEN" \
    "$(jbody email "nope@${SLUG_A}.local")")")" \
    "an ordinary staff account cannot CREATE a user"
  assert_status 403 "$(status_of "$(req POST "${GATEWAY}/api/v1/users/${CASHIER_ID}/deactivate" "$FLOOR_TOKEN")")" \
    "an ordinary staff account cannot DEACTIVATE a user"
else
  echo "FAIL: no staff token available for the authorization floor"
  PHASE13_FAIL=$((PHASE13_FAIL + 1))
fi

assert_status 401 "$(status_of "$(req GET "${GATEWAY}/api/v1/users")")" \
  "an anonymous caller cannot list users"
assert_status 401 "$(status_of "$(req POST "${GATEWAY}/api/v1/users" "" "$(jbody email "nope@${SLUG_A}.local")")")" \
  "an anonymous caller cannot create a user"
echo

phase13_summary
