package io.restaurantos.hr.entity;

import io.restaurantos.shared.security.EncryptedStringConverter;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;
import java.util.UUID;

/**
 * Biometric attendance device registry (HR-07). {@code deviceToken} is the device's shared secret,
 * field-encrypted (AES-256-GCM) into a {@code bytea} column exactly like employee PII. The serial
 * number is globally unique and is the lookup key the device-authenticated ingest path resolves
 * tenant/branch from — never client-supplied tenant headers.
 */
@Entity
@Table(name = "attendance_devices")
@Getter
@Setter
public class AttendanceDeviceEntity {

    public enum ConnectionMode { NETWORK_ADMS, USB_BRIDGE, MANUAL }

    /**
     * How a device proves it is itself (D-25-06, decided 2026-08-11 as {@code both}).
     *
     * <p>{@link #TOKEN} is the mode in force before phase 25 and remains the default for every device,
     * existing and new. The other two exist because <b>a stock ZKTeco terminal cannot use TOKEN</b>:
     * its configuration menu offers Enable, Domain Name, Server Address, Server Port and proxy
     * settings, and the request path and its entire query string are generated by firmware, so there
     * is nowhere to type a per-device secret. That is not a gap in the management surface; it is the
     * reason no such terminal could connect at all.
     *
     * <p>A device's mode is changed only by an explicit, audited act. Never by migration, never by
     * default, and never as a side effect of registration.
     */
    public enum AuthMode {
        /** Per-device token in the query string. The default, the strongest, and unusable by stock firmware. */
        TOKEN,
        /** The request's Host header must match a per-device hostname. Needs DNS and a certificate per branch. */
        HOST_MAPPED,
        /**
         * Serial alone, bounded by a source-address allowlist that MUST be non-empty — checked before
         * anything else and failing closed. The weakest mode and the one most single-restaurant
         * deployments will run; see 25-AUTH-MODES.md for the residual risk, written down rather than
         * inferred.
         */
        SERIAL_ONLY_BOUNDED
    }

    /** Whether this terminal is being heard from on the cadence it was configured to expect (D-25-02). */
    public enum HealthState {
        /** Registered and never yet contacted. The honest state for a device that is not installed. */
        UNKNOWN,
        /** Heard from within its own expected-contact interval. */
        HEALTHY,
        /** Silent for longer than its own interval. */
        SILENT,
        /** Heard from, but its clock disagrees with the server's by more than its own tolerance. */
        CLOCK_SKEWED
    }

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "tenant_id", nullable = false)
    private UUID tenantId;

    @Column(name = "branch_id", nullable = false)
    private UUID branchId;

    @Column(name = "serial_no", nullable = false)
    private String serialNo;

    @Column(name = "model")
    private String model;

    @Enumerated(EnumType.STRING)
    @Column(name = "connection_mode", nullable = false)
    private ConnectionMode connectionMode;

    @Convert(converter = EncryptedStringConverter.class)
    @Column(name = "device_token", columnDefinition = "bytea", nullable = false)
    private String deviceToken;

    @Column(name = "last_seen_at")
    private Instant lastSeenAt;

    @Column(name = "is_active", nullable = false)
    private boolean active = true;

    // ── Identity (25-03; read by 25-09, 25-11) ────────────────────────────────────────────────
    /** A name a human chose. {@code model} is not a name — two identical units in one branch need one. */
    @Column(name = "display_name")
    private String displayName;

    // ── Locale (25-03; read by 25-05) ─────────────────────────────────────────────────────────
    /** The zone the device's reported timestamps are in. Defaulted to the constant the parser hard-codes. */
    @Column(name = "device_timezone", nullable = false)
    private String deviceTimezone = "Asia/Karachi";

    // ── Liveness (25-03; read by 25-10, 25-11) ────────────────────────────────────────────────
    /** How long this device may be silent before that is a fault. Its own cadence, not a global guess. */
    @Column(name = "expected_contact_interval_seconds", nullable = false)
    private int expectedContactIntervalSeconds = 900;

    @Enumerated(EnumType.STRING)
    @Column(name = "health_state", nullable = false)
    private HealthState healthState = HealthState.UNKNOWN;

    /** When silence STARTED, so 25-10 can alert on the transition rather than on the state. */
    @Column(name = "silent_since")
    private Instant silentSince;

    // ── Clock discipline (25-03; read by 25-10) ───────────────────────────────────────────────
    /** The tolerance. The skew itself is never stored — it is derived from the two punch timestamps. */
    @Column(name = "max_clock_skew_seconds", nullable = false)
    private int maxClockSkewSeconds = 300;

    // ── Sync configuration (25-03; read by 25-07, edited by 25-09/25-11) ──────────────────────
    // Every default here equals the literal AdmsController currently emits, so no device changes.
    @Column(name = "realtime_push", nullable = false)
    private boolean realtimePush = true;

    @Column(name = "poll_delay_seconds", nullable = false)
    private int pollDelaySeconds = 30;

    @Column(name = "error_delay_seconds", nullable = false)
    private int errorDelaySeconds = 30;

    @Column(name = "transfer_interval_minutes", nullable = false)
    private int transferIntervalMinutes = 1;

    @Column(name = "transfer_times", nullable = false)
    private String transferTimes = "00:00;14:05";

    /** ADMS TransFlag. Not free text — see the column comment in changelog 033 before changing it. */
    @Column(name = "transfer_flag", nullable = false)
    private String transferFlag = "1111000000";

    // ── Authentication mode (25-03; read and implemented by 25-08) ────────────────────────────
    /** Defaults to TOKEN: the mode in force today. A migration must never relax an existing device. */
    @Enumerated(EnumType.STRING)
    @Column(name = "auth_mode", nullable = false)
    private AuthMode authMode = AuthMode.TOKEN;

    /** Comma-separated IPs/CIDRs. MUST be non-empty for any mode presenting no secret (25-08). */
    @Column(name = "source_address_allowlist")
    private String sourceAddressAllowlist;

    /** The address a refusal was actually seen from, so a changed public IP is self-service to fix. */
    @Column(name = "last_refused_source_address")
    private String lastRefusedSourceAddress;

    @Column(name = "last_refused_at")
    private Instant lastRefusedAt;

    // ── Lifecycle (25-03; read by 25-09, 25-11) ───────────────────────────────────────────────
    /** Removal is a recorded event. Punches must stay resolvable to their device after it is removed. */
    @Column(name = "archived_at")
    private Instant archivedAt;

    /** Rotation stops the terminal working until someone retypes the token; 25-10 reads this so the
     *  resulting silence is reported as a consequence rather than as a fault. */
    @Column(name = "token_rotated_at")
    private Instant tokenRotatedAt;
}
