import { describe, it, expect, afterEach } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { http, HttpResponse } from "msw";

import { server } from "@/mocks/server";
import { seedSession, clearSession } from "@/__tests__/utils/auth-fixtures";
import { createQueryWrapper } from "@/__tests__/utils/query-wrapper";
import { PaymentPanel } from "@/components/pos/payment-panel";
import type { Order } from "@/lib/models/pos.model";

const ORDER_ID = "d1000001-0000-4000-8000-000000000001";

const mockOrder: Order = {
  id: ORDER_ID,
  branchId: "b0000001-0000-4000-8000-000000000001",
  orderNo: "ORD-20260630-0001",
  type: "DINE_IN",
  status: "SERVED",
  tableId: null,
  coverCount: 2,
  cashierId: null,
  customerId: null,
  subtotalPaisa: 85000,
  taxPaisa: 4250,
  discountPaisa: 0,
  serviceChargePaisa: 0,
  totalPaisa: 89250,
  notes: null,
  openedAt: "2026-06-30T00:00:00Z",
  sentToKdsAt: null,
  clientOrderId: "c0000001-0000-4000-8000-000000000001",
  version: 0,
  items: [],
};

// Minimal raw response that passes apiOrderSchema
const rawClosedOrder = {
  id: ORDER_ID,
  branchId: "b0000001-0000-4000-8000-000000000001",
  orderNo: "ORD-20260630-0001",
  type: "DINE_IN",
  status: "CLOSED",
  clientOrderId: "c0000001-0000-4000-8000-000000000001",
  version: 1,
  tableId: null,
  coverCount: 2,
  cashierId: null,
  customerId: null,
  subtotalPaisa: 85000,
  taxPaisa: 4250,
  discountPaisa: 0,
  serviceChargePaisa: 0,
  totalPaisa: 89250,
  notes: null,
  openedAt: "2026-06-30T00:00:00Z",
  sentToKdsAt: null,
  items: [],
};

function renderPanel(order: Order = mockOrder) {
  seedSession({ permissions: ["pos.order.close"] });
  const Wrapper = createQueryWrapper();
  return render(
    <Wrapper>
      <PaymentPanel order={order} />
    </Wrapper>,
  );
}

describe("PaymentPanel", () => {
  afterEach(() => clearSession());

  it("CHARGE NOW button is disabled when remaining balance is greater than zero", async () => {
    renderPanel();
    const user = userEvent.setup();

    const amountInput = screen.getByLabelText("Amount in paisa");
    await user.clear(amountInput);
    // Enter an amount below the order total so remaining > 0
    await user.type(amountInput, "1000");

    expect(screen.getByLabelText("Charge order")).toBeDisabled();
  });

  it("CHARGE NOW button is enabled when payment sum exactly equals order total", () => {
    // Payment panel initialises first row with amountPaisa = order.totalPaisa,
    // so remaining === 0 and the button must be active immediately.
    renderPanel();

    expect(screen.getByLabelText("Charge order")).not.toBeDisabled();
  });

  it("sends Idempotency-Key UUID header when closing the order", async () => {
    let capturedKey: string | null = null;

    server.use(
      http.post(`*/api/v1/pos/orders/${ORDER_ID}/close`, async ({ request }) => {
        capturedKey = request.headers.get("Idempotency-Key");
        return HttpResponse.json(
          { data: rawClosedOrder, meta: null, warnings: [] },
          { status: 200 },
        );
      }),
    );

    renderPanel();
    const user = userEvent.setup();

    const chargeBtn = screen.getByLabelText("Charge order");
    expect(chargeBtn).not.toBeDisabled();

    await user.click(chargeBtn);

    await waitFor(() => {
      expect(capturedKey).not.toBeNull();
    });

    // Key must be a v4 UUID generated by crypto.randomUUID()
    expect(capturedKey).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
    );
  });
});
