#!/usr/bin/env python3
"""
The authoritative RestaurantOS seed (phase 13, plan 13-15, D-25 / D-30).

WHAT THIS IS FOR
================

The production-readiness audit (AUDIT-REPORT-2026-08-06.md) found
`.planning/phases/03-*/03-VERIFICATION.md` scoring Phase 3 "24/24 passed" while citing a
controller that does not exist. That verification was STRUCTURAL — it grepped source — which
is exactly why blocker B1 (no SuperAdmin could authenticate) survived for months inside a
phase marked complete.

This script is the countermeasure. It cannot report success unless every repaired path
actually works end to end through the real gateway, because its final phase authenticates
all nineteen seeded principals itself and exits non-zero, naming every failure, if any one of
them cannot log in. Verification is NOT performed by inspecting the database for expected
rows — a row is what a broken API leaves behind too.

WHAT IT PRODUCES
================

  * the project SuperAdmin, VERIFIED BY LOGIN (it is created by 13-05's migration; a seeder
    that silently re-creates what a migration owns is how two sources of truth appear)
  * Floating Terrace (the working tenant, ENTERPRISE, richly seeded) plus one small
    isolation-control tenant, with DELIBERATELY DIVERGENT enabled module sets,
    asserted to differ rather than assumed to
  * eight personas per tenant — one for every role in the catalog — each
    created through the real user API, each activated through the real forced-change flow,
    each ending with its documented working password and NO outstanding temporary credential
  * TOTP enrolment for every persona the platform challenges for step-up (D-29a)
  * menu, inventory, purchasing and point-of-sale data per tenant, at different volumes, so
    dashboards and reports are non-empty and visibly different between tenants

STRATEGY: DRIVE THE REAL API (D-28)
===================================

Every resource is created through the public API at the gateway wherever one exists, because
driving the real API is what proves the repair. Direct database writes are permitted only
where no API exists; the ledger of them is printed on EVERY run, so the remaining gaps stay
visible rather than archaeological. On the happy path that ledger is empty and the script
says so explicitly.

IDEMPOTENCY
===========

Every identifier this script controls is a uuid5 over a stable name, using the same namespace
`scripts/onboarding.py` uses. Resources whose identifier the server assigns — tenants, users
— are looked up first and reconciled rather than duplicated. A second run completes and
changes nothing material.

USAGE
=====

    python3 scripts/seed_restaurantos.py                  # every phase
    python3 scripts/seed_restaurantos.py --phase platform
    python3 scripts/seed_restaurantos.py --phase personas
    python3 scripts/seed_restaurantos.py --phase business
    python3 scripts/seed_restaurantos.py --phase verify   # the acceptance test

    # prove the verification can fail (T-13-15-D) — dev stack only:
    python3 scripts/seed_restaurantos.py --corrupt-persona cashier@saffron.local
    python3 scripts/seed_restaurantos.py --phase verify    # must exit 1 naming that address

CREDENTIALS
===========

Every credential is DEVELOPMENT-ONLY and is documented in `scripts/README-seed.md`. Nothing
here belongs in a deployed environment. This script prints principal identifiers and
outcomes; it never prints a password or a token (T-13-15-E).

DEPENDENCIES
============

Python 3 standard library only. `T-13-15-SC` forbids installing a package to make a
verification script run, so TOTP, JSON, HTTP and base32 are all done with stdlib — the same
choice 13-10 and 13-13 made for the same reason.
"""

from __future__ import annotations

import argparse
import base64
import binascii
import hashlib
import hmac
import json
import os
import re
import ssl
import struct
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterable

REPO_ROOT = Path(__file__).resolve().parent.parent

# The SAME namespace scripts/onboarding.py uses, so an identifier this script derives and one
# that script derives for the same name are the same identifier.
UUID_NS = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")

GATEWAY = os.environ.get("GATEWAY", "http://localhost:8080").rstrip("/")

# State this script must remember between runs. TOTP secrets are generated by auth-service at
# enrolment and are NOT derivable — losing them means a persona holding a second factor cannot
# be logged in again. Kept out of git; see .gitignore.
STATE_DIR = Path(os.environ.get("SEED_STATE_DIR", REPO_ROOT / ".seed-state"))
TOTP_DIR = STATE_DIR / "totp"

# ── The SuperAdmin ──────────────────────────────────────────────────────────────────────────
# Created by 13-05's migration. This script VERIFIES it by logging in, and fails immediately
# naming that migration if the login does not succeed.
SUPERADMIN_EMAIL = "superadmin@softxlogic.com"
SUPERADMIN_PASSWORD = "Test@123!"
SUPERADMIN_MIGRATION = (
    "services/platform-admin-service/src/main/resources/db/changelog/"
    "v1.0.0/901-seed-project-superadmin.xml"
)

# ── Tenants ─────────────────────────────────────────────────────────────────────────────────
#
# Three tiers AND two deliberate feature overrides on top, because tier alone would leave the
# STARTER/GROWTH/ENTERPRISE sets nested — each a superset of the last. Turning a primary module
# OFF for one tenant and an above-tier feature ON for another makes the three sets genuinely
# incomparable, which is what actually exercises feature gating instead of assuming it.
#
# FEATURE_CRM is the module switched off: nothing this script seeds touches CRM, so the
# divergence is real without making the tenant unusable. FEATURE_NLQ is the above-tier grant:
# it is GROWTH+, so a STARTER tenant holding it can only have got it from an override.

TENANTS: list[dict[str, Any]] = [
    {
        # THE working tenant. This is a real restaurant the user is building for, so it gets
        # the top tier, every module, a second branch, and enough transactional data that the
        # dashboards and reports have something to show.
        "key": "terrace",
        "brand": "Floating Terrace",
        "tier": "ENTERPRISE",
        "overrides": [],
        "extra_branches": ["Floating Terrace — Rooftop"],
        "orders": 24,
        "menu_items": 18,
        "invoices": 6,
    },
    {
        # An isolation CONTROL, kept deliberately small.
        #
        # The user asked for the other tenants to be dropped. One is retained on purpose: with a
        # single tenant, no test can distinguish "tenant scoping works" from "there is only one
        # tenant's data to return". Cross-tenant leakage is the highest-severity defect class in
        # a multi-tenant system and it is unobservable without a second tenant — plan 13-12
        # proved tenant isolation precisely by provisioning two and asserting all five verbs 404
        # across the boundary.
        #
        # It also keeps feature-gating honest: its module set is deliberately different from
        # Floating Terrace's, so a disabled module is exercised rather than assumed.
        #
        # Delete this entry if it is genuinely unwanted — the seed will still run, but the
        # isolation and feature-gating assertions lose their control.
        "key": "control",
        "brand": "Control Bistro (isolation test tenant)",
        "tier": "STARTER",
        # A PRIMARY module switched OFF: FEATURE_CRM is ON in every tier by default, so this is
        # a genuine divergence rather than a tier artefact.
        "overrides": [("FEATURE_CRM", False)],
        "extra_branches": [],
        "orders": 2,
        "menu_items": 3,
        "invoices": 1,
    },
]

# ── Personas ────────────────────────────────────────────────────────────────────────────────
#
# Six per tenant, exactly the set 13-CONTEXT names. The OWNER is the admin the provisioning
# saga creates; the other five are created through the public user API by that OWNER.
#
# `verify_path` is the ONE role-appropriate endpoint the verification loop calls for this
# persona. Each is gated on a permission ONLY that role holds among the six, so a 200 says
# something about this role rather than about the platform being open:
#
#   OWNER          rbac.manage        GET /api/v1/users
#   MANAGER        pos.menu.manage    GET /api/v1/pos/menu/categories/admin
#   CASHIER        pos.till.open      GET /api/v1/pos/tills
#   WAITER         pos.order.view     GET /api/v1/pos/tables
#   KITCHEN_STAFF  pos.kds.view       GET /api/v1/pos/stations   (its ONLY reachable POS read)
#   ACCOUNTANT     finance.coa.view   GET /api/v1/finance/accounts

# Approval limits (paisa) written onto user_branch_roles when the persona is assigned.
# vendor.rego / finance.rego / pos.rego all fail-closed when approval_limit_paisa is absent,
# so a seeded MANAGER with vendor.po.approve but a NULL limit cannot approve any PO.
# Values match the demo Liquibase seeds (900-seed-auth-dev-data.xml) and onboarding.py.
APPROVAL_LIMIT_BY_ROLE: dict[str, int | None] = {
    "OWNER": 100_000_000,
    "TENANT_ADMIN": 100_000_000,
    "ACCOUNTANT": 50_000_000,
    "MANAGER": 30_000_000,
    "FINANCE_VIEWER": 25_000_000,
    "CASHIER": 5_000_000,
    "WAITER": None,
    "KITCHEN_STAFF": None,
    "INVENTORY_MANAGER": None,
}

PERSONAS: list[dict[str, Any]] = [
    {"local": "owner", "role": "OWNER", "label": "Owner / tenant admin",
     "provisioned": True, "verify_path": "/api/v1/users?page=0&size=1"},
    {"local": "manager", "role": "MANAGER", "label": "Branch manager",
     "provisioned": False, "verify_path": "/api/v1/pos/menu/categories/admin"},
    {"local": "cashier", "role": "CASHIER", "label": "Cashier (till control)",
     "provisioned": False, "verify_path": "/api/v1/pos/tills"},
    {"local": "waiter", "role": "WAITER", "label": "Waiter (no till)",
     "provisioned": False, "verify_path": "/api/v1/pos/tables?branchId={branch}"},
    {"local": "kitchen", "role": "KITCHEN_STAFF", "label": "Kitchen / KDS",
     "provisioned": False, "verify_path": "/api/v1/pos/stations?branchId={branch}"},
    {"local": "accountant", "role": "ACCOUNTANT", "label": "Accountant",
     "provisioned": False, "verify_path": "/api/v1/finance/accounts"},
    # Added so every role in the catalog has a live persona. `SELECT code FROM roles` returns
    # exactly these eight; seeding six left TENANT_ADMIN and INVENTORY_MANAGER with no account,
    # which meant nothing exercised them — and TENANT_ADMIN is the role the whole 13-11/13-12
    # privilege-ceiling work exists to constrain, so leaving it unseeded left the most
    # security-relevant role untested end to end.
    {"local": "admin", "role": "TENANT_ADMIN", "label": "Tenant admin (user + branch admin)",
     "provisioned": False, "verify_path": "/api/v1/users?page=0&size=1"},
    {"local": "storekeeper", "role": "INVENTORY_MANAGER", "label": "Store keeper / inventory",
     "provisioned": False, "verify_path": "/api/v1/inventory/ingredients"},
]


def persona_email(tenant_key: str, local: str) -> str:
    return f"{local}@{tenant_key}.local"


def persona_password(tenant_key: str, local: str) -> str:
    """
    Deterministic, documented, and policy-satisfying: >= 8 characters with a lowercase letter,
    an uppercase letter, a digit and a special character (shared-lib @StrongPassword).

        Saffron#Owner1, Zaitoon#Cashier1, Marina#Accountant1, ...
    """
    return f"{tenant_key.capitalize()}#{local.capitalize()}1"


def persona_full_name(tenant_key: str, local: str) -> str:
    return f"{tenant_key.capitalize()} {local.capitalize()}"


# ════════════════════════════════════════════════════════════════════════════════════════════
# Output
# ════════════════════════════════════════════════════════════════════════════════════════════

_BOLD, _DIM, _RED, _GREEN, _YELLOW, _RESET = (
    ("\033[1m", "\033[2m", "\033[31m", "\033[32m", "\033[33m", "\033[0m")
    if sys.stdout.isatty() else ("", "", "", "", "", "")
)


def banner(text: str) -> None:
    print()
    print(f"{_BOLD}{'=' * 78}{_RESET}")
    print(f"{_BOLD}  {text}{_RESET}")
    print(f"{_BOLD}{'=' * 78}{_RESET}")


def step(text: str) -> None:
    print(f"  {_DIM}·{_RESET} {text}")


def ok(text: str) -> None:
    print(f"  {_GREEN}✓{_RESET} {text}")


def warn(text: str) -> None:
    print(f"  {_YELLOW}!{_RESET} {text}")


def die(text: str) -> None:
    print(f"\n{_RED}FATAL:{_RESET} {text}\n", file=sys.stderr)
    sys.exit(2)


# ════════════════════════════════════════════════════════════════════════════════════════════
# T-13-15-C — refuse to seed anything that is not obviously a local development stack
# ════════════════════════════════════════════════════════════════════════════════════════════

LOCAL_HOSTS = {"localhost", "127.0.0.1", "::1", "0.0.0.0", "host.docker.internal", "gateway"}


def assert_target_is_local(force: bool) -> None:
    host = (urllib.parse.urlparse(GATEWAY).hostname or "").lower()
    allowed = {h.strip().lower() for h in os.environ.get("SEED_ALLOWED_HOSTS", "").split(",") if h.strip()}
    if host in LOCAL_HOSTS or host in allowed:
        return
    if force:
        warn(f"GATEWAY host '{host}' is not local — proceeding because --i-know-what-i-am-doing was given.")
        return
    die(
        f"GATEWAY resolves to '{host}', which is neither local nor allow-listed.\n"
        f"  This script creates real tenants, real users with documented passwords, and real\n"
        f"  transactional data. Pointing it at anything production-like would be a tampering\n"
        f"  event, not a seeding one.\n"
        f"  Allow-list it with SEED_ALLOWED_HOSTS='{host}', or pass --i-know-what-i-am-doing."
    )


# ════════════════════════════════════════════════════════════════════════════════════════════
# HTTP
# ════════════════════════════════════════════════════════════════════════════════════════════

@dataclass
class Response:
    status: int
    body: Any
    raw: str

    def get(self, *path: str, default: Any = None) -> Any:
        node = self.body
        for key in path:
            if not isinstance(node, dict):
                return default
            node = node.get(key)
            if node is None:
                return default
        return node

    def data(self, *path: str, default: Any = None) -> Any:
        return self.get("data", *path, default=default)

    @property
    def error_code(self) -> str:
        return str(self.get("error", "code", default="") or self.get("code", default="") or "")

    def __str__(self) -> str:  # never carries a credential we put IN, but may carry one we got OUT
        return f"HTTP {self.status}"


_UNSAFE = ssl.create_default_context()
_UNSAFE.check_hostname = False
_UNSAFE.verify_mode = ssl.CERT_NONE


def request(
    method: str,
    path: str,
    token: str | None = None,
    body: Any = None,
    origin: str | None = None,
    retries: int = 6,
) -> Response:
    """
    One HTTP call, with the two retry behaviours this gateway genuinely requires.

    429 — RETRY WITH BACKOFF, NEVER A FAILURE. `platform-auth-route` is rate-limited at
    2/s (burst 100) and 13-13 recorded a script reporting "the SuperAdmin could not log in"
    seconds before a direct login answered 200. A seed that reports a fake failure is as bad
    as one that reports a fake success.

    503 SERVICE_UNAVAILABLE — retried once. This gateway's Resilience4j breaker answers the
    first request against a cold `lb://` pool with its own fallback body even though the
    backend is healthy. A SECOND consecutive 503 is returned as-is: this must never become a
    loop that hides a genuinely dead upstream.
    """
    url = (origin or GATEWAY).rstrip("/") + path
    payload = None if body is None else json.dumps(body).encode()
    delay = 0.75
    last: Response | None = None

    for attempt in range(retries):
        req = urllib.request.Request(url, data=payload, method=method)
        req.add_header("Accept", "application/json")
        if payload is not None:
            req.add_header("Content-Type", "application/json")
        if token:
            req.add_header("Authorization", f"Bearer {token}")

        try:
            with urllib.request.urlopen(req, timeout=90, context=_UNSAFE) as resp:
                raw = resp.read().decode("utf-8", "replace")
                status = resp.status
        except urllib.error.HTTPError as exc:
            raw = exc.read().decode("utf-8", "replace")
            status = exc.code
        except urllib.error.URLError as exc:
            if attempt == retries - 1:
                die(f"{method} {path}: cannot reach {url} — {exc.reason}. Is the gateway up?")
            time.sleep(delay)
            delay *= 2
            continue

        try:
            parsed = json.loads(raw) if raw.strip() else None
        except json.JSONDecodeError:
            parsed = None

        last = Response(status, parsed, raw)

        if status == 429:
            time.sleep(delay)
            delay = min(delay * 2, 20)
            continue
        if status == 503 and "SERVICE_UNAVAILABLE" in raw and attempt < 1:
            time.sleep(2)
            continue
        return last

    return last  # type: ignore[return-value]


def expect(resp: Response, *statuses: int, what: str) -> Response:
    if resp.status not in statuses:
        die(f"{what}: expected {' or '.join(map(str, statuses))}, got {resp.status} — {resp.raw[:600]}")
    return resp


# ════════════════════════════════════════════════════════════════════════════════════════════
# TOTP (pure stdlib — T-13-15-SC forbids installing pyotp to make a seed run)
# ════════════════════════════════════════════════════════════════════════════════════════════

def totp_now(secret: str, skew: int = 0) -> str:
    key = base64.b32decode(secret + "=" * (-len(secret) % 8), casefold=True)
    counter = int(time.time()) // 30 + skew
    mac = hmac.new(key, struct.pack(">Q", counter), hashlib.sha1).digest()
    off = mac[-1] & 0x0F
    return str((struct.unpack(">I", mac[off:off + 4])[0] & 0x7FFFFFFF) % 10 ** 6).zfill(6)


def totp_secret_path(email: str) -> Path:
    return TOTP_DIR / re.sub(r"[^A-Za-z0-9._@-]", "_", email)


def load_totp_secret(email: str) -> str | None:
    p = totp_secret_path(email)
    return p.read_text().strip() if p.is_file() else None


def store_totp_secret(email: str, secret: str) -> None:
    TOTP_DIR.mkdir(parents=True, exist_ok=True)
    p = totp_secret_path(email)
    p.write_text(secret)
    os.chmod(p, 0o600)


# ════════════════════════════════════════════════════════════════════════════════════════════
# The direct-write ledger (T-13-15-B) — printed on EVERY run
# ════════════════════════════════════════════════════════════════════════════════════════════

@dataclass
class DirectWrite:
    what: str
    service: str
    table: str
    reason: str
    replacement: str


DIRECT_WRITES: list[DirectWrite] = []
GAPS: list[str] = []


def record_direct_write(what: str, service: str, table: str, reason: str, replacement: str) -> None:
    DIRECT_WRITES.append(DirectWrite(what, service, table, reason, replacement))


def print_direct_write_ledger() -> None:
    banner("DIRECT DATABASE WRITES PERFORMED BY THIS RUN")
    if not DIRECT_WRITES:
        print("  NONE. Every resource this run created or changed went through a real API at the")
        print("  gateway. There is nothing on this list, and that is stated explicitly rather than")
        print("  left to be inferred from an empty section.")
    else:
        for i, dw in enumerate(DIRECT_WRITES, 1):
            print(f"  {i}. {_BOLD}{dw.what}{_RESET}")
            print(f"     owning service : {dw.service}")
            print(f"     table          : {dw.table}")
            print(f"     why no API     : {dw.reason}")
            print(f"     would be replaced by: {dw.replacement}")
    if GAPS:
        print()
        print(f"  {_BOLD}Known gaps encountered on this run (no write was made for these):{_RESET}")
        for g in GAPS:
            print(f"    - {g}")


# ════════════════════════════════════════════════════════════════════════════════════════════
# SQL — used ONLY for the two recovery paths and for the deliberate-corruption demo
# ════════════════════════════════════════════════════════════════════════════════════════════

PG_CONTAINER = os.environ.get("SEED_PG_CONTAINER", "restaurantos-postgres")
DB_ROLES = {
    "auth_db": "auth_user",
    "user_db": "user_service",
    "platform_db": "platform_admin",
    "pos_db": "pos_service",
    "finance_db": "finance_user",
}


def tenant_id_for_email(email: str) -> str:
    """
    Resolve the tenant that owns a persona address, so an RLS-scoped statement can set the GUC.

    Needed because `auth_db.users` is `ENABLE` + **FORCE** ROW LEVEL SECURITY and `auth_user` is
    `NOSUPERUSER NOBYPASSRLS` — so a statement without the right tenant GUC sees no rows at all,
    including from psql. That is the correct posture, and it is worth contrasting with
    `pos_db`/`purchasing_db`, whose tables are NOT forced and whose owner therefore sees
    everything (see `seed_menu`).
    """
    domain = email.split("@")[-1]
    key = domain.split(".")[0]
    brand = next((s["brand"] for s in TENANTS if s["key"] == key), None)
    if not brand:
        die(f"'{email}' does not belong to any tenant this script seeds")
    row = sql("platform_db",
              f"SELECT id FROM tenants WHERE brand_name = '{brand}' ORDER BY created_at DESC LIMIT 1;")
    if not row:
        die(f"tenant '{brand}' does not exist — run --phase platform first")
    return row.splitlines()[0].strip()


def sql(database: str, statement: str) -> str:
    role = DB_ROLES[database]
    proc = subprocess.run(
        ["docker", "exec", "-i", PG_CONTAINER, "psql", "-U", role, "-d", database,
         "-v", "ON_ERROR_STOP=1", "-qtA"],
        input=statement, capture_output=True, text=True,
    )
    if proc.returncode != 0:
        die(f"psql ({role}@{database}) failed: {proc.stderr.strip()[:500]}")
    return proc.stdout.strip()


# ════════════════════════════════════════════════════════════════════════════════════════════
# Authentication
# ════════════════════════════════════════════════════════════════════════════════════════════

def jwt_claims(token: str) -> dict[str, Any]:
    seg = token.split(".")[1]
    seg += "=" * (-len(seg) % 4)
    return json.loads(base64.urlsafe_b64decode(seg))


class SuperAdmin:
    """
    ONE platform login, reused. `platform-auth-route` is rate-limited at 2/s and a seed that
    logs the SuperAdmin in per call will hit 429; the platform token is also short-lived and
    non-refreshable, so it is re-minted only when it is genuinely close to expiring.
    """

    def __init__(self) -> None:
        self._token: str | None = None
        self._expires_at: float = 0.0
        self.user_id: str | None = None

    def token(self) -> str:
        if self._token and time.time() < self._expires_at - 60:
            return self._token
        resp = request("POST", "/api/v1/platform/auth/login",
                       body={"email": SUPERADMIN_EMAIL, "password": SUPERADMIN_PASSWORD})
        if resp.status != 200:
            die(
                f"The project SuperAdmin '{SUPERADMIN_EMAIL}' could not log in through the gateway "
                f"(HTTP {resp.status}).\n"
                f"  This account is owned by a MIGRATION, not by this script — it is deliberately\n"
                f"  NOT re-created here, because a seeder that silently re-creates what a migration\n"
                f"  owns is how two sources of truth appear.\n"
                f"  Check {SUPERADMIN_MIGRATION} has run against platform_db, and that\n"
                f"  platform-admin-service and the gateway are both up.\n"
                f"  Response: {resp.raw[:400]}"
            )
        self._token = resp.data("accessToken")
        self.user_id = resp.data("platformUserId")
        self._expires_at = time.time() + float(resp.data("expiresIn", default=900) or 900)
        return self._token  # type: ignore[return-value]


SUPER = SuperAdmin()


def platform(method: str, path: str, body: Any = None) -> Response:
    return request(method, path, token=SUPER.token(), body=body)


def raw_login(email: str, password: str, slug: str, totp_code: str | None = None) -> Response:
    body: dict[str, Any] = {"email": email, "password": password, "tenantSlug": slug}
    if totp_code:
        body["totpCode"] = totp_code
    return request("POST", "/api/v1/auth/login", body=body)


def change_token_from(resp: Response) -> str | None:
    for detail in resp.get("error", "details", default=[]) or []:
        if isinstance(detail, dict) and detail.get("field") == "changeToken":
            return detail.get("issue")
    return None


def forced_change(change_token: str, current: str, new: str) -> Response:
    return request("POST", "/api/v1/auth/change-password/forced",
                   body={"changeToken": change_token, "currentPassword": current,
                         "newPassword": new})


def enrol_totp(email: str, password: str, slug: str, repair: bool = True) -> str | None:
    """
    Enrol a second factor over the PUBLIC bootstrap endpoints — 13-06's and 13-13's recipe,
    copied rather than reinvented.

    ORDER MATTERS and is not negotiable: the forced password change happens FIRST, enrolment
    second, so the factor is never bound under a temporary credential that whoever provisioned
    the account also knows.

    Returns None rather than aborting when enrolment genuinely cannot proceed, so ONE persona in
    an odd state does not take the other seventeen down with it. Measured: a run died outright on
    `409 TOTP_ALREADY_ENROLLED` for a single address and reported nothing about anybody else.

    That 409 beside a `401 TOTP_ENROLLMENT_REQUIRED` from login is not a contradiction — the two
    endpoints read different columns. Login demands enrolment when `totp_secret IS NULL`;
    bootstrap refuses when `totp_enabled` is true. An account with the flag set and no secret is
    stuck between them and can never log in again, because no endpoint at any tier resets another
    user's second factor. The repair clears the factor directly and re-enrols, and prints that
    write in the ledger.
    """
    resp = request("POST", "/api/v1/auth/2fa/bootstrap",
                   body={"email": email, "password": password, "tenantSlug": slug})

    if resp.status == 409 and "TOTP_ALREADY_ENROLLED" in resp.raw:
        if not repair:
            warn(f"{email}: already holds a factor this run has no secret for, and repair is off")
            return None
        warn(f"{email}: holds an enrolled factor this run has no secret for — clearing and re-enrolling")
        clear_totp(email)
        resp = request("POST", "/api/v1/auth/2fa/bootstrap",
                       body={"email": email, "password": password, "tenantSlug": slug})

    uri = resp.data("otpauthUri")
    if not uri:
        warn(f"TOTP bootstrap for {email} returned no otpauth uri (HTTP {resp.status}): {resp.raw[:200]}")
        return None
    secret = urllib.parse.parse_qs(urllib.parse.urlparse(uri).query)["secret"][0]
    verify = request("POST", "/api/v1/auth/2fa/bootstrap/verify",
                     body={"email": email, "password": password, "tenantSlug": slug,
                           "code": totp_now(secret)})
    if verify.status != 200:
        warn(f"TOTP enrolment for {email} was not accepted (HTTP {verify.status}): {verify.raw[:200]}")
        return None
    store_totp_secret(email, secret)
    return secret


def login(email: str, password: str, slug: str) -> tuple[str | None, str]:
    """
    Log a persona in, meeting whichever gates the platform raises, and return
    (access_token, note). A None token means the persona could not authenticate; the note
    always says why in terms a reader can act on.

    Both gates a provisioned or created account can meet are handled here, in the order
    13-08 pinned:  403 PASSWORD_CHANGE_REQUIRED  then  401 TOTP_ENROLLMENT_REQUIRED.
    """
    secret = load_totp_secret(email)
    resp = raw_login(email, password, slug, totp_now(secret) if secret else None)

    if resp.status == 200:
        return resp.data("accessToken"), "ok"

    if resp.status == 401 and resp.error_code == "TOTP_ENROLLMENT_REQUIRED":
        enrol_totp(email, password, slug)
        secret = load_totp_secret(email)
        resp = raw_login(email, password, slug, totp_now(secret) if secret else None)
        if resp.status == 200:
            return resp.data("accessToken"), "ok (enrolled a second factor)"
        return None, f"still refused after TOTP enrolment: {resp.status} {resp.error_code}"

    if resp.status == 401 and resp.error_code == "TOTP_REQUIRED":
        if not secret:
            # The factor is enrolled and this run holds no secret for it. The secret is minted by
            # auth-service and cannot be re-derived, and no endpoint at any tier revokes another
            # user's second factor — so the only way back is to clear it and enrol again, which is
            # an enumerated direct write rather than a silent one.
            if enrol_totp(email, password, slug):
                secret = load_totp_secret(email)
                resp = raw_login(email, password, slug, totp_now(secret) if secret else None)
                if resp.status == 200:
                    return resp.data("accessToken"), "ok (factor re-enrolled)"
            return None, (
                "requires a TOTP code and this run holds no secret for it, and re-enrolment did "
                f"not succeed. Secrets live in {TOTP_DIR}; losing that directory is recoverable "
                "but not free."
            )
        # One clock-skew retry before calling it a failure.
        resp = raw_login(email, password, slug, totp_now(secret, skew=-1))
        if resp.status == 200:
            return resp.data("accessToken"), "ok (previous TOTP window)"
        return None, f"TOTP code refused: {resp.status} {resp.error_code}"

    if resp.status == 403 and resp.error_code == "PASSWORD_CHANGE_REQUIRED":
        return None, "still carries an outstanding forced-change flag"

    return None, f"{resp.status} {resp.error_code or resp.raw[:120]}"


# ════════════════════════════════════════════════════════════════════════════════════════════
# PHASE 1 — the platform and three deliberately divergent tenants
# ════════════════════════════════════════════════════════════════════════════════════════════

@dataclass
class Tenant:
    key: str
    brand: str
    tier: str
    tenant_id: str = ""
    slug: str = ""
    admin_email: str = ""
    admin_temp_password: str | None = None
    hq_branch_id: str = ""
    branch_ids: list[str] = field(default_factory=list)
    features: dict[str, bool] = field(default_factory=dict)
    spec: dict[str, Any] = field(default_factory=dict)


def find_tenant_by_brand(brand: str) -> dict[str, Any] | None:
    resp = expect(platform("GET", "/api/v1/platform/tenants?page=0&size=200"), 200,
                  what="listing platform tenants")
    rows = resp.data(default=[]) or []
    if isinstance(rows, dict):
        rows = rows.get("content") or rows.get("items") or []
    for row in rows:
        if isinstance(row, dict) and row.get("brandName") == brand:
            return row
    return None


def read_features(tenant_id: str) -> dict[str, bool]:
    resp = expect(platform("GET", f"/api/v1/platform/tenants/{tenant_id}/features"), 200,
                  what="reading tenant features")
    raw = resp.data("features", default=None)
    if raw is None:
        raw = resp.data(default={})
    if isinstance(raw, dict):
        return {k: bool(v) for k, v in raw.items()}
    out: dict[str, bool] = {}
    for row in raw or []:
        if isinstance(row, dict):
            code = row.get("featureCode") or row.get("code")
            if code:
                out[code] = bool(row.get("enabled", row.get("isEnabled")))
    return out


def phase_platform() -> list[Tenant]:
    banner("PHASE 1 — the platform, and three deliberately divergent tenants")

    step(f"verifying the SuperAdmin by LOGGING IN as {SUPERADMIN_EMAIL} (not by inserting it)")
    claims = jwt_claims(SUPER.token())
    if "SUPER_ADMIN" not in (claims.get("roles") or []):
        die(f"the SuperAdmin token does not carry the SUPER_ADMIN role: {claims.get('roles')}")
    ok(f"SuperAdmin authenticated through the real gateway — platformUserId {SUPER.user_id}")

    tenants: list[Tenant] = []
    for spec in TENANTS:
        t = Tenant(key=spec["key"], brand=spec["brand"], tier=spec["tier"], spec=spec)
        t.admin_email = persona_email(t.key, "owner")

        existing = find_tenant_by_brand(t.brand)
        if existing:
            t.tenant_id = existing["id"] if "id" in existing else existing.get("tenantId", "")
            t.slug = existing.get("slug", "")
            step(f"{t.brand}: already provisioned as '{t.slug}' — reconciling, not duplicating")
            if (existing.get("tier") or "").upper() != t.tier:
                resp = platform("POST", f"/api/v1/platform/tenants/{t.tenant_id}/tier",
                                body={"tier": t.tier, "force": True})
                expect(resp, 200, what=f"setting {t.brand} to tier {t.tier}")
                ok(f"{t.brand}: tier reconciled to {t.tier}")
        else:
            step(f"{t.brand}: provisioning through POST /api/v1/platform/tenants (tier {t.tier})")
            resp = platform("POST", "/api/v1/platform/tenants",
                            body={"brandName": t.brand, "adminEmail": t.admin_email, "tier": t.tier})
            expect(resp, 201, 200, what=f"provisioning {t.brand}")
            t.tenant_id = resp.data("tenantId")
            t.slug = resp.data("slug")
            t.admin_temp_password = resp.data("tempPassword")
            ok(f"{t.brand}: tenant {t.slug} provisioned, admin {t.admin_email}")

        if not t.tenant_id or not t.slug:
            die(f"{t.brand}: could not establish a tenant id and slug")

        # Diverge the module sets DELIBERATELY, on top of the tier difference.
        for code, enabled in spec["overrides"]:
            resp = platform("PATCH", f"/api/v1/platform/tenants/{t.tenant_id}/features/{code}",
                            body={"enabled": enabled})
            expect(resp, 200, what=f"setting {code}={enabled} on {t.brand}")
            ok(f"{t.brand}: {code} forced {'ON' if enabled else 'OFF'} (an explicit override, not a tier default)")

        t.features = read_features(t.tenant_id)
        enabled = sorted(c for c, v in t.features.items() if v)
        step(f"{t.brand} [{t.tier}] enables {len(enabled)} features: {', '.join(enabled)}")
        tenants.append(t)

    # ASSERT the divergence rather than trusting the calls succeeded. Three tenants whose
    # enabled sets are equal would mean feature gating is assumed, which is the exact thing
    # 13-CONTEXT says must not happen.
    sets = {t.key: frozenset(c for c, v in t.features.items() if v) for t in tenants}
    keys = list(sets)
    for i in range(len(keys)):
        for j in range(i + 1, len(keys)):
            a, b = keys[i], keys[j]
            if sets[a] == sets[b]:
                die(
                    f"tenants '{a}' and '{b}' ended with IDENTICAL enabled module sets. "
                    f"Feature gating would be assumed rather than exercised, which is the "
                    f"prohibition this phase exists to close."
                )
    ok(f"all {len(TENANTS)} enabled module sets are pairwise DIFFERENT — asserted, not assumed")
    for i in range(len(keys)):
        for j in range(i + 1, len(keys)):
            a, b = keys[i], keys[j]
            only_a = sorted(sets[a] - sets[b])
            only_b = sorted(sets[b] - sets[a])
            print(f"     {a} ⊖ {b}: only {a} = {only_a or '—'} ; only {b} = {only_b or '—'}")

    return tenants


# ════════════════════════════════════════════════════════════════════════════════════════════
# PHASE 2 — six personas per tenant, activated through the real forced-change flow
# ════════════════════════════════════════════════════════════════════════════════════════════

def admin_reset(target_user_id: str, admin_token: str, reason: str) -> str | None:
    """
    13-13's tenant-tier administrator reset — the ONLY working way to set a user's password,
    because self-service delivery ships disabled (13-09 / D-31: notification-service has zero
    source files, so no email can be sent). `reason` is MANDATORY; the endpoint answers 400
    without it.
    """
    resp = request("POST", f"/api/v1/users/{target_user_id}/reset-password",
                   token=admin_token, body={"reason": reason})
    if resp.status != 200:
        return None
    return resp.data("tempPassword")


def clear_reuse_history(email: str) -> None:
    """
    RECOVERY ONLY. `PasswordPolicyService.HISTORY_DEPTH` is 5, so a persona that has already
    held its documented password cannot be returned to it by a reset + forced change — the
    change is correctly refused PASSWORD_REUSE. Nothing in the platform can rescind password
    history and nothing should: the rule exists to stop a HUMAN cycling back to a password
    they have used before, and this is a development seed converging on a DOCUMENTED
    credential, which is a different thing entirely.
    """
    record_direct_write(
        what=f"deleted password history rows for {email} (recovery path only)",
        service="auth-service",
        table="auth_db.password_history",
        reason=(
            "no API can rescind password history, and none should — the reuse rule is a control "
            "on human password choice. Reached only when a persona has to be returned to its "
            "DOCUMENTED credential after an out-of-band change, which the reuse rule correctly "
            "refuses."
        ),
        replacement=(
            "nothing. This is not a missing endpoint; it is a deliberate rule the seed has to "
            "step around exactly once, and only on a repair."
        ),
    )
    tid = tenant_id_for_email(email)
    sql("auth_db", f"""
        SET app.current_tenant_id = '{tid}';
        DELETE FROM password_history WHERE user_id IN (SELECT id FROM users WHERE email = '{email}');
    """.strip())


def clear_totp(email: str) -> None:
    """
    RECOVERY ONLY. A TOTP secret is minted by auth-service at enrolment and is not derivable;
    if this script's state directory is lost, the persona holding it can never be logged in
    again. There is NO endpoint anywhere in the platform that resets another user's second
    factor — 13-13's admin reset deliberately does not, and it is right not to: a reset
    replaces one factor, not both.
    """
    record_direct_write(
        what=f"cleared the enrolled TOTP factor for {email} (recovery path only)",
        service="auth-service",
        table="auth_db.users.totp_secret / totp_enabled",
        reason=(
            "no endpoint at any tier resets another user's second factor. 13-13's administrator "
            "reset deliberately leaves TOTP intact, which is correct — a password reset replaces "
            "one factor, not both."
        ),
        replacement=(
            "an admin-initiated 'revoke second factor' endpoint beside "
            "POST /api/v1/users/{userId}/reset-password, gated the same way and audited the same way."
        ),
    )
    tid = tenant_id_for_email(email)
    sql("auth_db", f"""
        SET app.current_tenant_id = '{tid}';
        UPDATE users SET totp_secret = NULL, totp_enabled = false WHERE email = '{email}';
    """.strip())
    p = totp_secret_path(email)
    if p.is_file():
        p.unlink()


def find_user(admin_token: str, email: str) -> dict[str, Any] | None:
    resp = request("GET", f"/api/v1/users?page=0&size=200&search={urllib.parse.quote(email)}",
                   token=admin_token)
    if resp.status != 200:
        return None
    for row in resp.data(default=[]) or []:
        if isinstance(row, dict) and (row.get("email") or "").lower() == email.lower():
            return row
    return None


def activate_persona(email: str, temp_password: str, final_password: str, slug: str) -> None:
    """
    Walk the real forced-change flow: login -> 403 PASSWORD_CHANGE_REQUIRED carrying a
    single-use change token -> POST /api/v1/auth/change-password/forced.

    The token has a ten-minute TTL and a WRONG CURRENT PASSWORD SPENDS IT (13-08), so the
    current password passed here is always the one the API just handed back, never a guess.
    """
    refusal = raw_login(email, temp_password, slug)
    if refusal.status == 200:
        return  # already usable; nothing to change
    token = change_token_from(refusal)
    if not token:
        die(
            f"{email}: expected a 403 PASSWORD_CHANGE_REQUIRED carrying a change token, got "
            f"{refusal.status} {refusal.error_code}. {refusal.raw[:300]}"
        )
    resp = forced_change(token, temp_password, final_password)
    if resp.status != 200:
        die(f"{email}: the forced password change was refused ({resp.status}): {resp.raw[:300]}")


def ensure_persona_usable(
    email: str, final_password: str, slug: str, temp_password: str | None,
    owner_token_for_repair: Callable[[], str | None], user_id: str | None, repair: bool,
) -> tuple[str | None, str]:
    """
    Converge one persona on its documented working password, and leave NO persona holding a
    temporary one.

    Order of attempts, cheapest and least destructive first:
      1. the temporary password we were just handed  -> forced change  -> documented password
      2. the documented password directly            (the ordinary second-run case)
      3. repair: administrator reset -> forced change -> documented password
    """
    if temp_password:
        activate_persona(email, temp_password, final_password, slug)

    token, note = login(email, final_password, slug)
    if token:
        return token, note

    if not repair:
        return None, note

    # --- repair ---------------------------------------------------------------------------
    admin_token = owner_token_for_repair()
    if not admin_token or not user_id:
        return None, note + " (no administrator token available to repair it)"

    if "TOTP" in note or "second factor" in note:
        warn(f"{email}: {note} — clearing and re-enrolling the factor")
        clear_totp(email)
        token, note = login(email, final_password, slug)
        if token:
            return token, note + " (factor re-enrolled)"

    warn(f"{email}: {note} — repairing through the administrator reset endpoint")
    temp = admin_reset(user_id, admin_token, reason="seed reconciliation: converge on the documented development credential")
    if not temp:
        return None, note + " (the administrator reset was refused)"
    resp = raw_login(email, temp, slug)
    change = change_token_from(resp)
    if not change:
        return None, note + " (no change token after the administrator reset)"
    changed = forced_change(change, temp, final_password)
    if changed.status != 200 and "REUSE" in (changed.error_code or "") + changed.raw:
        clear_reuse_history(email)
        temp = admin_reset(user_id, admin_token, reason="seed reconciliation after clearing reuse history")
        resp = raw_login(email, temp or "", slug)
        change = change_token_from(resp)
        if change:
            changed = forced_change(change, temp or "", final_password)
    if changed.status != 200:
        return None, note + f" (the repair's forced change was refused: {changed.status})"
    return login(email, final_password, slug)


def phase_personas(tenants: list[Tenant], repair: bool = True) -> dict[str, str]:
    banner("PHASE 2 — six personas per tenant, activated through the real forced-change flow")

    tokens: dict[str, str] = {}

    for t in tenants:
        print()
        print(f"  {_BOLD}{t.brand} ({t.slug}){_RESET}")

        # ── the provisioned OWNER first: it is the only route to a usable administrator ────
        owner_email = t.admin_email
        owner_password = persona_password(t.key, "owner")
        owner_token, note = ensure_persona_usable(
            owner_email, owner_password, t.slug, t.admin_temp_password,
            owner_token_for_repair=lambda: None, user_id=None, repair=False,
        )
        if not owner_token and repair:
            # Recover a stranded OWNER through the PLATFORM tier — the one case no tenant can
            # resolve for itself, which is precisely why 13-13's platform reset exists.
            uid = sql("auth_db", f"SET app.current_tenant_id = '{t.tenant_id}'; "
                                 f"SELECT id FROM users WHERE email = '{owner_email}';")
            if uid:
                warn(f"{owner_email}: {note} — repairing through the PLATFORM reset endpoint")
                resp = platform("POST",
                                f"/api/v1/platform/tenants/{t.tenant_id}/users/{uid}/reset-password",
                                body={"reason": "seed reconciliation: the tenant OWNER could not be authenticated"})
                if resp.status == 200:
                    temp = resp.data("tempPassword")
                    refusal = raw_login(owner_email, temp, t.slug)
                    change = change_token_from(refusal)
                    if change:
                        res = forced_change(change, temp, owner_password)
                        if res.status != 200 and "REUSE" in res.raw:
                            clear_reuse_history(owner_email)
                            resp = platform("POST",
                                            f"/api/v1/platform/tenants/{t.tenant_id}/users/{uid}/reset-password",
                                            body={"reason": "seed reconciliation after clearing reuse history"})
                            temp = resp.data("tempPassword")
                            refusal = raw_login(owner_email, temp, t.slug)
                            change = change_token_from(refusal)
                            if change:
                                forced_change(change, temp, owner_password)
                    owner_token, note = login(owner_email, owner_password, t.slug)
                    if not owner_token and ("TOTP" in note):
                        clear_totp(owner_email)
                        owner_token, note = login(owner_email, owner_password, t.slug)

        if not owner_token:
            die(f"{owner_email}: the tenant OWNER cannot be authenticated ({note}). "
                f"Every other persona in this tenant is created BY that owner, so there is "
                f"nothing further this script can honestly do for '{t.slug}'.")

        tokens[owner_email] = owner_token
        claims = jwt_claims(owner_token)
        ok(f"{owner_email}: OWNER, {len(claims.get('permissions', []))} permissions, "
           f"step-up {'enrolled' if load_totp_secret(owner_email) else 'not required'} — {note}")

        # ── the role catalog, READ rather than hardcoded ───────────────────────────────────
        cat = request("GET", "/api/v1/roles", token=owner_token)
        expect(cat, 200, what=f"reading the role catalog as {owner_email}")
        catalog_rows = cat.data(default=[]) or []
        catalog = {r.get("code") for r in catalog_rows if isinstance(r, dict)}
        withheld = [w for w in (cat.get("warnings", default=[]) or [])]
        wanted = {p["role"] for p in PERSONAS if not p["provisioned"]}
        missing = sorted(wanted - catalog)
        if missing:
            die(
                f"the role catalog at GET /api/v1/roles does not offer {missing} to {owner_email}.\n"
                f"  It offers: {sorted(catalog)}\n"
                f"  This disagreement is a genuine defect and is NOT swallowed: a seeded role code\n"
                f"  the catalog does not know silently yields a permissionless login, which is the\n"
                f"  exact class of failure this phase exists to close. Fix the catalog or the seed's\n"
                f"  expectations — do not proceed with a role code nothing validated."
            )
        ok(f"role catalog agrees on {sorted(wanted)}"
           + (f" (with {len(withheld)} ceiling warning(s))" if withheld else ""))

        # ── branches ──────────────────────────────────────────────────────────────────────
        branches = expect(request("GET", "/api/v1/branches", token=owner_token), 200,
                          what="listing branches").data(default=[]) or []
        by_name = {b["name"]: b["id"] for b in branches if isinstance(b, dict)}
        hq = next((b for b in branches if isinstance(b, dict) and b.get("isHq")), None)
        if not hq:
            die(f"{t.slug}: no HQ branch. The provisioning saga must send isHq:true (D-07).")
        t.hq_branch_id = hq["id"]
        t.branch_ids = [t.hq_branch_id]

        # Provisioning saga creates the OWNER without approval_limit_paisa. Same fail-closed
        # OPA trap as the created personas — pin the documented OWNER limit onto the HQ row.
        owner_user = find_user(owner_token, owner_email)
        owner_limit = APPROVAL_LIMIT_BY_ROLE["OWNER"]
        if owner_user:
            ol = request(
                "POST", f"/api/v1/users/{owner_user['id']}/branch-roles", token=owner_token,
                body={"branchId": t.hq_branch_id, "roleCode": "OWNER",
                      "approvalLimitPaisa": owner_limit},
            )
            if ol.status in (200, 201):
                owner_token, note = ensure_persona_usable(
                    owner_email, owner_password, t.slug, None,
                    owner_token_for_repair=lambda: None, user_id=None, repair=False,
                )
                if owner_token:
                    tokens[owner_email] = owner_token
                    attrs = (jwt_claims(owner_token).get("attributes") or {})
                    if attrs.get("approval_limit_paisa") != owner_limit:
                        warn(f"{owner_email}: JWT still missing approval_limit_paisa after assign")
                    else:
                        ok(f"{owner_email}: approval_limit_paisa={owner_limit}")
            else:
                warn(f"{owner_email}: OWNER approval-limit assign answered {ol.status}")

        for extra in t.spec["extra_branches"]:
            if extra in by_name:
                t.branch_ids.append(by_name[extra])
                step(f"branch '{extra}' already exists")
                continue
            resp = request("POST", "/api/v1/branches", token=owner_token,
                           body={"name": extra, "isHq": False, "timezone": "Asia/Karachi"})
            expect(resp, 201, 200, what=f"creating branch '{extra}'")
            t.branch_ids.append(resp.data("id"))
            ok(f"branch '{extra}' created through POST /api/v1/branches")

        # ── the five created personas ─────────────────────────────────────────────────────
        for p in PERSONAS:
            if p["provisioned"]:
                continue
            email = persona_email(t.key, p["local"])
            password = persona_password(t.key, p["local"])
            existing = find_user(owner_token, email)
            temp = None
            if existing:
                user_id = existing["id"]
                step(f"{email}: already exists — reconciling")
            else:
                resp = request("POST", "/api/v1/users", token=owner_token, body={
                    "email": email,
                    "fullName": persona_full_name(t.key, p["local"]),
                    "locale": "en",
                    "branchId": t.hq_branch_id,
                    "roleCode": p["role"],
                })
                expect(resp, 201, 200, what=f"creating {email} as {p['role']}")
                user_id = resp.data("id")
                temp = resp.data("tempPassword")

            token, note = ensure_persona_usable(
                email, password, t.slug, temp,
                owner_token_for_repair=lambda tok=owner_token: tok,
                user_id=user_id, repair=repair,
            )
            if not token:
                die(f"{email}: could not be brought to its documented working password ({note}). "
                    f"A partial seed is a failed seed.")

            # CreateUserRequest has no approvalLimitPaisa field, so POST /users leaves the HQ
            # assignment NULL. OPA deny-by-default on missing approval_limit_paisa then makes
            # every vendor.po.approve / finance.expense.approve call return APPROVAL_LIMIT_EXCEEDED
            # even for tiny amounts. Re-assign the HQ role with the documented limit (idempotent).
            limit = APPROVAL_LIMIT_BY_ROLE.get(p["role"])
            if limit is not None:
                limit_resp = request(
                    "POST", f"/api/v1/users/{user_id}/branch-roles", token=owner_token,
                    body={"branchId": t.hq_branch_id, "roleCode": p["role"],
                          "approvalLimitPaisa": limit},
                )
                if limit_resp.status not in (200, 201):
                    warn(f"{email}: approval-limit assign answered {limit_resp.status} — "
                         f"{limit_resp.raw[:200]}")
                # Re-login so the JWT we cache carries attributes.approval_limit_paisa.
                token, note = ensure_persona_usable(
                    email, password, t.slug, None,
                    owner_token_for_repair=lambda tok=owner_token: tok,
                    user_id=user_id, repair=repair,
                )
                if not token:
                    die(f"{email}: re-login after approval-limit assign failed ({note})")

            tokens[email] = token
            claims = jwt_claims(token)
            got_roles = claims.get("roles") or []
            if p["role"] not in got_roles:
                die(f"{email}: the issued token carries roles {got_roles}, not {p['role']}. "
                    f"A role code that persists but does not resolve is the silent "
                    f"permissionless-login defect B3 is about.")
            attrs = claims.get("attributes") or {}
            if limit is not None and attrs.get("approval_limit_paisa") != limit:
                die(f"{email}: JWT attributes.approval_limit_paisa is {attrs.get('approval_limit_paisa')!r}, "
                    f"expected {limit}. OPA will deny every approval this persona attempts.")
            ok(f"{email}: {p['role']}, {len(claims.get('permissions', []))} permissions — {note}")

        # ── one persona at BOTH branches, so the one-active-role-per-branch rule (13-02) is
        #    exercised across two branches rather than assumed ──────────────────────────────
        if len(t.branch_ids) > 1:
            mgr_email = persona_email(t.key, "manager")
            mgr = find_user(owner_token, mgr_email)
            if mgr:
                mgr_limit = APPROVAL_LIMIT_BY_ROLE["MANAGER"]
                resp = request("POST", f"/api/v1/users/{mgr['id']}/branch-roles", token=owner_token,
                               body={"branchId": t.branch_ids[1], "roleCode": "MANAGER",
                                     "approvalLimitPaisa": mgr_limit})
                if resp.status in (200, 201):
                    ok(f"{mgr_email} now holds MANAGER at BOTH branches "
                       f"(displaced: {resp.data('displacedRoleCode', default=None)}; "
                       f"limit={mgr_limit})")
                else:
                    warn(f"{mgr_email}: second-branch assignment answered {resp.status} — {resp.raw[:200]}")

    return tokens


# ════════════════════════════════════════════════════════════════════════════════════════════
# PHASE 3 — business data, driven by the persona whose permissions actually cover it
# ════════════════════════════════════════════════════════════════════════════════════════════

def det(*parts: str) -> str:
    """
    A deterministic uuid5 over a stable name — the idempotency mechanism onboarding.py uses.

    Every caller passes the TENANT ID as the first part, never the tenant key. That is not
    decoration: `OrderServiceImpl.createOrder` is idempotent on `clientOrderId` and
    `findByClientOrderId` carries no tenant predicate, so a client order id derived from a
    stable KEY is answered by whichever tenant used it first — including one that has since
    been deleted. Measured here: a freshly provisioned Saffron Grill was handed back a
    previous Saffron Grill's order, and every read of it then 404'd against the new branch.
    """
    return str(uuid.uuid5(UUID_NS, "restaurantos/seed/" + "/".join(parts)))


MENU = [
    ("Starters", [("Chicken Samosa", 25000, 16.0), ("Seekh Kebab", 45000, 16.0)]),
    ("Mains", [("Chicken Karahi", 145000, 16.0), ("Mutton Biryani", 125000, 16.0),
               ("Butter Naan", 8000, 16.0)]),
    ("Drinks", [("Fresh Lime", 22000, 16.0)]),
]


def seed_menu(t: Tenant, manager_token: str) -> list[str]:
    """
    Menu categories and items, created by the MANAGER — the role that holds pos.menu.manage.
    An owner-driven seed proves nothing about the other five roles.

    🔴 THE LOOKUP IS DELIBERATELY NOT BY NAME, and the reason is a live defect this script
    found. `GET /api/v1/pos/menu/items/admin` and `.../categories/admin` return EVERY TENANT'S
    rows: `MenuItemRepository`'s queries carry no tenant predicate and rely entirely on row-level
    security, but `pos_db.menu_items` is `relrowsecurity=t, relforcerowsecurity=f` and the
    runtime connects as `pos_user`, which OWNS the table — so the policy does not apply to it.

    Measured, not inferred: the Saffron manager (tenant 4f2783b6…) sees 13 items of which 2 are
    its own, including another tenant's "Beef Nihari".

    A name-keyed reconciliation against that list adopts a NEIGHBOUR'S menu item id, and the
    order priced from it is then rejected — which is exactly how this run found the defect.
    Every lookup here is therefore keyed on a description this script writes and that contains
    the tenant's brand, so a collision across tenants is impossible. The defect itself is
    pos-service's and is recorded in the phase's deferred items; it is NOT worked around
    silently.
    """
    wanted = t.spec["menu_items"]
    item_ids: list[str] = []

    def mine(rows: Iterable[Any], marker: str) -> dict[str, str]:
        out: dict[str, str] = {}
        for row in rows or []:
            if isinstance(row, dict) and (row.get("description") or "").endswith(marker):
                out[row.get("name") or ""] = row["id"]
        return out

    # The marker carries the TENANT ID, not just the brand. A brand is stable across a delete
    # and re-provision, and nothing purges pos_db when a tenant goes away (tenant deletion is a
    # status flip — 13-CONTEXT's deferred list), so a brand-only marker adopts a dead tenant's
    # rows. The display NAME is left clean; only the description carries it.
    marker = f"— {t.brand} · tenant {t.tenant_id[:8]}"
    cats = request("GET", "/api/v1/pos/menu/categories/admin", token=manager_token)
    own_categories = mine(cats.data(default=[]) if cats.status == 200 else [], marker)
    items = request("GET", "/api/v1/pos/menu/items/admin", token=manager_token)
    own_items = mine(items.data(default=[]) if items.status == 200 else [], marker)

    for order, (cat_name, entries) in enumerate(MENU):
        if len(item_ids) >= wanted:
            break
        cat_id = own_categories.get(cat_name)
        if not cat_id:
            resp = request("POST", "/api/v1/pos/menu/categories", token=manager_token,
                           body={"name": cat_name, "description": f"{cat_name} {marker}",
                                 "sortOrder": order})
            if resp.status not in (200, 201):
                warn(f"{t.slug}: menu category '{cat_name}' answered {resp.status} — {resp.raw[:180]}")
                continue
            cat_id = resp.data("id")
            own_categories[cat_name] = cat_id
        for name, price, tax in entries:
            if len(item_ids) >= wanted:
                break
            if name in own_items:
                item_ids.append(own_items[name])
                continue
            resp = request("POST", "/api/v1/pos/menu/items", token=manager_token,
                           body={"categoryId": cat_id, "name": name,
                                 "description": f"{name} {marker}",
                                 "basePricePaisa": price, "taxRatePct": tax})
            if resp.status not in (200, 201):
                warn(f"{t.slug}: menu item '{name}' answered {resp.status} — {resp.raw[:180]}")
                continue
            item_ids.append(resp.data("id"))
    if item_ids:
        ok(f"{t.slug}: menu has {len(item_ids)} items across {len(own_categories)} categories "
           f"(created by the MANAGER, pos.menu.manage)")
    return item_ids


def seed_inventory(t: Tenant, manager_token: str, menu_item_ids: list[str]) -> int:
    """Ingredients and a recipe, so depletion has something to deplete. MANAGER holds
    inventory.item.manage."""
    made = 0
    # The standard unit set is PROVISIONED per tenant by inventory-service's own
    # UomProvisioningService (StandardUomCatalog: G/KG/MG/LB/OZ, ML/L/…, EACH/DOZEN/PAIR).
    # This script therefore READS the codes rather than inventing them — creating "kg" beside a
    # provisioned "KG" would give the tenant two units for one thing, which is precisely the
    # duplicate-master-data problem the provisioning service exists to prevent.
    uoms = request("GET", "/api/v1/inventory/uom", token=manager_token)
    if uoms.status in (403, 503):
        GAPS.append(f"{t.slug}: inventory answered {uoms.status} for the MANAGER — no ingredients "
                    f"or recipes were seeded")
        return 0
    have_uom = {(u.get("code") or "").upper() for u in (uoms.data(default=[]) or [])
                if isinstance(u, dict)}
    stock_uom = "KG" if "KG" in have_uom else next(iter(sorted(have_uom)), None)
    if not stock_uom:
        GAPS.append(f"{t.slug}: the tenant has no units of measure — inventory-service's "
                    f"UomProvisioningService did not run for it")
        return 0

    cats = request("GET", "/api/v1/inventory/categories", token=manager_token)
    cat_id = None
    for row in (cats.data(default=[]) or []) if cats.status == 200 else []:
        if isinstance(row, dict) and row.get("name") == "Raw Materials":
            cat_id = row["id"]
    if not cat_id:
        r = request("POST", "/api/v1/inventory/categories", token=manager_token,
                    body={"name": "Raw Materials", "code": "RAW", "sortOrder": 1})
        if r.status in (200, 201):
            cat_id = r.data("id")
        else:
            GAPS.append(f"{t.slug}: inventory category create answered {r.status}")
            return 0

    existing = request("GET", "/api/v1/inventory/ingredients", token=manager_token)
    have = {i.get("sku") for i in (existing.data(default=[]) or []) if isinstance(i, dict)}
    ingredient_ids: list[str] = []
    for sku, name in (("CHK-001", "Chicken"), ("RIC-001", "Basmati Rice"), ("SPC-001", "Spice Mix")):
        if sku in have:
            for i in existing.data(default=[]) or []:
                if isinstance(i, dict) and i.get("sku") == sku:
                    ingredient_ids.append(i["id"])
            continue
        r = request("POST", "/api/v1/inventory/ingredients", token=manager_token,
                    body={"name": name, "sku": sku, "baseUomCode": stock_uom, "categoryId": cat_id,
                          "reorderPoint": 5, "parLevel": 25, "perishable": True,
                          "shelfLifeDays": 7})
        if r.status in (200, 201):
            ingredient_ids.append(r.data("id"))
            made += 1
        else:
            warn(f"{t.slug}: ingredient '{sku}' answered {r.status} — {r.raw[:160]}")

    if ingredient_ids and menu_item_ids:
        # inventory-service holds its own PROJECTION of the POS menu, fed by an event. A menu
        # item created moments ago is not there yet, and a recipe against it answers 404
        # MENU_ITEM_NOT_FOUND. That is eventual consistency working correctly, not a defect —
        # so this waits for the projection instead of reporting a false gap.
        r = None
        for _ in range(10):
            r = request("POST", "/api/v1/inventory/recipes", token=manager_token,
                        body={"menuItemId": menu_item_ids[0], "yieldServings": 1,
                              "name": "Seed recipe",
                              "lines": [{"ingredientId": ingredient_ids[0], "qty": 0.25,
                                         "uomCode": stock_uom, "yieldPct": 100}]})
            if r.status != 404:
                break
            time.sleep(2)
        if r is not None and r.status in (200, 201):
            ok(f"{t.slug}: {len(ingredient_ids)} ingredients and a recipe "
               f"(depletion has something to deplete)")
        else:
            GAPS.append(f"{t.slug}: recipe create answered {r.status} ({r.error_code}) after "
                        f"waiting for the menu projection — the ingredient set is seeded, "
                        f"the recipe is not")
    elif ingredient_ids:
        ok(f"{t.slug}: {len(ingredient_ids)} ingredients")
    return made


def seed_purchasing(t: Tenant, manager_token: str) -> int:
    """Vendor -> PO -> approve -> send -> goods receipt -> invoice, by the MANAGER (vendor.*).

    Invoice dates are spread over several BUSINESS DATES through the real API field, which is
    how period-scoped purchase reporting gets more than one day in it without any direct write:
    `invoiceDate` is a request field, so no back-dating is needed anywhere."""
    vendor_name = f"{t.brand} Supplies"
    # 🔴 `GET /api/v1/purchasing/vendors` returns EVERY TENANT'S vendors, for the same reason
    # the POS menu listing does: `purchasing_db.vendors` is `relrowsecurity=t
    # relforcerowsecurity=f` and the runtime connects as `purchasing_user`, which OWNS the
    # table, so the policy never applies to it. The write path IS tenant-scoped, so adopting a
    # neighbour's vendor id produces `404 Vendor not found` on the very next call — which is
    # how this run found it. The reconciliation key is therefore a `notes` marker carrying this
    # tenant's id, which no other tenant's row can carry.
    marker = f"seed:{t.tenant_id}"
    listed = request("GET", "/api/v1/purchasing/vendors", token=manager_token)
    if listed.status in (403, 404, 503):
        GAPS.append(f"{t.slug}: purchasing answered {listed.status} for the MANAGER — "
                    f"no vendor, purchase order or goods receipt was seeded")
        return 0
    vendor_id = None
    rows = listed.data(default=[]) or []
    if isinstance(rows, dict):
        rows = rows.get("content") or []
    for row in rows:
        if isinstance(row, dict) and (row.get("notes") or "") == marker:
            vendor_id = row["id"]
    if not vendor_id:
        r = request("POST", "/api/v1/purchasing/vendors", token=manager_token,
                    body={"name": vendor_name, "paymentTerms": "NET_30", "notes": marker,
                          "ntn": "1234567-8", "strn": "12-34-5678-901-23"})
        if r.status not in (200, 201):
            GAPS.append(f"{t.slug}: vendor create answered {r.status} — {r.raw[:160]}")
            return 0
        vendor_id = r.data("id")

    import datetime as _dt
    today = _dt.date.today()
    made = 0
    for n in range(t.spec["invoices"]):
        # Tenant-qualified for the same reason every other key here is: a vendor invoice number
        # collides across a delete-and-reprovision otherwise.
        invoice_no = f"SEED-{t.key.upper()}-{t.tenant_id[:8].upper()}-{n + 1}"
        invoice_date = today - _dt.timedelta(days=n * 3)
        ingredient = det(t.tenant_id, "po-ingredient", str(n))
        qty, unit = 10 + n * 5, 100000
        po = request("POST", "/api/v1/purchasing/purchase-orders", token=manager_token,
                     body={"vendorId": vendor_id, "branchId": t.hq_branch_id,
                           "notes": f"seed {invoice_no}",
                           "lines": [{"ingredientId": ingredient, "qty": qty, "uom": "kg",
                                      "unitPricePaisa": unit}]})
        if po.status not in (200, 201):
            if po.status == 409:
                made += 1  # already there from a previous run
                continue
            warn(f"{t.slug}: purchase order {invoice_no} answered {po.status} — {po.raw[:160]}")
            continue
        po_id, line_id = po.data("id"), (po.data("lines", default=[{}]) or [{}])[0].get("id")
        for verb, body in (("submit", None), ("approve", {}), ("send", None)):
            request("POST", f"/api/v1/purchasing/purchase-orders/{po_id}/{verb}",
                    token=manager_token, body=body)
        request("POST", f"/api/v1/purchasing/purchase-orders/{po_id}/mock-receive",
                token=manager_token, body={"lines": [{"poLineId": line_id, "receivedQty": qty}]})
        inv = request("POST", "/api/v1/purchasing/invoices", token=manager_token,
                      body={"purchaseOrderId": po_id, "invoiceNo": invoice_no,
                            "invoiceDate": invoice_date.isoformat(),
                            "inputTaxPaisa": 1500 * (n + 1),
                            "lines": [{"poLineId": line_id, "qty": qty, "unitPricePaisa": unit}]})
        if inv.status in (200, 201):
            made += 1
        elif inv.status == 409:
            made += 1
        else:
            warn(f"{t.slug}: invoice {invoice_no} answered {inv.status} — {inv.raw[:160]}")
    if made:
        ok(f"{t.slug}: {made} vendor invoice(s) matched through PO → approve → send → GRN → invoice, "
           f"dated across {t.spec['invoices']} business date(s)")
    return made


def seed_pos(t: Tenant, waiter_token: str, cashier_token: str, menu_item_ids: list[str]) -> int:
    """
    The point of D-30, driven exactly as the roles intend it:

      the WAITER  creates the order, adds lines, fires it to the KDS and serves — with NO till,
                  because a waiter cannot open one and that is the whole point;
      the CASHIER settles it. A CASH tender requires the PAYING user to hold an OPEN till, so
                  the cashier opens one first. A CARD tender needs none, and some orders are
                  settled that way deliberately so the exemption is exercised too.
    """
    if not menu_item_ids:
        GAPS.append(f"{t.slug}: no menu items, so no point-of-sale orders were seeded")
        return 0

    # The cashier's own open session, asked for the way the active-till bar asks: no branchId,
    # status filtered at the producer. Passing branchId switches this endpoint to the paginated
    # admin history instead, which is a different question and answered a different way.
    till = request("GET", "/api/v1/pos/tills?status=OPEN", token=cashier_token)
    rows = (till.data(default=[]) or []) if till.status == 200 else []
    if isinstance(rows, dict):
        rows = rows.get("content") or []
    open_till = next((r["id"] for r in rows
                      if isinstance(r, dict) and (r.get("status") or "OPEN") == "OPEN"), None)
    if open_till:
        step(f"{t.slug}: the CASHIER already holds an open till")
    else:
        r = request("POST", "/api/v1/pos/tills", token=cashier_token,
                    body={"branchId": t.hq_branch_id, "openingFloatPaisa": 500000})
        if r.status in (200, 201):
            open_till = r.data("id")
            ok(f"{t.slug}: the CASHIER opened a till "
               f"(a CASH settlement is 409 NO_OPEN_TILL without one — D-30)")
        elif r.status == 409 and "TILL_ALREADY_OPEN" in r.raw:
            open_till = "already-open"
            step(f"{t.slug}: the CASHIER already holds an open till")
        else:
            warn(f"{t.slug}: the cashier could not open a till ({r.status}) — "
                 f"cash settlements will be refused: {r.raw[:180]}")

    closed = 0
    for n in range(t.spec["orders"]):
        client_order_id = det(t.tenant_id, "order", str(n))
        created = request("POST", "/api/v1/pos/orders", token=waiter_token,
                          body={"branchId": t.hq_branch_id, "clientOrderId": client_order_id,
                                "type": "DINE_IN", "coverCount": 2 + (n % 3)})
        if created.status not in (200, 201):
            warn(f"{t.slug}: order {n} create answered {created.status} — {created.raw[:180]}")
            continue
        order_id = created.data("id")
        # createOrder is IDEMPOTENT on clientOrderId (OrderServiceImpl:145), and clientOrderId is
        # a uuid5 over a stable name — so a second run gets the same order back rather than a
        # second one. Lines are added only when it has none, or a re-run would keep growing it.
        already_built = bool(created.data("items", default=[]) or [])

        for k in range(0 if already_built else 1 + (n % 2)):
            item = menu_item_ids[(n + k) % len(menu_item_ids)]
            added = request("POST", f"/api/v1/pos/orders/{order_id}/items", token=waiter_token,
                            body={"menuItemId": item, "branchId": t.hq_branch_id,
                                  "quantity": 1 + (k % 2)})
            if added.status not in (200, 201):
                # Checked rather than fired and forgotten: an unchecked add is how a run reports
                # "order has a zero total" and leaves the reader guessing which call failed.
                warn(f"{t.slug}: order {n} line {k} answered {added.status} — {added.raw[:180]}")
        if not already_built:
            request("POST", f"/api/v1/pos/orders/{order_id}/send-to-kds", token=waiter_token)

        # `branchId` is a REQUIRED query parameter on the single-order read. Omitting it is a
        # 400, and a 400 read is how a run reports "the order has a zero total" and blames the
        # settlement for a defect in the fetch — which is exactly what happened here once.
        one = f"/api/v1/pos/orders/{order_id}?branchId={t.hq_branch_id}"
        current = request("GET", one, token=waiter_token)
        if current.status != 200:
            warn(f"{t.slug}: order {n} could not be read back ({current.status}) — {current.raw[:180]}")
            continue
        for lineitem in current.data("items", default=[]) or []:
            served = request("POST", f"/api/v1/pos/orders/{order_id}/items/{lineitem['id']}/serve",
                             token=waiter_token)
            if served.status not in (200, 201, 409):
                warn(f"{t.slug}: order {n} serve answered {served.status} — {served.raw[:160]}")

        settled = request("GET", one, token=cashier_token)
        total = int(settled.data("totalPaisa", default=0) or 0)
        # An order a previous run already settled comes back CLOSED. `OrderDto` carries no
        # amountPaidPaisa — that field is on the SUMMARY projection — so the status is what says
        # "already settled"; asking for a tender again is a 409 STATE_INVALID, which is the API
        # being right and the seed being wrong.
        if (settled.data("status") or "") == "CLOSED":
            closed += 1
            continue
        if total <= 0:
            warn(f"{t.slug}: order {n} has a zero total — not settling it")
            continue
        # An order auto-closes once it is fully PAID and fully SERVED; POST /{id}/close is
        # retired to 410 Gone (POS-23) and is deliberately not called.
        method = "CARD" if n % 3 == 2 else "CASH"
        pay = request("POST", f"/api/v1/pos/orders/{order_id}/payments", token=cashier_token,
                      body={"method": method, "amountPaisa": total, "tenderedPaisa": total,
                            "referenceNo": f"SEED-{n}" if method == "CARD" else None})
        if pay.status in (200, 201):
            closed += 1
        elif pay.status == 409 and "NO_OPEN_TILL" in pay.raw:
            die(f"{t.slug}: a CASH settlement was refused 409 NO_OPEN_TILL. The cashier holds no "
                f"open till — that is D-30 working exactly as specified, and the seed's fault.")
        else:
            warn(f"{t.slug}: order {n} {method} payment answered {pay.status} — {pay.raw[:180]}")
    if closed:
        ok(f"{t.slug}: {closed} orders taken by the WAITER (no till) and settled by the CASHIER "
           f"across CASH and CARD tenders")
    return closed


def phase_business(tenants: list[Tenant], tokens: dict[str, str]) -> None:
    banner("PHASE 3 — catalog, purchasing and point-of-sale data, by the role that owns each")

    for t in tenants:
        print()
        print(f"  {_BOLD}{t.brand} ({t.slug}){_RESET}")
        mgr = tokens.get(persona_email(t.key, "manager"))
        waiter = tokens.get(persona_email(t.key, "waiter"))
        cashier = tokens.get(persona_email(t.key, "cashier"))
        if not (mgr and waiter and cashier):
            die(f"{t.slug}: phase 3 needs manager, waiter and cashier tokens from phase 2.")

        items = seed_menu(t, mgr)
        seed_inventory(t, mgr, items)
        seed_purchasing(t, mgr)
        seed_pos(t, waiter, cashier, items)

    # Non-emptiness, asserted for a ROLE-APPROPRIATE persona rather than for the owner.
    print()
    step("checking each tenant's dashboards and reports are non-empty for the right persona")
    import datetime as _dt
    frm = (_dt.date.today() - _dt.timedelta(days=30)).isoformat()
    to = _dt.date.today().isoformat()
    for t in tenants:
        acct = tokens.get(persona_email(t.key, "accountant"))
        mgr = tokens.get(persona_email(t.key, "manager"))
        coa = request("GET", "/api/v1/finance/accounts?page=0&size=5", token=acct)
        n_coa = len(coa.data(default=[]) or []) if coa.status == 200 else 0
        # `status` must be given explicitly: the default listing is the POS floor view, which
        # deliberately excludes CLOSED orders. Counting settled orders without it reports zero
        # for a tenant whose orders all settled — the opposite of what is being asked.
        orders = request("GET",
                         f"/api/v1/pos/orders?branchId={t.hq_branch_id}&status=CLOSED&size=100",
                         token=mgr)
        raw_orders = orders.data(default=[]) or []
        if isinstance(raw_orders, dict):
            raw_orders = raw_orders.get("content") or []
        n_orders = len(raw_orders)
        rep = request("POST", "/api/v1/reporting/reports/sales-by-day/run", token=acct,
                      body={"from": frm, "to": to, "branchId": t.hq_branch_id})
        n_rows = 0
        if rep.status == 200:
            payload = rep.data(default={}) or {}
            n_rows = (len(payload.get("rows") or payload.get("data") or [])
                      if isinstance(payload, dict) else len(payload))
        tiles = request("GET", f"/api/v1/reporting/dashboard/{t.hq_branch_id}/tiles", token=acct)
        n_tiles = len(tiles.data(default={}) or {}) if tiles.status == 200 else 0
        print(f"     {t.slug:<18} chart-of-accounts {n_coa:>3}   settled orders {n_orders:>3}   "
              f"sales-by-day rows {n_rows:>3}   dashboard tiles {n_tiles:>3} ({tiles.status})")
        if n_orders == 0:
            GAPS.append(f"{t.slug}: no SETTLED orders are visible to the MANAGER — "
                        f"dashboards and sales reports will be empty")
        if n_rows == 0:
            GAPS.append(f"{t.slug}: sales-by-day returned no rows for the last 30 days")


# ════════════════════════════════════════════════════════════════════════════════════════════
# PHASE 4 — the self-verification loop. THIS is the acceptance test for the whole phase.
# ════════════════════════════════════════════════════════════════════════════════════════════

def phase_verify(tenants: list[Tenant]) -> int:
    banner("PHASE 4 — VERIFICATION: every principal authenticates through the real gateway")
    print("  Not by inspecting the database for expected rows — a row is what a broken API")
    print("  leaves behind too. Every line below is a live login through ${GATEWAY}.")
    print()

    passed: list[str] = []
    failed: list[tuple[str, str]] = []

    def line(name: str, good: bool, detail: str) -> None:
        mark = f"{_GREEN}PASS{_RESET}" if good else f"{_RED}FAIL{_RESET}"
        print(f"  {mark}  {name:<34} {detail}")

    # ── the SuperAdmin ────────────────────────────────────────────────────────────────────
    resp = request("POST", "/api/v1/platform/auth/login",
                   body={"email": SUPERADMIN_EMAIL, "password": SUPERADMIN_PASSWORD})
    if resp.status == 200:
        claims = jwt_claims(resp.data("accessToken"))
        perms = claims.get("permissions") or []
        reach = request("GET", "/api/v1/platform/tenants?page=0&size=1",
                        token=resp.data("accessToken"))
        good = "SUPER_ADMIN" in (claims.get("roles") or []) and bool(perms) and reach.status != 403
        line(SUPERADMIN_EMAIL, good,
             f"roles={claims.get('roles')} permissions={len(perms)} "
             f"GET /api/v1/platform/tenants -> {reach.status}")
        (passed if good else failed).append(
            SUPERADMIN_EMAIL if good else (SUPERADMIN_EMAIL, "token or platform read was wrong"))  # type: ignore[arg-type]
    else:
        line(SUPERADMIN_EMAIL, False, f"login refused {resp.status} {resp.error_code}")
        failed.append((SUPERADMIN_EMAIL, f"login refused {resp.status} {resp.error_code}"))

    # ── all eighteen tenant personas ──────────────────────────────────────────────────────
    for t in tenants:
        print(f"  {_DIM}--- {t.brand} ({t.slug}) ---{_RESET}")
        for p in PERSONAS:
            email = persona_email(t.key, p["local"])
            password = persona_password(t.key, p["local"])
            token, note = login(email, password, t.slug)
            if not token:
                line(email, False, note)
                failed.append((email, note))
                continue
            claims = jwt_claims(token)
            roles = claims.get("roles") or []
            perms = claims.get("permissions") or []
            # The OWNER is verified first in every tenant, so its token is what resolves the HQ
            # branch the branch-scoped checks below need. A `--phase verify` run starts with no
            # branch at all, and a branch-scoped read without one is a 400 — which is "not 403"
            # and would therefore PASS while proving nothing about the caller's authority.
            if p["provisioned"] and not t.hq_branch_id:
                for b in request("GET", "/api/v1/branches", token=token).data(default=[]) or []:
                    if isinstance(b, dict) and b.get("isHq"):
                        t.hq_branch_id = b["id"]
            path = p["verify_path"].replace("{branch}", t.hq_branch_id or "")
            reach = request("GET", path, token=token)
            problems = []
            if p["role"] not in roles:
                problems.append(f"token carries roles {roles}, expected {p['role']}")
            if not perms:
                problems.append("token carries an EMPTY permission list")
            if reach.status == 403:
                problems.append(f"{path} answered 403 for a role that holds its gate")
            if reach.status >= 400 and reach.status != 403:
                problems.append(f"{path} answered {reach.status}, which is neither a refusal nor "
                                f"a result: {reach.raw[:120]}")
            if problems:
                line(email, False, "; ".join(problems))
                failed.append((email, "; ".join(problems)))
            else:
                line(email, True,
                     f"{p['role']:<14} {len(perms):>2} permissions  "
                     f"{p['verify_path'].split('?')[0]} -> {reach.status}")
                passed.append(email)

    print()
    print(f"  {_BOLD}{len(passed)} of {len(passed) + len(failed)} principals authenticated"
          f" and reached a role-appropriate endpoint.{_RESET}")
    if failed:
        print()
        print(f"  {_RED}{_BOLD}THE SEED IS NOT COMPLETE. A partial seed is a failed seed.{_RESET}")
        for email, why in failed:
            print(f"    {_RED}✗{_RESET} {email}: {why}")
        return 1
    print(f"  {_GREEN}Every seeded principal can log in. This is ROADMAP SC6's live evidence.{_RESET}")
    return 0


# ════════════════════════════════════════════════════════════════════════════════════════════
# Reconciliation for a run that starts at a later phase
# ════════════════════════════════════════════════════════════════════════════════════════════

def reconcile_tenants() -> list[Tenant]:
    """Rebuild the tenant list from the platform API, for a run that starts mid-way."""
    out: list[Tenant] = []
    for spec in TENANTS:
        row = find_tenant_by_brand(spec["brand"])
        if not row:
            die(f"tenant '{spec['brand']}' does not exist. Run --phase platform first.")
        t = Tenant(key=spec["key"], brand=spec["brand"], tier=spec["tier"],
                   tenant_id=row.get("id") or row.get("tenantId"), slug=row.get("slug", ""),
                   admin_email=persona_email(spec["key"], "owner"), spec=spec)
        t.features = read_features(t.tenant_id)
        out.append(t)
    return out


def resolve_branches(tenants: list[Tenant], tokens: dict[str, str]) -> None:
    for t in tenants:
        token = tokens.get(t.admin_email)
        if not token:
            continue
        branches = request("GET", "/api/v1/branches", token=token).data(default=[]) or []
        hq = next((b for b in branches if isinstance(b, dict) and b.get("isHq")), None)
        if hq:
            t.hq_branch_id = hq["id"]
        t.branch_ids = [b["id"] for b in branches if isinstance(b, dict)]


def login_all(tenants: list[Tenant]) -> dict[str, str]:
    tokens: dict[str, str] = {}
    for t in tenants:
        for p in PERSONAS:
            email = persona_email(t.key, p["local"])
            token, _ = login(email, persona_password(t.key, p["local"]), t.slug)
            if token:
                tokens[email] = token
    return tokens


# ════════════════════════════════════════════════════════════════════════════════════════════

def corrupt_persona(email: str) -> None:
    """
    T-13-15-D. A verification that cannot fail is not a verification. This deliberately
    breaks one persona's stored password so the next `--phase verify` must fail and must name
    that address. Development stacks only — the host guard has already run.
    """
    record_direct_write(
        what=f"replaced {email}'s stored password hash with an unusable value, ON PURPOSE",
        service="auth-service",
        table="auth_db.users.password_hash",
        reason=(
            "there is no API for breaking an account, and there should not be. This exists so the "
            "verification loop can be shown to FAIL — a verification that cannot fail is not a "
            "verification (T-13-15-D)."
        ),
        replacement="nothing. It is a deliberate fault injection, not a missing endpoint.",
    )
    tid = tenant_id_for_email(email)
    row = sql("auth_db", f"""
        SET app.current_tenant_id = '{tid}';
        UPDATE users SET password_hash = '$2a$12$0000000000000000000000000000000000000000000000000000'
        WHERE email = '{email}' RETURNING email;
    """.strip())
    if not row:
        die(f"no user with address '{email}' — nothing was corrupted")
    print(f"  {_YELLOW}!{_RESET} {email}'s stored password hash has been deliberately replaced.")
    print(f"    Now run:  python3 {Path(__file__).name} --phase verify   (it MUST exit 1 and name it)")
    print(f"    Undo it:  python3 {Path(__file__).name} --phase personas")


def main() -> int:
    ap = argparse.ArgumentParser(description="Seed and verify a complete RestaurantOS environment.")
    ap.add_argument("--phase", choices=["platform", "personas", "business", "verify", "all"],
                    default="all")
    ap.add_argument("--no-repair", action="store_true",
                    help="do not attempt to repair a persona that cannot reach its documented password")
    ap.add_argument("--corrupt-persona", metavar="EMAIL",
                    help="deliberately break one persona's password, to prove the verification can fail")
    ap.add_argument("--i-know-what-i-am-doing", action="store_true", dest="force",
                    help="seed a non-local gateway origin")
    args = ap.parse_args()

    assert_target_is_local(args.force)
    STATE_DIR.mkdir(parents=True, exist_ok=True)

    banner("RestaurantOS seed — phase 13 / plan 13-15 (D-25, D-30)")
    print(f"  gateway : {GATEWAY}")
    print(f"  state   : {STATE_DIR}  (TOTP secrets only; never committed)")
    print(f"  phase   : {args.phase}")
    print()
    print("  Every credential this script creates is DEVELOPMENT-ONLY and documented in")
    print("  scripts/README-seed.md. Rotate every one of them before any deployment.")

    if args.corrupt_persona:
        banner("DELIBERATE CORRUPTION (T-13-15-D)")
        corrupt_persona(args.corrupt_persona)
        print_direct_write_ledger()
        return 0

    started = time.time()
    exit_code = 0

    if args.phase in ("platform", "all"):
        tenants = phase_platform()
    else:
        tenants = reconcile_tenants()

    tokens: dict[str, str] = {}
    if args.phase in ("personas", "all"):
        tokens = phase_personas(tenants, repair=not args.no_repair)
        resolve_branches(tenants, tokens)
    elif args.phase == "business":
        tokens = login_all(tenants)
        resolve_branches(tenants, tokens)

    if args.phase in ("business", "all"):
        phase_business(tenants, tokens)

    if args.phase in ("verify", "all"):
        exit_code = phase_verify(tenants)

    print_direct_write_ledger()

    banner("DONE" if exit_code == 0 else "FAILED")
    print(f"  elapsed {time.time() - started:.0f}s")
    if exit_code == 0 and args.phase in ("verify", "all"):
        print("  Every seeded principal authenticated through the real gateway.")
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
