server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_SEARCH_LOCATIONS:file:/config,classpath:/config}
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/restaurantos/restaurantos-config.git}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        native:
          search-locations: ""
        git:
          uri: ${CONFIG_GIT_URI}
